### ISSUE TITLE
First Start Wizzard

### ISSUE THREAD

**Issue by Rello** [Rello/analytics#103]
- [x] Modal Wizzard
- [x] Multi pages
- [x] Mark as read and store in DB
- [x] Define set of demo reports
- [x] Create demo reports from wizzard

**Comment by Rello** [comment]
https://user-images.githubusercontent.com/13385119/106658480-a22c1180-659d-11eb-9bad-a7b44298ca6a.mov

**Comment by jospoortvliet** [comment]
That is super helpful! It makes it clear you have the 'data import' section, and that visualization is separate. I'd add one more page with the visualization, though. Just to help with that part, too.

Also, a way to see the first run wizart/quick feature overview/how-to might be helpful.

**Comment by Rello** [comment]
![Bildschirmfoto 2021-03-03 um 13 04 13](https://user-images.githubusercontent.com/13385119/109803121-f5d35e80-7c20-11eb-8907-daaf972c1754.png)

**Comment by Rello** [comment]
![Bildschirmfoto 2021-03-04 um 15 48 58](https://user-images.githubusercontent.com/13385119/109981418-2b4f7900-7d01-11eb-9614-a45e7b319ac9.png)

**Comment by vcbd** [comment]
Hi there,
I had the wizard run every time I opened Analytics, and looking into the code I noticed it was spelled "wizzard" in the filename and the controller class. Changing these two to "wizard" solved the issue.
Thanks for this app!
