### ISSUE TITLE
Couldn't find Analytics app on nextcloud app list 

### ISSUE THREAD

**Issue by elhananjair** [Rello/analytics#104]
Hello there I was using Analytics on nextcloud. Recently I have updated NC to the latest stable version [NC 20.0.6]. I was installing apps and wanted to install Analytics too, but the search won't find Analytics... and I have tried from CLI using occ commands like this one:  sudo -u apache php occ app:install Analytics, but still its not working it gives me an error "Error: Could not download app analytics". So what's the problem with it?

**Comment by Rello** [comment]
Hello,
NC has an issue there
https://github.com/nextcloud/server/pull/25335

should be fixed with 20.0.7

**Comment by elhananjair** [comment]
> Hello,
> NC has an issue there
> [nextcloud/server#25335](https://github.com/nextcloud/server/pull/25335)
> 
> should be fixed with 20.0.7

Okay thanks for replying, ok I will wait for the next update. But why not  "sudo -u apache php occ app:install Analytics" work? cause I have downloaded another apps from CLI

**Comment by Rello** [comment]
Hello,
it depends what the apps have in the settings.
I currently have the php-max version of 7.4 - others might have set it to 8.0 already.
if you have 7.4.14, mine does currently not work. the next version of Analytics will also get a higher version

**Comment by elhananjair** [comment]
> Hello,
> it depends what the apps have in the settings.
> I currently have the php-max version of 7.4 - others might have set it to 8.0 already.
> if you have 7.4.14, mine does currently not work. the next version of Analytics will also get a higher version

yeah mine is also 7.4.14, so waiting for NC 20.0.7 fix that? or is there anything from Analytics app side

**Comment by Rello** [comment]
Hello @elhananjair 
20.0.7 was released. could you check already?

**Comment by elhananjair** [comment]
Yeah @Rello I have updated and others apps are shown in search, but still analytics app is not bein shown there.

**Comment by elhananjair** [comment]
But finally I found it on Dashboard section, and downloaded it from there..

**Comment by Rello** [comment]
thank you for the update

**Comment by elhananjair** [comment]
> thank you for the update

👍

**Comment by Rello** [comment]
regarding occ
i am not sure but I think occ is case sensitive and internally all apps are handled with small letters by NC

**Comment by elhananjair** [comment]
> regarding occ
> i am not sure but I think occ is case sensitive and internally all apps are handled with small letters by NC
aww okay I got that.
