### ISSUE TITLE
One Chart Line to much and Gridline color

### ISSUE THREAD

**Issue by Himra** [Rello/analytics#105]
Hello all,

why do I have these additional lines in the chart (see arrows 1)
and why does the colour not change for these gridlines (see arrows 2)? 

![Analytics-Nextcloud](https://user-images.githubusercontent.com/15324567/106615149-6fb5f080-656c-11eb-8c16-e0adc563e9d4.png)

In the chart options I use the following:
`{
	"scales": {
		"xAxes": [{
			"gridLines": {
				"display" : "true",
				"color" : "rgba(255, 255, 255, 0.2)"
			},
			"type": "time",
			"time": {
				"format" : "DD-MM-YYYY HH:mm:ss",
				"displayFormats" : { "day": "MMM DD" },
				"unit" : "day"
			}
		}],
		"yAxes": [{
			"gridLines": {
				"display" : "true",
				"color" : "rgba(255, 255, 255, 0.2)"
			}
		}]
	}
}`

Thank you and greetings
Himra

**Comment by Rello** [comment]
Hi,
sorry for the delay.
can you check the data?
a timeline chart connects whatever values are coming. in your chart it looks like for every chart you have one additional value with an oder date/timestamp which connects it to the beginning again.
there is one reverse linke somewhere

**Comment by Himra** [comment]
Hello Rello,

The data is correct so far. 
It is somehow due to the entries in the chart options.
If I empty the options then I don't have the phenomenon.

Thanks for the great project
Himra

**Comment by Rello** [comment]
Hello,
I cant solve this right now. 
but: i am finalizing the next release. it will include an option to export reports+data. This would be good to see an export of yours to analyze this in detail

**Comment by Himra** [comment]
Thanks for your answer also waiting joyfully the coming release

**Comment by Rello** [comment]
Hello @Himra 
did you update already? if yes, please use the Export feature (Settings->Report->Button at the bottom) and send me the file to https://home.scherello.de/owncloud/s/J8Qysz4cQWfTjYF

**Comment by Himra** [comment]
Hello @Rello,

I have updated and exported, and I find the mistake. After I have deleted the wrong Data all is good.
Thank you for your help and the great project.
Himra

**Comment by Himra** [comment]
Hello @Rello,

the error I meant that I had fixed it was not the error at all, but the problem always occurs at the change of the month. It seems that he messes with the days in the date something

**Comment by Rello** [comment]
do you have more information for me?
like what records would cause this, when its added?
