### ISSUE TITLE
JSON source not adding timestamp

### ISSUE THREAD

**Issue by dutchgecko** [Rello/analytics#106]
I'm trying to add a JSON API source to the app, but when I follow the example instructions at https://github.com/Rello/analytics/wiki/Datasource:-JSON I don't get a timestamp column like the example shows.

My settings:

![image](https://user-images.githubusercontent.com/2513484/107148361-fabf2e00-6952-11eb-9c99-115bba50abbe.png)

Results:

![image](https://user-images.githubusercontent.com/2513484/107148389-132f4880-6953-11eb-8d33-d69e194155d9.png)

The wiki shows an example with timestamp column, but I can never get this column to appear.

**Comment by Rello** [comment]
Hello.
let me check...

impressive number of files by the way 😳

**Comment by Rello** [comment]
thank you for reporting this.
you are right. there is the section for the timestamp, which was only applied to the dataload - but not to the realtime reporting
https://github.com/Rello/analytics/blob/master/lib/Service/DataloadService.php#L186

will take care...

in your case: I think you want to look at advanced=>dataload anyway, isn´t it?
Timestamps really only make sense if you want to report on regular snapshots and they can only be achieved by e.g. daily dataloads.
What do you want to report?

**Comment by dutchgecko** [comment]
The actual use case for me will be for checking the API of Ethminer, with an address such as https://api.ethermine.org/miner/21795cd1cb4e26fdc165aae4028eb33729d11660/currentStats

Because I couldn't get the timestamp to work I tried to replicate the example from the wiki instead and found it didn't work there either.

Will timestamp do what I want in this case, or do I need to set up a custom dataload?

**Comment by Rello** [comment]
Hello,
the timestamp issue is fixed - even so I am pretty sure that its not what you wanted. 
you are looking for the dataload anyway.

I assume that you will monitore e.g. the current Hashrate over time?
...it would be worth another "usecase" in the wiki...

![Bildschirmfoto 2021-02-08 um 20 41 56](https://user-images.githubusercontent.com/13385119/107272520-1824f280-6a4e-11eb-861f-592019d25da8.png)

![Bildschirmfoto 2021-02-08 um 20 42 16](https://user-images.githubusercontent.com/13385119/107272541-2246f100-6a4e-11eb-9a35-d1bd4b010239.png)

**Comment by Rello** [comment]
@dutchgecko 
one addition, in case you want to monitore several values.
I extended the coding to handle several paths, separated by "," so they don´t need to be separated into several dataloads and receive the exact same timestamp

e.g. 
`data/currentHashrate,data/averageHashrate`
