### ISSUE TITLE
Favorite also for shared reports

### ISSUE THREAD

**Issue by jhinvestor** [Rello/analytics#107]
🚀 Feature request | 

Please add the option to favorite a report that has been shared to you from someone else.

(I have never made a post on GitHub, please forgive my ignorance if the format is wrong. Also keep up the great work.)

**Comment by Rello** [comment]
![Bildschirmfoto 2021-02-10 um 21 56 36](https://user-images.githubusercontent.com/13385119/107571177-da110580-6bea-11eb-9ea7-3521964f5475.png)
