### ISSUE TITLE
Error in occ- and scheduled load

### ISSUE THREAD

**Issue by dutchgecko** [Rello/analytics#109]
With the settings looking like this:

![image](https://user-images.githubusercontent.com/2513484/107557089-7500e400-6bd9-11eb-822a-d6756fe1aba2.png)

    > ./occ analytics:load 8

    *   Trying 2606:4700::6812:d9e8:443...
    * Connected to api.ethermine.org (2606:4700::6812:d9e8) port 443 (#0)
    * ALPN, offering h2
    * ALPN, offering http/1.1
    * successfully set certificate verify locations:
    *  CAfile: /etc/ssl/certs/ca-certificates.crt
    *  CApath: /etc/ssl/certs
    * SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
    * ALPN, server accepted to use h2
    * Server certificate:
    *  subject: C=US; ST=CA; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
    *  start date: Jul 29 00:00:00 2020 GMT
    *  expire date: Jul 29 12:00:00 2021 GMT
    *  subjectAltName: host "api.ethermine.org" matched cert's "*.ethermine.org"
    *  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
    *  SSL certificate verify ok.
    * Using HTTP2, server supports multi-use
    * Connection state changed (HTTP/2 confirmed)
    * Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
    * Using Stream ID: 1 (easy handle 0x55a2429961e0)
    > GET /miner/[address removed]/currentStats HTTP/2
    Host: api.ethermine.org
    accept: */*
    ocs-apirequest: true

    * old SSL session ID is stale, removing
    * Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
    < HTTP/2 200 
    < date: Wed, 10 Feb 2021 18:53:55 GMT
    < content-type: application/json; charset=utf-8
    < content-length: 380
    < set-cookie: __cfduid=ddfb8de661017f554115163bdb17ca2831612983235; expires=Fri, 12-Mar-21 18:53:55 GMT; path=/; domain=.ethermine.org; HttpOnly; SameSite=Lax
    < access-control-allow-origin: *
    < cache-control: public, max-age=60
    < etag: W/"17c-aaSboMKDSGwLIciItBqbZ4OUbn4"
    < strict-transport-security: max-age=15552000; includeSubDomains
    < x-content-type-options: nosniff
    < x-dns-prefetch-control: off
    < x-download-options: noopen
    < x-frame-options: SAMEORIGIN
    < x-xss-protection: 1; mode=block
    < cf-cache-status: HIT
    < age: 48
    < expires: Wed, 10 Feb 2021 18:54:55 GMT
    < accept-ranges: bytes
    < cf-request-id: 082ee40d6100000b4fc3b64000000001
    < expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
    < server: cloudflare
    < cf-ray: 61f809289fcb0b4f-AMS
    < 
    * Connection #0 to host api.ethermine.org left intact
    An unhandled exception has been thrown:
    Error: Call to a member function getUID() on null in /var/www/owncloud/nextcloud/apps/analytics/lib/Db/ShareMapper.php:220
    Stack trace:
    #0 /var/www/owncloud/nextcloud/apps/analytics/lib/Activity/ActivityManager.php(103): OCA\Analytics\Db\ShareMapper->getSharedReceiver()
    #1 /var/www/owncloud/nextcloud/apps/analytics/lib/Activity/ActivityManager.php(68): OCA\Analytics\Activity\ActivityManager->sendToUsers()
    #2 /var/www/owncloud/nextcloud/apps/analytics/lib/Controller/DataloadController.php(186): OCA\Analytics\Activity\ActivityManager->triggerEvent()
    #3 /var/www/owncloud/nextcloud/apps/analytics/lib/Command/Load.php(48): OCA\Analytics\Controller\DataloadController->execute()
    #4 /var/www/owncloud/nextcloud/apps/mail/vendor/symfony/console/Command/Command.php(255): OCA\Analytics\Command\Load->execute()
    #5 /var/www/owncloud/nextcloud/apps/mail/vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run()
    #6 /var/www/owncloud/nextcloud/apps/mail/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
    #7 /var/www/owncloud/nextcloud/apps/mail/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun()
    #8 /var/www/owncloud/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
    #9 /var/www/owncloud/nextcloud/console.php(100): OC\Console\Application->run()
    #10 /var/www/owncloud/nextcloud/occ(11): require_once('/var/www/ownclo...')
    #11 {main}

**Comment by Rello** [comment]
Hello,
thank you for this finding. I will check.
But in your case isn´t the hourly/daily schedule in the dropdown above better?

**Comment by dutchgecko** [comment]
I found that the hourly schedule only ran once every 12 hours. Also I wouldn't mind checking more frequently as the data updates every 10 minutes or so.

**Comment by Rello** [comment]
technically its every 58 minutes
https://github.com/Rello/analytics/blob/master/lib/BackgroundJob/Hourly.php#L32
will test on my side later to double check

**Comment by dutchgecko** [comment]
![image](https://user-images.githubusercontent.com/2513484/107579698-d040cf80-6bf5-11eb-8b58-52b921912b85.png)

It only updates every 12 hours or when I manually click the button... additionally only reportedHashrate (the first line configured) is updated automatically even though all three are set to update.

Basically the auto update seemed super buggy to me so I was hoping to use `occ` instead, but that bugged too...

**Comment by Rello** [comment]
its tied to the occ cron job. you have scheduled it correctly to run every 5 minutes, do you?

**Comment by dutchgecko** [comment]
Yep, the cron for nextcloud runs every five minutes as per the manual.

**Comment by Rello** [comment]
found the issue!
thank you

**Comment by Rello** [comment]
note: an error in a background job causes NC to set the `reserved_at` flag.
this blocks further executions for safety reasons and it´s reset every 24 hours
