### ISSUE TITLE
Compatible with dark theme

### ISSUE THREAD

**Issue by Ludovicis** [Rello/analytics#11]
Hello Rello,

Thanks for your application.
Can you add the possibility to use your application with nextcloud black theme, please ?
See my screenshot capture
![image](https://user-images.githubusercontent.com/16205280/70901092-62514600-1ffa-11ea-9ba5-5fab8d1e2239.png)

**Comment by Rello** [comment]
I will check

**Comment by Rello** [comment]
Hello,
only the table could be done for now. the chart css is a little more complicated and will be moved to the next release.

thank you

**Comment by Rello** [comment]
first version released; chart still in progress

**Comment by Rello** [comment]
Hello,

the switch from highcharts to chart.js with the upcoming release will enable the full dark-theme support.

![Screenshot 2020-03-10 at 12 58 13](https://user-images.githubusercontent.com/13385119/76310292-d08e6780-62ce-11ea-83ee-73bdb0318894.png)

**Comment by Rello** [comment]
v2.1.0 released
