### ISSUE TITLE
Dataload issue with "External file"

### ISSUE THREAD

**Issue by dgedgedge** [Rello/analytics#110]
Hi,
I tried to use the "Scheduled dataloads".
I created a data load from https://www.data.gouv.fr/fr/datasets/r/0f376780-631c-4689-ba46-bf52b7ca3a67 csv
![Capture d’écran 2021-02-17 à 13 54 36](https://user-images.githubusercontent.com/17098018/108207257-cb18de80-7127-11eb-8ab3-671ab649337d.png)
and tried to use the loaded data. I expected it to be in the database : 
![Capture d’écran 2021-02-17 à 13 56 41](https://user-images.githubusercontent.com/17098018/108207427-04e9e500-7128-11eb-99c8-1f9f01363a7a.png)
but no data seems to apear...
Even by doing occ analytics:load 2 

Is it the rigth pattern ?
Did I do something wrong ?
Note:
Nextcloud 20.0.7
Analytics 3.3.1
Debian GNU/Linux 10 (buster)
Mariadb...

**Comment by Rello** [comment]
Hello,
thank you for reporting!
there is really a minor issue, which was not caught during testing.
Your setup is correct. I will push a fix version

![Bildschirmfoto 2021-02-17 um 22 03 11](https://user-images.githubusercontent.com/13385119/108267783-edcce680-716b-11eb-82dc-8d210dc53d5d.png)

**Comment by Rello** [comment]
3.3.2 released

**Comment by dgedgedge** [comment]
OK it does work when you issue a occ analytics:load, but the button "charger maintenant", "upload now" does not work.

Sequence : 
1- Create a new report.
2- Add a data source 
3- Press on "upload now"
4- Refresh the graphics...

The data is only loaded after a analytics:load only.

**Comment by dgedgedge** [comment]
Usure if a second issue is required, but When you put 2 data sources, the second one does seem  to upload even with a analytics:load.

Note: I am trying to load the different colums in one single graphic. But it seems not possible as in the concept it seems that the different graphics has to be distinguished by a tagg, which is not clear in the wiki.



![Capture d’écran 2021-02-18 à 08 31 30](https://user-images.githubusercontent.com/17098018/108321255-331d0280-71c4-11eb-801c-9c732d573f98.png)
![Capture d’écran 2021-02-18 à 08 31 45](https://user-images.githubusercontent.com/17098018/108321283-3adca700-71c4-11eb-96d1-ad5dd4731b1a.png)

**Comment by Rello** [comment]
Hello,
I see what you want to do - but thats still difficult at this early step of Analytics.

first, there is a little flag next to the dataload button. that should be "Test". I need to check why the text is not shown. when you remove the flag, the button will load the data manually

second: you selected to delete the data from before (last dropdown). this will clear the whole dataset (both loads, as it can not recognize which is coming from where).
So you would need to keep this. in your case its fine, because the dataload as an "update" logic. if you load the whole data every time, it will not double it, it will just update the existing ones if changes.

But yes, you mentioned correctly. to get them all in, they would need a different indicator e.g. in the first column. thats difficult at the moment.
one workaround could be - but not nice - to use column 1 for the first load and column2 for the second. The table/ledgend would look odd, but in the chart you could combine them with columns/lines

**Comment by Rello** [comment]
I was just thinking about it - let me know what you think:

- in the column selection you select `1,2,6` e.g.
- In you case, column 1 does not have much meaning and you would like to use that for a characteristic for the load
- I could think about making this input box flexible by offering a way to use constants with " "
- e.g.: `"data1",2,6`

what do you think? would this sound "intuitive"?

**Comment by dgedgedge** [comment]
> I was just thinking about it - let me know what you think:
> 
>     * in the column selection you select `1,2,6` e.g.
> 
>     * In you case, column 1 does not have much meaning and you would like to use that for a characteristic for the load
> 
>     * I could think about making this input box flexible by offering a way to use constants with " "
> 
>     * e.g.: `"data1",2,6`
> 
> 
> what do you think? would this sound "intuitive"?

Yes, the idea would be to anable the possibility to load 2 or three data sets and for each dataset to be able to gat the data set.

In fact organisation of csv could be of two main ways : 
1- The one I now understand is to have A first colum as a selector of data, then the label / date, then the data.
     Which is the way a flow / multiple flows would be collected each providing one value at a time.
      Note: This is not obvious from the documentation/interface.

2- The second one is to have one line for each data, but multiple colums for the values.
     Which is the way a multisensor device could produce.
     Or a synthetic updated complete file (My case) cold be produced.

In case of flows with multiple values or updated complete CSV, the issue is that data is organized by columns.

If we load multiple data sets with method one, the issue is how to well organize the data on the Xaxis.
I tried not to reset the data in my previous example and that leads to this : 

![Capture d’écran 2021-02-18 à 13 35 42](https://user-images.githubusercontent.com/17098018/108357855-48a72200-71ee-11eb-9548-aa1c8f863ea4.png)

which is not the intended behaviour, but I think I understand in the view of the concept you seems to follow.

In order to be able to use method 1 with multiple data sets, that are "complete" updated datasets, we must then be able to "order" on the xaxis the samples for the two datasets.....

**Comment by dgedgedge** [comment]
> In you case, column 1 does not have much meaning and you would like to use that for a characteristic for the load

Now I do better understand the dataconcept.
Your proposal seems great.

Did you implement such a thing?

I would have put the fixed value as the X absis.
