### ISSUE TITLE
API getData endpoints

### ISSUE THREAD

**Issue by Himra** [Rello/analytics#111]
Hello @Rello,

does the API currently already have the ability to retrieve data (GET). For example the last value of an entry.
If no, is this planned for future versions?

Thanks for the great project
Himra

**Comment by Rello** [comment]
Hello,
I am not sure what you mean.
can you give me more details?

**Comment by Himra** [comment]
Actually I just wanted to know if you can read values via the API not only write and delete.

**Comment by Rello** [comment]
Hi,
was added with the upcoming release
https://github.com/Rello/analytics/pull/151
https://github.com/Rello/analytics/wiki/API#dataGet
