### ISSUE TITLE
Database issue on NC21 installation

### ISSUE THREAD

**Issue by J0WI** [Rello/analytics#113]
A fresh Nextcloud 21/PHP 7.4 installation fail to install the app with the following error: There is no table with name '.oc_analytics_facts' in the schema.

**Comment by Rello** [comment]
Hello,
anything else in the nextcloud log?
I did not have this issue until now

**Comment by helmut72** [comment]
Same error message for me. NC21/PHP8

**Comment by Rello** [comment]
Hello,
do you have an entry in the nextcloud.log?
where the error is coming up?

**Comment by Rello** [comment]
found something
"Exception":"Exception","Message":"Undefined class constant 'DECIMAL'"

**Comment by Rello** [comment]
new version was pushed.
I still need to figure out how to clean this up now

**Comment by Rello** [comment]
@helmut72 @J0WI 
I released a new version. I am not sure how the installer will behave now. could you give me feedback?
thank you

**Comment by AleksovAnry** [comment]
Issue still persists

**Comment by Rello** [comment]
@AleksovAnry you also installed on a brand new NC21, correctly?
because upgrade are not affected as far as I could test.

is it possible that you execute the following occ command?
`occ migrations:status analytics`

**Comment by AleksovAnry** [comment]
Yes, brand new installation, completed yesterday.
![Снимок экрана 2021-02-24 в 16 11 11](https://user-images.githubusercontent.com/21116220/109005750-5ca1c680-76bb-11eb-968e-5e516f47e71a.png)

**Comment by Rello** [comment]
yes, thats the one who failed - I corrected it.
could you try
`occ migrations:execute analytics 020500Date20200815180000`

**Comment by AleksovAnry** [comment]
` Migration step 'OCA\Analytics\Migration\Version020500Date20200815180000' is unknown `

**Comment by Rello** [comment]
Hello,
just do make sure: is it still "installed" in your instance or did you delete it already when doing the occ command?
Because it would need to have the file available I would guess

**Comment by AleksovAnry** [comment]
Of course! I repeat all steps again
1) Delete Analytics
2) Install Analytics from Apps --> here i got "There is no table with name 'nextcloud.oc_analytics_facts' in the schema." error
3) Ran `sudo -u www-data php occ migrations:execute analytics 020500Date20200815180000` -->  here i got " Migration step 'OCA\Analytics\Migration\Version020500Date20200815180000' is unknown " error

**Comment by AleksovAnry** [comment]
Hey, if u need, i can create VM's with NC21/20/19 inside my cluster and gave 2 u access 4 it.

**Comment by Rello** [comment]
what happens when you run
`sudo -u www-data php occ migrations:execute analytics 020400Date20200515185352`

this is the first migration. if this works, we could start from the beginning and run 1 by 1.
... I need to start some containers on my side to test it. just need to finish my work first.
if you can try in the meantime, it could help

**Comment by Rello** [comment]
Hello,
there is an issue with the way the migration works in case of errors.
I just talked to the NC team and they will optimize something here. In the meantime, the issue needs to be solved on the database level.

to fix it, a command needs to be executed on the database

`DELETE FROM nextcloud.oc_migrations WHERE app = 'analytics'`

Afterwards, the updated 3.3.3 can be installed as normal.
I know, its very unfortunate. I hope you can perform this step.
Please let me know

**Comment by AleksovAnry** [comment]
Hello!
Yes, this helps.

**Comment by nikrozman21** [comment]
Hi. I'm seeing the same issue.

Doing ```DELETE FROM nextcloud.oc_migrations WHERE app = 'analytics'``` didn't help at all.
I've also tried ```occ migrations:status analytics``` and that returns
```Migration step 'OCA\Analytics\Migration\Version3005Date20210508180000' is unknown```.

I tried executing ```php occ migrations:execute analytics 3005Date20210508180000```, but all I got was
```Migration step 'OCA\Analytics\Migration\Version3005Date20210508180000' is unknown```.

I assumed this is because it fails to install at all, however the same issue happens when I click on the install button as shown here:

![image](https://user-images.githubusercontent.com/20975185/119223095-d3eac900-baf7-11eb-96bf-656dc703319d.png)

(button sais "Download and install")

Can someone point me into the right direction on what to do to get this working?

Thank you in advance.

**Comment by Rello** [comment]
I think I found the issue.
NC team adviced to change the naming of the migration files.
I need to fix this

**Comment by Rello** [comment]
@nikrozman21 
can you please try the released 3.5.1 again and let me know?

**Comment by nikrozman21** [comment]
> @nikrozman21
> can you please try the released 3.5.1 again and let me know?

Looks like that worked.
Thank you.
