### ISSUE TITLE
[Enhancement] Set default types for preview

### ISSUE THREAD

**Issue by sirdrakeistda** [Rello/analytics#116]
A data set has normally type, x_value and y_value. In the preview in Analytics and the preview in the Dashboard of the Graph there are maximum 4 types plotted. Am I able to change these four types?

I have a data set with type=country and I would like to have my favourite countries in the preview. Is this actually possible (e.g. with additional Options)?

**Comment by Rello** [comment]
Hello,

is it possible that you share the details of the data, to make it clear?
you can use the export-report button in the sidebar and past the text here, if it is ok for you.
once I got it, I will remove it again...

...yes, there is a filter for 4 dataseries as the previews would be too small.
you can use your report and filter it (and save the filter). this would then apply for the preview. did you try this one?

**Comment by sirdrakeistda** [comment]
My data:
https://covid19.who.int/WHO-COVID-19-global-data.csv
I take for one data set the columns 3,1,6 and I would like four countries in the preview (e.g. Brazil,France,Russian Federation,China). In the main Graph I need all countries.

**Comment by Rello** [comment]
Hello,
at the moment this is not yet possible. its in progress.
what you want is 2 different reports/view on the same data.
https://github.com/Rello/analytics/issues/33

until then, just create 2 reports with the same datasource and filter the one for the dashboard.

**Comment by sirdrakeistda** [comment]
It think this wont work, because filter are not available for external data sources.

There is a workaround with this Dataset by importing only some columns: (mostly equal data, but ordered  in a different way)
https://www.dkriesel.com/_media/corona-cases.csv
But If I import a dataset with so many columns (all of them) Analytics displays only part of the graph. It is only possible to see the rest by scrolling. Maybe it would be an idea to have the graph on a fixed postion and scroll only trough the Table. 

I tried to use more then three columns. Is this actually possible (It didn't worked for me)? This issue seemed like it would work (on the picture there are 4 columns selected):
https://github.com/Rello/analytics/issues/101

Thank you for your great work. Analytics is getting with every Version better. I like this App very much.

**Comment by dgedgedge** [comment]
> It think this wont work, because filter are not available for external data sources.
> 
> There is a workaround with this Dataset by importing only some columns: (mostly equal data, but ordered in a different way)
> https://www.dkriesel.com/_media/corona-cases.csv
> But If I import a dataset with so many columns (all of them) Analytics displays only part of the graph. It is only possible to see the rest by scrolling. Maybe it would be an idea to have the graph on a fixed postion and scroll only trough the Table.
> 
> I tried to use more then three columns. Is this actually possible (It didn't worked for me)? This issue seemed like it would work (on the picture there are 4 columns selected):
> #101
> 
> Thank you for your great work. Analytics is getting with every Version better. I like this App very much.

I think you have the same issue a I had understanding the concept of analytics at the begining : 

Data sets shall have only 3 columns:
1- The first one is the "identifyer" of the curve.
2- Is the Xaxis.
3- is the Y axes

Trying to import the file directly leads to nothing.
If I did understood right the #101 is for future..

**Comment by Rello** [comment]
thats a good summary of the current status:
```
1- The first one is the "identifyer" of the curve
2- Is the X axis
3- is the Y axes
```

If you are using a realtime interface + table display, many columns can be displayed.
The chart will only display the last column in that case

if you are using persisted data (via dataload), only 3 columns are possible at the moment.
I am working on a better solution there, but that kind of deep changes require sensitive testing.
