### ISSUE TITLE
Float numbers in graph tooltips

### ISSUE THREAD

**Issue by dgedgedge** [Rello/analytics#117]
Hi,
I am testing on nextcoud 20, Analytics 3.3.3 on up to date Buster.
I am working on the following dataset which seems to me interesting.
https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv
And particularly on colums : 3,4,17

The value is a decimal value which goes below 1.

When I put my mouse on the graphic I get this : 

![Capture d’écran 2021-03-05 à 20 30 02](https://user-images.githubusercontent.com/17098018/110208025-05ec7780-7e87-11eb-9d19-0a5addc92cfd.png)

The Value shown in the pop up is just 1 but should be 1,xxx

Same apply if I look at a value below 1, it shows 0 in the pop up.

It would be great to improve this and have a decimal/floating value shown.

**Comment by Rello** [comment]
![Bildschirmfoto 2021-03-07 um 10 44 06](https://user-images.githubusercontent.com/13385119/110235752-0db52600-7f32-11eb-89d3-5098a1204c67.png)
solved with the next release
