### ISSUE TITLE
Charts: customize colors

### ISSUE THREAD

**Issue by ares** [Rello/analytics#119]
Hello,

I couldn't find a way to specify a custom color for specific data. Neither through chart options nor data options. Is this somehow possible?

**Comment by Rello** [comment]
Hello,
yes, thats a todo. I need to find a way to integrate it.
I am moving to the new chart version first. then I will take care

**Comment by Rello** [comment]
<img width="648" alt="Bildschirmfoto 2021-07-10 um 21 31 30" src="https://user-images.githubusercontent.com/13385119/125174494-32fabf00-e1c6-11eb-94bc-ba17fa76ed72.png">

**Comment by ares** [comment]
:clap: looking forward to test this

**Comment by mstyp** [comment]
Hello. Will it be possible to change the Color of Segments of a Doughnut Chart?
