### ISSUE TITLE
persist legend selections (hidden/visible)

### ISSUE THREAD

**Issue by ares** [Rello/analytics#120]
The chart with more than 4 lines shows only 4 lines by default, I need to open the legend and click crossed lines to display them. Could this be made optional?

**Comment by Rello** [comment]
Hello,
yes, thats a todo. I need to find a way to integrate it

**Comment by Mannshoch** [comment]
currently It's not possible to save the state of views. Please allow to save the viewing legend Items. It would also be nice If there is an option that not viewed Items change in an half opaque state so you have an Idea about other items in Background.

**Comment by Rello** [comment]
Hi,
yes. I still need to find a way to do this in a usable way

**Comment by Rello** [comment]
Hello,
I implemented a solution here. I am currently doing the testing in all ways.
There will not be a setting to change the default of 4 - this will remain.
but once the user did any change in the legend, the "save report" icon will come up so the user has the possibility to persist this setting also (same as any other chart option) - or discard it.

**Comment by Rello** [comment]
4.3.0 released
