### ISSUE TITLE
Sharing link not working

### ISSUE THREAD

**Issue by dgedgedge** [Rello/analytics#121]
Hi,
I am testing on nextcoud 20, Analytics 3.3.3 on up to date Buster.
I have tried to share graphics with links (password or not), and the result is a nearly blank page with only the titles.
The graphics does not seems to appear.

Note: Sharing with users connected works.

**Comment by Rello** [comment]
Hi,
thank you for the report.
I am planning a complete test of the 3.4 version today. I will have a look there.
any error in the browser console?

**Comment by dgedgedge** [comment]
No no error/warning in the journal of nextcloud.
In a FireFox console : 
![Capture](https://user-images.githubusercontent.com/17098018/110756581-aefdee00-824a-11eb-8f54-308266065ad6.JPG)
In a Chrome console : 
![Capture](https://user-images.githubusercontent.com/17098018/110756934-19af2980-824b-11eb-9cb8-b935c82f5ea9.JPG)

**Comment by Rello** [comment]
the last row is the issue.
I will check, but I think its not there in the new version anymore.
I will confirm
