### ISSUE TITLE
Filter usability enhancements

### ISSUE THREAD

**Issue by dgedgedge** [Rello/analytics#122]
Hi,
I am testing on nextcoud 20, Analytics 3.3.3 on up to date Buster on a J4105 cpu.

1- I am a bit surprised by the behaviour of the filter / presentation menue.
![Capture d’écran 2021-03-12 à 07 02 21](https://user-images.githubusercontent.com/17098018/110899195-f8a91000-8300-11eb-868a-d7b06a00f520.png)

There is 2 different behaviours that are not homogeneous  : 
- The filters, when changed, have to be saved for being associated to the graphic and stay remanent.
- The presentation menue (Fist or second axes), (Column or line). is remanent without needing saving to be sticky/remanent.

I thing it  should be improved by managing the two menus consistently.

2- When editing filters (List of values), we don't get the old setting of value. An improvement could be to put in a text field the old one to enable the user to edit it...
This later improvement is mabe linked to futur dev. stories.

**Comment by Rello** [comment]
Hello,
yes, you are correct. there is still an open todo.
the second one is also a valid point - also on the todo list

**Comment by Rello** [comment]
Request 2 was done as a quick fix.
The filters will be prefilled. 
with a little "but": it will only show one filter. if there is a filter on 2 dimensions, both can not - yet - be displayed. this has to come later

**Comment by Rello** [comment]
Filter save logic also for chart options #123

**Comment by dgedgedge** [comment]
> Request 2 was done as a quick fix.
> The filters will be prefilled.
> with a little "but": it will only show one filter. if there is a filter on 2 dimensions, both can not - yet - be displayed. this has to come later

I did not mention it as I did supposed that it was not developped yet, but the "and"/"et" element is allways grey on my installaton.

![Capture d’écran 2021-03-12 à 10 58 44](https://user-images.githubusercontent.com/17098018/110924400-46824000-8322-11eb-9e87-6c6b3190e2d0.png)

Or I don't understand the "2 dimensions" aspect of your answer.

**Comment by Rello** [comment]
Hello,

correct, its still grey. its prepared to show several filters and combine them with and/or. but thats planned for later
