### ISSUE TITLE
New key in l10n

### ISSUE THREAD

**Issue by AleksovAnry** [Rello/analytics#129]
Hello! Need new keys in files. First start wizard need translation. All keys. +in attachment

![Снимок экрана 2021-03-13 в 18 24 52](https://user-images.githubusercontent.com/21116220/111041373-ed60fc00-8448-11eb-80fa-feaac1eea777.png)

**Comment by Rello** [comment]
Hello,
I will check what is missing. thank you for the screenshot.

the first start wizard will not be translated at the moment. this effort is not worth the limited time. lets focus on the daily used fields first
