### ISSUE TITLE
occ command error

### ISSUE THREAD

**Issue by sirdrakeistda** [Rello/analytics#130]
I'm running Analytics 3.4 with NC 21 on a Rasberry Pi 3B+.
```
sudo -u www-data php occ analytics:load 19
Killed
```
I don't know why this happens. I don't see anything interesting in the logs.

My Dataset:
https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv
Columns: 
3,4,42

**Comment by sirdrakeistda** [comment]
There happens something strange:
The imported data (in graph and table doesn't match with the imported data in the test import. Are there different import procedures for test and import to internal database?

**Comment by sirdrakeistda** [comment]
Another Dataset load crashes, but this time with errors:
```
sudo -u www-data php occ analytics:load 15
An unhandled exception has been thrown:
Error: Undefined constant Symfony\Component\Console\Command\Command::SUCCESS in /var/www/nextcloud/apps/analytics/lib/Command/Load.php:49
Stack trace:
#0 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Analytics\Command\Load->execute()
#1 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#2 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#3 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#4 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#5 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#6 /var/www/nextcloud/occ(11): require_once('...')
```
I'm not sure if they are related.

Dataset:
https://opendata.arcgis.com/datasets/917fc37a709542548cc3be077a786c17_0.csv
Columns 8,9,44

**Comment by Rello** [comment]
Hello,
sorry for the delay. it will be fixed with ne next version
