### ISSUE TITLE
Error when sharing xlsx report

### ISSUE THREAD

**Issue by sibergad** [Rello/analytics#133]
When using xlsx as a data source in a view without authorization, I get an error:

{"reqId":"ZUnP6fCp0HSIdAlpeRP4","level":3,"time":"2021-03-14T20:45:04+00:00","remoteAddr":"78.29.109.130","user":"--","app":"index","method":"GET","url":"/index.php/apps/analytics/data/public/PolWUgq15YTSmPl","message":{"Exception":"OC\\User\\NoUserException","Message":"Backends provided no user object","Code":0,"Trace":[{"function":"getUserFolder","class":"OC\\Files\\Node\\Root","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Files/Node/LazyFolder.php","line":66,"function":"call_user_func_array"},{"file":"/var/www/html/nextcloud/lib/private/Files/Node/LazyRoot.php","line":41,"function":"__call","class":"OC\\Files\\Node\\LazyFolder","type":"->"},{"file":"/var/www/html/nextcloud/apps/analytics/lib/Datasource/Excel.php","line":84,"function":"getUserFolder","class":"OC\\Files\\Node\\LazyRoot","type":"->"},{"file":"/var/www/html/nextcloud/apps/analytics/lib/Controller/DatasourceController.php","line":125,"function":"readData","class":"OCA\\Analytics\\Datasource\\Excel","type":"->"},{"file":"/var/www/html/nextcloud/apps/analytics/lib/Controller/OutputController.php","line":116,"function":"read","class":"OCA\\Analytics\\Controller\\DatasourceController","type":"->"},{"file":"/var/www/html/nextcloud/apps/analytics/lib/Controller/OutputController.php","line":162,"function":"getData","class":"OCA\\Analytics\\Controller\\OutputController","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"readPublic","class":"OCA\\Analytics\\Controller\\OutputController","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/nextcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/nextcloud/lib/private/Files/Node/Root.php","Line":373,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36","version":"21.0.0.18","id":"604e75f44be9e"}

**Comment by Rello** [comment]
solved with the next release
