### ISSUE TITLE
Append data to existing collection

### ISSUE THREAD

**Issue by Chaemelion** [Rello/analytics#134]
I would love to be able to grab a single sample of a dataset using the HTML grabber (or any of the data sources, really), rather than the entire dataset. For an example, it would be really cool to use the HTML grabber to get the price for an Amazon product, and then use cron to trigger the sampling of this dataset on a regular interval. Thank you for the amazing plugin, btw.

**Comment by Rello** [comment]
hello,
can you send an example?
some datasources as github have a limit field already. what is your regex in your example?

**Comment by Chaemelion** [comment]
I'm not entirely sure what you mean by a limit field, but here's my regex. It works perfectly on the Amazon us site at least.
`/<span id=\"(?<dimension>.*)block_ourprice\".*>\$(?<value>.*)<\/span>/`

**Comment by Rello** [comment]
Hey,
but thats how it works?!

as long as you set `timestamp=true` and `delete data = no`, it will add the data to the report with a timestamp to show in a timeline chart

then you can also use the scheduler in the right dropdown - you don´t need to schedule via occ here
![Bildschirmfoto 2021-03-15 um 19 22 46](https://user-images.githubusercontent.com/13385119/111202133-d397f400-85c3-11eb-9973-fe4d6a6d8b8e.png)

**Comment by Chaemelion** [comment]
Oh.. well that's exactly what I'm looking for. I'm running version 3.4.1 and I have the timestamp option, but there's no delete data option. What am I missing here?

**Comment by Rello** [comment]
show me a screenshot of your setting.
are you using the advanced configuration -> dataloads?
 
don´t use the standard basic setting. this is only for realtime reporting of the current data

**Comment by Chaemelion** [comment]
I've only ever seen "Data maintenance is not possible for this type of report" on the advanced dataloads tab.

![Nextcloud_Analytics_1](https://user-images.githubusercontent.com/945991/111238358-4f4a6e80-85cd-11eb-8917-93ae37ea0f7c.png)

![Nextcloud_Analytics_2](https://user-images.githubusercontent.com/945991/111238371-57a2a980-85cd-11eb-9f10-7f5b75b56b27.png)

**Comment by Chaemelion** [comment]
Ahh, I see. You can't setup _anything_ in the basic settings or you don't see anything under advanced dataload. My mistake, I see it all now. Sorry for wasting your time, I'll make it up to you via paypal.

**Comment by Rello** [comment]
Hi,
its still an open todo. i think i need to make it more clear on when to use realtime or when to use internal-data+dataloads

but thank you for your kind support
