### ISSUE TITLE
Issues with bulk data upload

### ISSUE THREAD

**Issue by dgedgedge** [Rello/analytics#136]
Hi,
I am testing on nextcoud 20, Analytics 3.4.1 on up to date Buster.
I load a set of graphics on the basis of : 
https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv

The graphic which has a strange behaviour is data 1,3,10

The graphic is loaded each day with an automatic reset.

After the night here is the graphic : 

![Capture d’écran 2021-03-20 à 06 32 17](https://user-images.githubusercontent.com/17098018/111861272-3800dd80-894d-11eb-9982-35ddae720e68.png)

I was surprised with the glitch showed by the arrows.
So I reloaded the data graphic with the menu load data.
The result was then what I was waiting for : 

![Capture d’écran 2021-03-20 à 07 17 56](https://user-images.githubusercontent.com/17098018/111861309-6f6f8a00-894d-11eb-9cf5-d6af284be2c8.png)

This behavior is reproductible on my server at least. Each morning I reload this particular graphic which has some glitches introduced by the night load.

Notes : 
The data load did work correctly with release 3.3.3 but with some different data as the file changes more or less each day by data addition.
I don't know when the data source is updated in the git repository.

Generations of all my graphics ends at 01:00:23 and has lasted for 20 minutes and 22 seconds.
Save process impact on the nextcloud services (maintenance mode + Stop database) last from 00:29:00 to 00:32:00.

**Comment by Rello** [comment]
hello,
let me try it on my side...

**Comment by sirdrakeistda** [comment]
I have the same problem. In my setup Analytics adds the new data on the old data (I tried also to switch delete before load on and off, there is no difference).

**Comment by Rello** [comment]
Hello,
i am looking into this already. I can also see strange results. There seems to be a relation to the batch-commits to the database which was introduced with 3.4 to enable big dataloads.
Will get back...

**Comment by dgedgedge** [comment]
Please note that I do have 11 other graphics either on the same file (not the same data), or other data that works correctly.
They have apprimatively the same config.

**Comment by Rello** [comment]
Hello,
I think I found the issue. its related to the bulk size + the big amount of errors (empty values) in this file.
I change the logic and will do some more testing

**Comment by sirdrakeistda** [comment]
There could be a second problem related to this problem. The Data in the Dashboard has another colour than the data in Analytics (!=0 yellow,<50 green, >100 red). The colour in Analytics is red (number >100 because off adding data bug). The Number in the dashboard is green (same number, same report). It makes no difference between the case the original number is >100 or <100.

**Comment by Rello** [comment]
![Bildschirmfoto 2021-03-21 um 18 28 34](https://user-images.githubusercontent.com/13385119/111914685-40533880-8a73-11eb-9f88-0e529eb70b80.png)
works for me.
I will see if I could find a reason

**Comment by sirdrakeistda** [comment]
![Bildschirmfoto vom 2021-03-21 18-35-35](https://user-images.githubusercontent.com/35723909/111914963-70e7a200-8a74-11eb-88a3-7c03c2f0b67c.png)
This is the same report. One time in the dashboard and one time in Analytics. (Because off adding data the value is not the real value, the real value is >50 and <100 and should be yellow).

**Comment by sirdrakeistda** [comment]
I think I understood my problem more. Is it possible that the issue of different colours in Dashboard and Nextcloud App is caused because of the different notation of decimals? English people write 12,142.00 in other countrys (like my country) it is written 12.142,00. I found out, that the treshhold value 50 in Analytics is the treshold value 50.000,00 in the dashboard. So it seems to be an issue caused by the different decimal notation.

I thought first it is related to this issue here, but this seems now false. Should I open a new issue?

**Comment by dgedgedge** [comment]
Hi,
The issue still exists on V3.

After the night and automatic upload : 

![Capture d’écran 2021-05-20 à 07 41 38](https://user-images.githubusercontent.com/17098018/118925922-d0acdd00-b93f-11eb-9aff-2b8462bea31f.png)

After manual upload : 

![Capture d’écran 2021-05-20 à 07 43 15](https://user-images.githubusercontent.com/17098018/118926009-ecb07e80-b93f-11eb-9c84-68d3a097e273.png)

Note: I have 12 Graphics of the same nature from the same git fileset serveur.

Server configuration detail

Operating system: Linux 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64

Webserver: Apache (apache2handler)

Database: mysql 10.3.27

PHP version: 7.3.27-1~deb10u1

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, exif, msgpack, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, memcached, Zend OPcache

Nextcloud version: 21.0.1 - 21.0.1.1

Updated from an older Nextcloud/ownCloud or fresh install:

Where did you install Nextcloud from: unknown

<details><summary>Signing status</summary>

Array ( )

</details>

<details><summary>List of activated apps</summary>

Enabled:
 - accessibility: 1.7.0
 - activity: 2.14.3
 - admin_audit: 1.11.0
 - analytics: 3.5.0
 - bruteforcesettings: 2.1.0
 - calendar: 2.2.1
 - carnet: 0.23.8
 - checksum: 1.1.2
 - cloud_federation_api: 1.4.0
 - comments: 1.11.0
 - contacts: 3.5.1
 - contactsinteraction: 1.2.0
 - cookbook: 0.8.4
 - dashboard: 7.1.0
 - dav: 1.17.1
 - deck: 1.4.2
 - documentserver_community: 0.1.9
 - drawio: 1.0.0
 - federatedfilesharing: 1.11.0
 - files: 1.16.0
 - files_external: 1.12.0
 - files_markdown: 2.3.3
 - files_mindmap: 0.0.24
 - files_pdfviewer: 2.1.0
 - files_rightclick: 1.0.0
 - files_sharing: 1.13.1
 - files_texteditor: 2.14.0
 - files_trashbin: 1.11.0
 - files_versions: 1.14.0
 - files_videoplayer: 1.10.0
 - firstrunwizard: 2.10.0
 - fulltextsearch: 21.0.1
 - geoblocker: 0.4.6
 - keeweb: 0.6.5
 - logreader: 2.6.0
 - lookup_server_connector: 1.9.0
 - maps: 0.1.8
 - music: 1.2.0
 - nextcloud_announcements: 1.10.0
 - notes: 4.0.4
 - notifications: 2.9.0
 - oauth2: 1.9.0
 - onlyoffice: 7.0.2
 - password_policy: 1.11.0
 - phonetrack: 0.6.7
 - photos: 1.3.0
 - polls: 1.8.3
 - privacy: 1.5.0
 - provisioning_api: 1.11.0
 - recommendations: 1.0.0
 - serverinfo: 1.11.0
 - settings: 1.3.0
 - sharebymail: 1.11.0
 - spreed: 11.2.1
 - support: 1.4.0
 - survey_client: 1.9.0
 - systemtags: 1.11.0
 - tasks: 0.13.6
 - text: 3.2.0
 - theming: 1.12.0
 - twofactor_backupcodes: 1.10.0
 - updatenotification: 1.11.0
 - user_status: 1.1.1
 - viewer: 1.5.0
 - weather: 1.7.5
 - weather_status: 1.1.0
 - workflowengine: 2.3.0
Disabled:
 - encryption
 - federation
 - user_ldap



</details>

<details><summary>Configuration (config/config.php)</summary>

{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "21.0.1.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "loglevel": 2,
    "logtimezone": "Europe\/Paris",
    "logfile": "\/var\/log\/nextcloud.log",
    "log_rotate_size": 0,
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "default_phone_region": "FR",
    "updater.release.channel": "stable",
    "mail_smtpauth": 1,
    "mail_sendmailmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mysql.utf8mb4": true,
    "trashbin_retention_obligation": "auto, 100",
    "has_rebuilt_cache": true,
    "app_install_overwrite": [
        "files_reader"
    ]
}


</details>

External storages: yes

<details><summary>External storage configuration</summary>

No mounts configured


</details>

Encryption: no

User-backends:

OC\User\Database

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:88.0) Gecko/20100101 Firefox/88.0

**Comment by sirdrakeistda** [comment]
Have you noticed, that your y-Scale is different in the two graphs? I think the last value is the only correct value. All other values were doubled after data update. So I think there is a bug where the new data is added on the old data.

**Comment by dgedgedge** [comment]
> Have you noticed, that your y-Scale is different in the two graphs? I think the last value is the only correct value. All other values were doubled after data update. So I think there is a bug where the new data is added on the old data.

Yes you are right. I did not notice.
Here is the configuration of the autmatic upload:
![Capture d’écran 2021-05-20 à 10 07 29](https://user-images.githubusercontent.com/17098018/118942705-42daed00-b953-11eb-8e2f-46528ab736f9.png)

I don't see where we could have this multiply by 2.
I didn't see any possibility to add old values to the stored ones in Analytics ?

**Comment by sirdrakeistda** [comment]
I have the same problem here. I tried also to switch the option to delete old data before update data on and off. It didn't made any difference. I update the data every hour, so my data is completely false (actual value is around 100 value in analytics is around 50000).

**Comment by dgedgedge** [comment]
Unsure of the documented behaviour.
Even when we update the value, it is not supposed to add the amount of the new value to the old one, does it ?

**Comment by dgedgedge** [comment]
> I have the same problem here. I tried also to switch the option to delete old data before update data on and off. It didn't made any difference. I update the data every hour, so my data is completely false (actual value is around 100 value in analytics is around 50000).

From what you said, it seems either 
that at each "update", the old value is added to the new value, 
and/or 
that the data is not reset, and each entry is added to the SQL table the graphic then doing a sum of the multiple instances at the same "date".

**Comment by sirdrakeistda** [comment]
> From what you said, it seems either
> that at each "update", the old value is added to the new value,
> and/or
> that the data is not reset, and each entry is added to the SQL table the graphic then doing a sum of the multiple instances at the same "date"
Thats exactly what I mean. I have a Dataset, which only contains actual values (no old values). For me it seems like if category and x value are the same the data is added and not updated or replaced.

**Comment by Rello** [comment]
hi,
let me check. I will connect the same datasource

**Comment by Rello** [comment]
I activated hourly updates now on my side. its really strange. the class can only update - not add values. lets see what we find out

**Comment by Rello** [comment]
Hello,
I can confirm that it is in fact adding up.
technically its not adding up - its adding records with same keys in this special combination even  so the whole data should have been deleted before.
I will debug and fix as soon as possible

**Comment by Rello** [comment]
I think I got it 🤦
the deletion is filtered on the "current user id" - which is not the same as the report owner during background jobs.
this explains, why the data is not removed and only added

**Comment by dgedgedge** [comment]
Fyi : 
I created a file in nextcloud with the following command : 
awk -v date=$(date +"%FT%T") '/^pswp/{print $1","date","$2 }' /proc/vmstat >> ........./nextcloud_vmstat.csv

Load each hour in nextcloud lead to the following graphic : 
![Capture d’écran 2021-05-21 à 20 21 00](https://user-images.githubusercontent.com/17098018/119187104-2fc23d00-ba79-11eb-8424-b6c78a7e780f.png)

After manual reload : 
![Capture d’écran 2021-05-21 à 20 23 43](https://user-images.githubusercontent.com/17098018/119187121-3650b480-ba79-11eb-9cba-d4d818244d32.png)

So I stopped the update of the file (The file did not changed during one hour) and after 1 hour it lead to : 
![Capture d’écran 2021-05-21 à 21 07 23](https://user-images.githubusercontent.com/17098018/119187220-5da78180-ba79-11eb-9806-7a213e210357.png)

So in this example, we see the effect of the load even if the file does not change from load to load.

Upload is done with : 
![Capture d’écran 2021-05-21 à 21 15 48](https://user-images.githubusercontent.com/17098018/119187549-c989ea00-ba79-11eb-98f0-81fb8546acce.png)

On the contrary similar graphics are behaving correctly....

**Comment by Rello** [comment]
its fixed.
I will run my automated tests and then release tomorrow

**Comment by Rello** [comment]
Hi,
can you please try again with the latest bugfix version?

**Comment by dgedgedge** [comment]
> Hi,
> can you please try again with the latest bugfix version?

I installed the 3.5.1 and the issue disapeared. On my last example of this issue.
Before the install there was a curve stairs  like.
After the automatic update, the curve is as expected....
We can consider that he issue is corrected.

Still I don't understand why the curve made the sum of the values even if with the same date...
Could you explain ?

**Comment by Rello** [comment]
Hello,

problem was, that when using background job (not the manual load), the old data was not deleted.
So a second, third ... record was added to the database every time. As the SELECT for reading the numbers us using SUM() GROUP BY, it was adding all records per date together.

And the nice stairs in the chart are also displayed by this. the current date only has one value; previous has 2; before that already 3 values being added up

very interesting combination. Lucky that its solved now. nothing any testcase would have found in this constellation.

**Comment by dgedgedge** [comment]
OK, it's in the code. I understand this. My question was more why is a sum in the code?

If I did correctly read the code it's written in ./lib/Db/StorageMapper.php
`125         $sql->addSelect($sql->func()->sum('value'));$`

I wonder why you do a sum here.
You could have done an avg / Average ?

If i did analyse the thing correctly, that means that in other situations we could also calculate the sum of values where the 'value' would be more meaningfull...

I don't see in the documentation where we introduce this sum.

**Comment by Rello** [comment]
Hi,
the reason for the sum is this part
https://github.com/Rello/analytics/blob/master/lib/Db/StorageMapper.php#L114-L122

when you change the filter or the drilldown (by removing a column e.g.) it needs to group/add up the values. This is much easier done directly on the DB than anywhere in php or in js.

but your remark more can lead into another direction: There might me cases where other aggregations might be interesting.

- Sum - grouping/cumulating like financials
- Avg - daily readings like IOT
- Last/Max - inventory numbers

would be something for the roadmap to have a selector in the report for this

**Comment by dgedgedge** [comment]
> Hi,
> the reason for the sum is this part
> https://github.com/Rello/analytics/blob/master/lib/Db/StorageMapper.php#L114-L122
> 
> when you change the filter or the drilldown (by removing a column e.g.) it needs to group/add up the values. This is much easier done directly on the DB than anywhere in php or in js.
> 
> but your remark more can lead into another direction: There might me cases where other aggregations might be interesting.
> 
>     * Sum - grouping/cumulating like financials
> 
>     * Avg - daily readings like IOT
> 
>     * Last/Max - inventory numbers
> 
> 
> would be something for the roadmap to have a selector in the report for this

On my last example, I was not with UTC. So I changed to UTC, thus leading to multiple measures to the same date and time leading to the following.

![Capture d’écran 2021-05-23 à 11 05 36](https://user-images.githubusercontent.com/17098018/119254543-25a65880-bbb7-11eb-899d-89b0a49af8ba.png)

I Agree that there may be a need for sum, average or Last/Max.
At a first step, reading the doc,  I thought naively that all values where printed, and/or in case of collision one of the values or the average was selected.
Looking back at the architecture diagram I would say that there is an extra layer, I would call "Treatement" where you compute from the raw data.
For short that computation is Sum, Avg, Lax, Max, ...

**Comment by Rello** [comment]
what does the data in the table look like?
multiple values for the exact same timestamp? 
what is the source data?

**Comment by dgedgedge** [comment]
> what does the data in the table look like?
> multiple values for the exact same timestamp?
> what is the source data?

Sadly I have removed the file. I am redoing the experiment. Results in 4 hours at least.

**Comment by dgedgedge** [comment]
> what does the data in the table look like?
> multiple values for the exact same timestamp?
> what is the source data?

Here is a new curve showing the potential issue: 
(The data is constant, and as you did imagine of the class of IOT measures).

![Capture d’écran 2021-05-23 à 16 43 36](https://user-images.githubusercontent.com/17098018/119265257-4f2aa880-bbe6-11eb-996a-19e202ec1fb9.png)

Generated by : 
`cat /root/swapmonitor.sh

#!/bin/bash

awk -v date=$(date +"%FT%T") '/^pswp/{print $1","date","$2 }' /proc/vmstat >> ......./nextcloud_vmstat.csv
awk -v date=$(date --utc +"%FT%T") '/^pswp/{print $1","date","$2 }' /proc/vmstat >> ....../nextcloud_vmstat.csv
`

File generated : 
[nextcloud_vmstat.csv](https://github.com/Rello/analytics/files/6528269/nextcloud_vmstat.csv)

**Comment by dgedgedge** [comment]
Note: My remarks are theorical to improve the tool. As it is it works perfectly for me.
Thanks a lot for this tooling.
