### ISSUE TITLE
Download chart as image

### ISSUE THREAD

**Issue by koulaxizis** [Rello/analytics#143]
Is there an option to export analysis as an image? Couldn't find it...

**Comment by Rello** [comment]
hello,
i just realized that there is an export feature in chart.js
https://www.chartjs.org/docs/latest/developers/api.html#tobase64image-type-quality

I will have a look

**Comment by Rello** [comment]
Hello,

I added this menu point to the new chart options menu.
it will trigger a download of the chart as png.

would this work for you?
![Bildschirmfoto 2021-04-28 um 20 37 00](https://user-images.githubusercontent.com/13385119/116455555-7dc09800-a861-11eb-8970-6aee2b806325.png)

**Comment by koulaxizis** [comment]
This looks great! Looking forward to test it. Thank you very much!
