### ISSUE TITLE
text variables in report header (e.g. %lastUpdate%)

### ISSUE THREAD

**Issue by Rello** [Rello/analytics#145]
- [x] new replace-function in datasetService

Variables:
- [x] %lastUpdateDate% (data added to the report)
- [x] %lastUpdateTime% (data added to the report)
- [x] %currentDate% (reload of the report)
- [x] %currentTime% (reload of the report)
- [x] %owner% = Report owner

Integration:
- [x] textvariables for header/subheader
- [x] hint popup

**Comment by Rello** [comment]
@dgedgedge you requested this also in #124. what do you think?

```
Numbers Today (%currentDate%)
Last Update: %lastUpdate%; Report owner: %owner%
```
<img width="367" alt="Bildschirmfoto 2021-07-07 um 00 20 01" src="https://user-images.githubusercontent.com/13385119/124673410-15251580-deb9-11eb-9535-2d507d1e1f26.png">

<img width="322" alt="Bildschirmfoto 2021-07-07 um 00 20 18" src="https://user-images.githubusercontent.com/13385119/124673434-1d7d5080-deb9-11eb-9ca8-e6f200e18b77.png">

**Comment by Rello** [comment]
<img width="819" alt="Bildschirmfoto 2021-07-08 um 00 08 29" src="https://user-images.githubusercontent.com/13385119/124834816-a3180380-df80-11eb-84ff-2d976bf6d3de.png">

**Comment by dgedgedge** [comment]
Seems great.
I look forward for the delivery.
