### ISSUE TITLE
Question: How to use multi-column tables with time (or x-axis) in first column and data in the others

### ISSUE THREAD

**Issue by fthommen** [Rello/analytics#147]
_apologies if that is not the right place to ask questions, but I couln't find an other one.  Feel free to redirect me if this is the wrong place._

Hi,

Is there a way to use datafiles which have the time in the first column and then one data (value) column per object? E.g. like
| date       | users | load | jobs |
|------------|-------|------|------|
| 2020-01-01 | 1200  | 15   | 120  |
| 2020-01-02 | 1000  | 10   | 261  | 
| 2020-01-03 | 1573  | 67   | 98   | 

this is the "normal" structure of most datafiles (of whatever format) we have and converting them all to something like

|key | data | value |
|------------|-------|------|
| users | 2020-01-01 | 1200  |
| users | 2020-01-02 | 1000  |
| users | 2020-01-03 | 1573  |
| load | 2020-01-01 | 15   |
| load | 2020-01-02 | 10   |
| load | 2020-01-03 | 67   |
| jobs | 2020-01-01 | 120  |
| jobs | 2020-01-02 | 261  | 
| jobs | 2020-01-03 | 98   | 

is quite tedious and error prone.  Also we would have to reconvert permanently, as data is by default recreated in the first format.

If this is not possible yet: Are there plans to implement this type of data structure?

**Comment by Rello** [comment]
Hi,
it would be possible - but not with realtime.
the realtime access (Report Type csv e.g.) to a file can only select one column combination.

If you would use the "internal database" and then use the dataload from the advanced options, you could load 3 different combinations.
I am not sure if this would be a feasible option to load the data?
![Bildschirmfoto 2021-05-04 um 14 21 40](https://user-images.githubusercontent.com/13385119/117002607-0f0d8f80-ace4-11eb-9f77-46d0924b63a0.png)

**Comment by fthommen** [comment]
>  it would be possible - but not with realtime.
> the realtime access (Report Type csv e.g.) to a file can only select one column combination.
> 
> If you would use the "internal database" and then use the dataload from the advanced options, you could load 3 different combinations.
> I am not sure if this would be a feasible option to load the data?

Hmm.  I probably don't quite understand the "internal database - dataload" thingy yet.  In the case of my example would I have to load the file three times with different titles and selected columns "1,2", 1,3" and "1,4" respectively?  But the timestamp would still be in the first of the imported columns (it does in fact, that table/graph is the wrong way round :-).  When using "2,1" for the users, I get three errors at data load.  See the screenshots

![Screenshot 2021-05-04 at 14 40 20](https://user-images.githubusercontent.com/279232/117004760-ba1f4880-ace6-11eb-8d19-6ab2f06d5a44.png)

![Screenshot 2021-05-04 at 14 40 06](https://user-images.githubusercontent.com/279232/117004750-b7bcee80-ace6-11eb-80c5-a55603fa4e9b.png)

`mydata.txt` is
```date,users,load,jobs
2020-01-01,1200,15,120
2020-01-02,1000,10,261
2020-01-03,1573,67,98
```

**Comment by Rello** [comment]
let me check. I think there may just be an issue with the date format. but this should be do-able.
I will get back

**Comment by fthommen** [comment]
I am (quite) flexible with the time format.  Are the allowed timestamp formats documented somewhere?

**Comment by Rello** [comment]
no. should be fine.
i am just checking something I found in my local data related to the new chart library. I think it might be the same topic

I will get back

**Comment by fthommen** [comment]
>  i tested and it looks good. in order to report all values in one chart, you need to create dataseries out of this.
> so you want to have one series for users, one for jobs, ...
> This is possible with a new feature that will be in the upcoming v3.5 - to add texts to column selections.
> [...]
>  then I expect this is your required report?

Yes, this is exactly the expected report :-).  I understand, that this will work only from the next version on?

I (also) have a more general and basic problem understanding the "Dataload"-page and its various entry fields and what I should fill in and also with the required file format.  Is there a place/forum/maillist to ask such questions?

**Comment by fthommen** [comment]
...one small thing, though: I would need the x-axis unit to be days, not time of day.  Do I need to configure this through the advanced chart options?

**Comment by Rello** [comment]
> ...one small thing, though: I would need the x-axis unit to be days, not time of day. Do I need to configure this through the advanced chart options?

Hello,
yes, this is correct
https://github.com/Rello/analytics/wiki/Advanced-chart-options

but I need to update the documentation first. it changed a little due to the chartjs v3 upgrade

**Comment by Rello** [comment]
{"scales": {"xAxes": {"time": {"unit" : "day"}}}}
