### ISSUE TITLE
handle db migration issues

### ISSUE THREAD

**Issue by patrizzle888** [Rello/analytics#148]
Hello,

I've been struggling to get Analytics to work. I am running Nextcloud  21.0.1 and have Analytics 3.4.1 installed.
When I click 'New Report' nothing happens and I find this error in the logs every time I click 'New Report':

**Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'value' in 'field list'**

![grafik](https://user-images.githubusercontent.com/11139511/117051276-a7bd0300-ad16-11eb-8f31-9cefb9bf63d4.png)

expanded view shows this:

![grafik](https://user-images.githubusercontent.com/11139511/117052220-c40d6f80-ad17-11eb-9746-7cb7f3c054ae.png)

![grafik](https://user-images.githubusercontent.com/11139511/117052332-e69f8880-ad17-11eb-8438-cf2ac8aead32.png)

![grafik](https://user-images.githubusercontent.com/11139511/117052543-25354300-ad18-11eb-88d0-bc07f952bf2a.png)

not being fluent in SQL I've run `occ maintenance:repair` and that did not resolve the issue. 
I would really appreciate some assistance with resolving this issue.

Thank you in advance,

Patrick

**Comment by Rello** [comment]
Hello,
there was an old issue related to NC21 but this was solved in February.
Could be that you did not use AP for some time?

https://github.com/Rello/analytics/issues/113

can you please try an
`occ migrations:status analytics`

**Comment by patrizzle888** [comment]
Thank you for getting back to me so fast! 

`occ migrations:status analytics` returns 

    >> App:                                                analytics
    >> Version Table Name:                                 oc_migrations
    >> Migrations Namespace:                               OCA\Analytics\Migration
    >> Migrations Directory:                               /config/www/nextcloud/apps/analytics/lib/Migration
    >> Previous Version:                                   030201Date20210129200000
    >> Current Version:                                    030400Date20210313200000
    >> Next Version:                                       Already at latest migration step
    >> Latest Version:                                     030400Date20210313200000
    >> Executed Migrations:                                10
    >> Executed Unavailable Migrations:                    10
    >> Available Migrations:                               10
    >> New Migrations:                                     10
    >> Pending Migrations:                                 None

and your are correct, I haven't used it in a while.

**Comment by Rello** [comment]
thats really strange.
can you let me know how you got there?
Fresh install/update of NC?
Fresh install/update of Analytics?

the migration in question was with
020500Date20200815180000

**Comment by patrizzle888** [comment]
i think i updated all the way up from NC 18.x in March (one major release after the other, using the console method). I'm not quite sure if I updated my apps before updating to the next major NC release during the NC update process or if I just updated everything when I got to NC 21.0.1. I tried uninstalling and reinstalling Analytics today after I noticed it wasn't working.

**Comment by Rello** [comment]
you don´t have database access, do you?

**Comment by patrizzle888** [comment]
i do have database access.

**Comment by Rello** [comment]
Hello,
after consulting back with the NC team, I really have no clue how you managed to get into this state. 
But we should not mess with the database migration files in this case as it can get complicated.
v 3.6 will be released shortly. in this version I will include a database migration, that will take care of this case and repair it.

so you need to wait for some more days, but its safer than messing with the SQL console

**Comment by patrizzle888** [comment]
Thank you very much and I'm looking forward to the update :)!
