### ISSUE TITLE
Report: yAxis start at 0

### ISSUE THREAD

**Issue by fthommen** [Rello/analytics#152]
The default settings of the column chart type seem to select the lowest y-axis value to be equal to the lowest occurring value, thus completely hiding this column.

Example: The following table
```
Name,Date,Inhabitants
city1,2020-01-01,13000
city1,2020-02-01,10000
city1,2020-03-01,14000
city2,2020-01-01,16000
city2,2020-02-01,17000
city2,2020-03-01,18000
```
results in the following column chart:
![image](https://user-images.githubusercontent.com/279232/117578729-01934380-b0f0-11eb-86e0-856fa263dbc3.png)

The middle value for city1 seems empty but isn't :-)

I suggest that the default settings/scaling should always make sure, that _all_ (existing) values are visible.  Intuitively I would suggest to start the y-axis at 0 (zero) or at least somewehat below the lowest existing value.

**Comment by Rello** [comment]
Hello,
I can confirm, that with the upcoming version (which has the upgrade to chatjs v3) this is not happening anymore.

![Bildschirmfoto 2021-05-09 um 22 05 22](https://user-images.githubusercontent.com/13385119/117585421-a888d700-b112-11eb-9692-dfb2579d8903.png)

**Comment by fthommen** [comment]
Looking forward to it :-).

**Comment by fthommen** [comment]
Updated the app just now and it work just fine out of the box.  Thanks a lot.
