### ISSUE TITLE
occ analytics:load doesn't delete data before load

### ISSUE THREAD

**Issue by fvidalmolina** [Rello/analytics#156]
I executed the command:
`php occ analytics:load 15`
to get the CSV loaded, and I receive this error:
`An unhandled exception has been thrown:
Error: Undefined class constant 'SUCCESS' in /var/www/html/apps/analytics/lib/Command/Load.php:49
Stack trace:
#0 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\Analytics\Command\Load->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Analytics\Command\Load), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/console.php(100): OC\Console\Application->run()
#6 /var/www/html/occ(11): require_once('/var/www/html/c...')
#7 {main}`

At the end the file is loaded, but I have configured  "Delete data before load --> yes" and this is not happening, so my report that is just a table with values, has as many duplicates as loads I do.

**Comment by Rello** [comment]
which NC version are you on?

**Comment by Rello** [comment]
Hello,
found it. it was fixed already with the upcoming 3.5. 
it should be ready within the next days
