### ISSUE TITLE
translations for Analytics v3.6

### ISSUE THREAD

**Issue by Rello** [Rello/analytics#158]
Hello,

@AleksovAnry
@simmstein

can you please check the fr and ru* language files?
- there are just 5 new rows in the ru json
- for fr, there are some more pending

thank you

**Comment by AleksovAnry** [comment]
Ок, i'm check it on this week

**Comment by AleksovAnry** [comment]
Hello! Translated new keys. Didn't find this::
`This section is used for advanced report and dataload configurations.
Please select a report from the navigation`

**Comment by Rello** [comment]
ah, nice find.
will prepare it for the next version. I need to quickly release this bugfix due to a db issue

**Comment by AleksovAnry** [comment]
Ок! Any help needed?

**Comment by Rello** [comment]
whish me luck. db issues are the worst

**Comment by Rello** [comment]
Hello,
an you please provide me with the strings for:

    "This section is used for advanced report and dataload configurations."
    "Please select a report"
