### ISSUE TITLE
threshold colors wrong in dashboard

### ISSUE THREAD

**Issue by sirdrakeistda** [Rello/analytics#159]
![Bildschirmfoto vom 2021-03-21 18-34-09](https://user-images.githubusercontent.com/35723909/118725315-14b0bc80-b830-11eb-9c5f-5177a1451049.png)
The colours treshold in the Dashboard and in the graph are not the same. I think the issue is because of different decimal notations (e.g. in some countrys the same value is written 12.142,00 and in some it is written 12,142.00). When I choose the treshold value >50 is red, then there are in the dashbaord only values red which are >50000. Issue persists in Analytics 3.5.0.

(I mentioned this with a bit more details here: https://github.com/Rello/analytics/issues/136)

**Comment by Rello** [comment]
Hi,
thank you for opening a separate issue here.
it got lost with the other one.
I will take care...

**Comment by Rello** [comment]
fixed.
I was converting the value to local String and then parsing through the comparison. wrong sequence...

**Comment by Rello** [comment]
let me know if it works the the latest 3.5.1 bugfix
