### ISSUE TITLE
occ command for executing dataloads

### ISSUE THREAD

**Issue by juliushaertl** [Rello/analytics#16]
It would be great if scheduled data loading could be configured to run more often than hourly, e.g. with a cronjob scheduled every 5 minutes.

**Comment by Rello** [comment]
Hallo Julius,

yes, I am planning to provide more flexibility here.
But this requests explains your need for #15 now :-)

**Comment by Rello** [comment]
Hello @juliushaertl 

currently i am registering a **hourly** and a **daily** execution to the cron backend.
potentially I could add 1/2 day or/and 15min execution. but this would add more jobs to cron.

The reason I go that route of registering separate jobs is that I can use the stock-framework which checks the last execution out of the box.
whenever one of the jobs is executed, I search which dataload applies to this d/h category.

to provide a fully flexible way would be to register only one job to every cron execution and develop my own time-checking implementation.

what is your view on this?

**Comment by juliushaertl** [comment]
A different idea would be to have some kind of manual trigger mode, where you could just setup your own cronjob that then calls something like `occ analytics:fetch` so you can make the runs independent from the nextcloud cron.

**Comment by Rello** [comment]
thats actually a nice idea. registering a command with a dataload-id as input parameter is pretty easy. I will look at it

**Comment by Rello** [comment]
`occ analytics:load 32`

**Comment by juliushaertl** [comment]
awesome :rocket:

**Comment by Rello** [comment]
v2.1.0 released
