### ISSUE TITLE
Legend is not totally visible

### ISSUE THREAD

**Issue by sirdrakeistda** [Rello/analytics#160]
![Bildschirmfoto vom 2021-05-18 23-59-31](https://user-images.githubusercontent.com/35723909/118728840-1d57c180-b835-11eb-9a86-327cd11ea2b1.png)
The legend is cut of (the legend includes all countries and is cut of after Mexico), but in the browser tab would be enough space to show the whole legend.

**Comment by Rello** [comment]
ok, thats a lot. I think there is a maximum space with the chart library itself. 
i will check

**Comment by sirdrakeistda** [comment]
In the past the legend was visible on a big screen. At the moment the space of graph and legend is constant so legend and graph share its space. Is it possible to make a dynamic space only for the legend? So if you open the legend the size of the graph is constant but under the graph it opens the legend? (at the moment: total size stays constant, graph gets smaller if legend gets bigger)

**Comment by Rello** [comment]
Hi,
it seems others have this issue also.
I don´t have any access to the legend as its part of the generated canvas of chartjs
will need to follow up
https://github.com/chartjs/Chart.js/issues/6545

**Comment by Rello** [comment]
Hello,
I am dependent on chart.js here and will have to close it for now.
