### ISSUE TITLE
0 values are no longer displayed in the diagram

### ISSUE THREAD

**Issue by Himra** [Rello/analytics#161]
Hello all,

thanks for the new API 3.0
But unfortunately since the update to 3.5.0 the values with 0 in the diagram are no longer displayed or ignored.
Subsequent values are shifted to the left as a result.
In the table they are displayed correctly.

greetings Himra

**Comment by Rello** [comment]
![Bildschirmfoto 2021-05-22 um 13 46 17](https://user-images.githubusercontent.com/13385119/119225441-161a0780-bb04-11eb-8df3-0db5b56ccd26.png)

Hello,
can you please give some more details?
if there is no sensitive content, you can also export the whole report (Basic Settings => Report => Export button) and provide the file

**Comment by Himra** [comment]
Hello Rello,

the lines containing values 0 are shortened see the line with arrow

![grafik](https://user-images.githubusercontent.com/15324567/120152778-3164d100-c1ee-11eb-8fdd-79ec1c5cefa9.png)

**Comment by Himra** [comment]
Hello Rello,

I found the error myself. It was the table, it was not 0 but NULL. I changed it and now it works again.

Probably something has changed in 3.5.1 compared to the previous version.

Thanks for the great project and sorry that I didn't think of it earlier.

Please close this issue.

Greetings Himra
