### ISSUE TITLE
Date format is incorrect

### ISSUE THREAD

**Issue by sibergad** [Rello/analytics#166]
I have two questions. How to specify the date format that I need and how to swap the first and second columns of the data output in the chart without making changes to the table?
![Без имени-1](https://user-images.githubusercontent.com/64952550/119234940-35835580-bb41-11eb-981f-f5c0a8082712.jpg)

**Comment by Rello** [comment]
ah, yes. thats the way excel stores dates.
are you using excel as realtime datasource, or are you loading?
...will search for my workaround...

**Comment by sibergad** [comment]
The Excel file is used in real time, the cell data type is set as General

**Comment by Rello** [comment]
Hello,
I just checked:

I am ussing full date in Excel: `18.04.2021`
within the report basic options, I set the "chart options" to the following to make chartjs understand the format (parser) and only display months as description (unit)
`{"scales": {"xAxes": {"time": {"parser" : "DD.MM.YYYY","unit" : "month"}}}}`

unfortunately the datatable is a little "dump". it will display everything, but not sort in a proper way

let me know
