### ISSUE TITLE
Enable receiver of share to unshare

### ISSUE THREAD

**Issue by dgedgedge** [Rello/analytics#171]
When you share a graphic, the person that receive the graphic has very limited options.
Things that seems to me important:
1- Be able to refuse the share (remove ones name from the share list).
2- Enable to move the graphic in a group.

**Comment by Rello** [comment]
Hi,
refusing share is a valid suggestion. will add it

Different Grouping is not possible with the current setup, as there can only be one group for a report. for share receivers, this is always empty. 
this would be a bigger rework but I have to focus the limited resources to more urgent topics for the moment

**Comment by Rello** [comment]
Hello,
i looked at the details. a share can be a user or a user group.
a share to the user can be removed (technically an entry in the table), but a share to the group can not be removed from one user for that group only.
I will check how NC treats this
