### ISSUE TITLE
Trend only for visible data series

### ISSUE THREAD

**Issue by sirdrakeistda** [Rello/analytics#172]
When Trend is activated it shows additional lines in the graph. In the legend of the graph there are additional elemets, which are clickable. When I click on an element (after activating "trend") some do not dis-/enable the element which I clicked, they de-/activate the element right to it.

Dataset:
https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv
columns: 3,4,42

steps to produce:
1.choose graph and activate trend
2. try to click on the new elements (e.g. 'Denmark Trend') in the legend
3. wait a few seconds (if you do it directly after opening the page there doesn't seem to be a bug)
-> not the element you clicked on is activated

edit: This bug seems to happen only on a special window size (tested with 1296* 1000 outer window and 1280* 910 inner window size checked with following website: https://www.rapidtables.com/web/tools/window-size.html)

[Further enhancement]:
Do not activate all trends in the graph. Activate only trend in the graph which are currently displayed.

**Comment by Rello** [comment]
Hi,
yes, current approach is that the trend is generated for all datasets of the chart.
if you you filter, it would work.

But I agree with your suggestion. it makes sense to only generate the trend for enabled datasets.
I also added a check to generate a trend only once for a dataset (when executing several times).
I also added a check to generate a trend not for a trend (when executing several times).
