### ISSUE TITLE
Time and date display in chart

### ISSUE THREAD

**Issue by Himra** [Rello/analytics#173]
Hello @Rello 
I am trying to set the date display in the chart and made several settings so far, but unfortunately none of the ones I entered in the chart options work.

`{"scales": {"xAxes": [{"time": {"format" : "X","unit" : "hour"}}]}}` from  #80

![grafik](https://user-images.githubusercontent.com/15324567/120291675-dac9c680-c2c3-11eb-826f-1f068e5e6489.png)

thanks and greetings
Himra

**Comment by Rello** [comment]
Hello,
with the latest chartjs migration, the syntax changed. I updated the wiki already
the [ ] were removed

`{"scales":{"xAxes":{"time":{"format" : "X", "unit" : "day"}}}}`
can you try this?

**Comment by Himra** [comment]
Hello Rello,

Thank you for your answer.
Unfortunately, the new spelling does not change anything, it is displayed as before

Greeting Himra

**Comment by Himra** [comment]
Hello @Rello,

I tried a few things again, but couldn't get it to work.

Now I have changed the date format to 2021-06-08 07:50 and added the following option:

`{"scales":{"xAxes":{"type":"time","time":{"format":"YYYY-MM-DD HH:mm","unit":"day","displayFormats":{"day":"DD. MMM"},"tooltipFormat":"HH:mm"}}}}`

Now it works

Thanks for the great project
Himra
