### ISSUE TITLE
Export data to NC file

### ISSUE THREAD

**Issue by dgedgedge** [Rello/analytics#174]
Hi,
When data is collected directly in Analytic, there is yet no "official" way to save the data.
It would be good to be able to have a way to save the data of the database in a .csv format for example, or XML, in order to apply other treatments, and/or to reload the data later.....
Thanks.

**Comment by Rello** [comment]
Hello,
did you try to export the report itself? it contains the definition + data and will download a txt file.
for exporting into a csv, the whole save-as-filepicker would need to be implemented.

**Comment by dgedgedge** [comment]
HI,
No I did not.
But now I have tried, and in it I did not get the data.
Note: My recording contains 4,013 entries....

**Comment by Rello** [comment]
thats strange. I tried several reports here.
they all get the data attached at the end.
anything in the logs?

`..."favorite":"","data":[["1000","1000","1000.00"]]}`

**Comment by dgedgedge** [comment]
> thats strange. I tried several reports here.
> they all get the data attached at the end.
> anything in the logs?
> 
> `..."favorite":"","data":[["1000","1000","1000.00"]]}`
> 
> https://github.com/Rello/analytics/blob/master/lib/Service/DatasetService.php#L310-L312

Nothing in the log.
