### ISSUE TITLE
sorting of external/unstructured data

### ISSUE THREAD

**Issue by dgedgedge** [Rello/analytics#175]
Hi,
I do have a csv file where I store the readings from 2 sensors.
In the file there is alternatively one measure then the next one.
The measure is determined through the first field as expected.

In the example file there is 2 sensor.
When loading the file through the database, Analytic prints correctly 2 curves.
When loading directly the file, it tries to print as many curve of one value as there is measure.....

It seems to me that the detection of new value in the  direct load is simply the change of value from the current 1st colum row and the previous one, without looking if the curve was already seen.... Something like that.

Analytics 3.5.1
Nextcloud 21.0.2
Debian Buster
Example file : 
[nextcloud_vmstat.csv](https://github.com/Rello/analytics/files/6596023/nextcloud_vmstat.csv)

**Comment by Rello** [comment]
Issue is solved with the next release.
the current behavior expected a sorted result-list, as it is coming from the internal database.
Coding was enhanced to find existing dataseries and not add new ones

**Comment by Rello** [comment]
![Bildschirmfoto 2021-06-13 um 00 11 46](https://user-images.githubusercontent.com/13385119/121790073-f2665080-cbdb-11eb-81a2-6c69ffb658c3.png)
