### ISSUE TITLE
The timeline does not show days when exten too more than one day.

### ISSUE THREAD

**Issue by dgedgedge** [Rello/analytics#176]
I have a graphic with plenty of data.
When I use colum 2 as date, when there is the basic setting showed, the timeline shows up consistently.
When I remove the basic settings menu, only hours are showed where it would be consistent to show dates...

See two exemple of graphics below from the same datasource. Sole difference is the fact to show the basic settings, which can't be done when sharing the graphic..

![Capture d’écran 2021-06-13 à 16 24 10](https://user-images.githubusercontent.com/17098018/121811298-4157c880-cc64-11eb-9c33-0eb4cc2b2b50.png)

![Capture d’écran 2021-06-13 à 16 20 10](https://user-images.githubusercontent.com/17098018/121811302-44eb4f80-cc64-11eb-9fc6-a047a81bf90a.png)

**Comment by Rello** [comment]
Hello,
the chart will automatically display the smallest unit when the place allows this.

for the moment, you could enter this in the "Chart options" input field in basic settings
`{"scales": {"xAxes": {"time": {"unit" : "day"}}}}`
its overwriting the display.

I plan to offer this as a normal option in the chart-options-ui.
But I need to see if I can do this for 3.6 already

**Comment by dgedgedge** [comment]
> Hello,
> the chart will automatically display the smallest unit when the place allows this.
> its not related to basic settings. on a different screen, it will look something else.
> 
> for the moment, you could enter this in the "Chart options" input field in basic settings
> `{"scales": {"xAxes": {"time": {"unit" : "day"}}}}`
> its overwriting the display.
> 
> I plan to offer this as a normal option in the chart-options-ui.
> But I need to see if I can do this for 3.6 already

Yes adding this to the chart option solves the issue.

**Comment by Rello** [comment]
👍🏻
