### ISSUE TITLE
Time options for graphics.

### ISSUE THREAD

**Issue by dgedgedge** [Rello/analytics#177]
Hi,
This is a feature suggestion.
I have graphics for temperature, created on the fly by sensor.
Looking at those graphics I realized that we miss some options to make zoom on parts of the graphic.

E.g.: Show data for data between Date 1 and Date 2, and/or Last xx data, and/or Last xx days/hours.
E.g.: Show only data for Y axis between value X1 and X2...

It's of no use if the data comes globaly from a CSV file because we may filter for hand by creating the csv file, 
but for IOT data directly collected in the database it seems to me an interesting option.

**Comment by Rello** [comment]
Hi,
will track it with this ticket
https://github.com/Rello/analytics/issues/186
