### ISSUE TITLE
dataset options not merged

### ISSUE THREAD

**Issue by lucentwolf** [Rello/analytics#178]
Hi Rello

just tried to customize dataset background colors, but the merge would only add new but not replace existing elements. Cause seems to be a swap in the cloner.deep.merge call:

app.js @ line 411:
reads: datasets = cloner.deep.merge(JSON.parse(userDatasetOptions), datasets);
should read: datasets = cloner.deep.merge(datasets, JSON.parse(userDatasetOptions));

**Comment by Rello** [comment]
sorry for the delay.
in progress now

**Comment by Rello** [comment]
Hi,
Thank you for the hint. 
for the chartOptions it is already that why. I can´t remember the specific reasons why I did it this way - but your remark makes sense to me.

tx
