### ISSUE TITLE
dataset options not merged on dashboard

### ISSUE THREAD

**Issue by lucentwolf** [Rello/analytics#179]
Dataset options are only merged when viewing a report in Analytics; however they're ignored in the Dashboard (e.g. bar colors); like in issue #178 due to wrong merge direction:

dashboard.js @ line 356
reads: datasets = cloner.deep.merge(JSON.parse(userDatasetOptions), datasets);
should read: datasets = cloner.deep.merge(datasets, JSON.parse(userDatasetOptions));

**Comment by Rello** [comment]
will check
