### ISSUE TITLE
How to access "advanced configuration"

### ISSUE THREAD

**Issue by Rello** [Rello/analytics#18]
Hi @Rello,  thank you for this app! I would like to use and contribute, but I have very little experience with nextcloud apps (yet). 

I need (and could help to create) user documentation for nextcloud beginners.

I want to use the "website grabber".

Chapter **Usage** in the [Wiki](https://github.com/Rello/analytics/wiki/Datasource:-website-grabber) says 

1. Report -> advanced config

Where do I find "advanced config"?

![image](https://user-images.githubusercontent.com/8489107/73127141-44dda780-3fbc-11ea-9e1f-3aac4abd2e3d.png)

Maybe I need to satisfy the condition "the datasource is only available in advanced config **with scheduling** due to the required parameters"?

How shall I enable scheduling?

_Originally posted by @markuskramerIgitt in https://github.com/Rello/analytics/issues/1#issuecomment-578442317_

**Comment by Rello** [comment]
@markuskramerIgitt

click the 3 "..." next to the report name. this gives basic and advanced config options

**Comment by markuskramerIgitt** [comment]
When I click the 3 "…," a pane opens to the right containing the 4 tabs "Report Thresholds Data Share" I can close the pane with thx "x" in the upper right corner or by clicking the three dots (the local menu) again.

The screen shot above shows the three dots, pane and the 4 tabs.

I do not find config options (basic or advanced) in any of the 4 tabs, scrolling up and below.

**Comment by Rello** [comment]
ah, ok.
please go to the app section of your nextcloud and update the app to the current release.
The feature was introduced with version 2.0

**Comment by markuskramerIgitt** [comment]
owncube.com offers only 1.2.2

![image](https://user-images.githubusercontent.com/8489107/73134988-8ebaa200-403d-11ea-82e5-d1ce388faa44.png)

Can I install 2.0 by myself, or can only owncube.com?

**Comment by Rello** [comment]
hello,
i don´t know about ownclube in that area. 2.0 has a dependency on NC 17 and NC 18

**Comment by markuskramerIgitt** [comment]
Owncube kindly bumped me to NextCloud 17 and Analytics 2.

I easily followed the instructions and I now track the bestseller number of "Wie der Tiger seine Streifen bekam"!

**Phantastic!**

Maybe one could improve the "website grabber" wiki?

- Add a comment like "Added in version 2" 
- Add screen shots of the 3 dots.
- Rename "HTML Regex" to  "HTML grabber" (as in the app)

It seems the fork of the git repo does not include the Wiki. How can I then contribute to the Wiki?

**Comment by Rello** [comment]
https://github.com/Rello/analytics/wiki/Advanced-configuration

thank you

**Comment by markuskramerIgitt** [comment]
Thank you!
