### ISSUE TITLE
Dashboard subheader

### ISSUE THREAD

**Issue by lucentwolf** [Rello/analytics#180]
Reports with multiple datasets will display only the last dataset label under the report title; which imho is somewhat irritating; I'd prefer to read the report's subheader instead;

My suggested change for dashboard.js @ line 103++:
function createWidgetContent 
+ let subheader = jsondata['options']['subheader'];
~ pass subheader as argument when calling buildWidgetRow
function buildWidgetRow
+ subheader parameter
~ replace ${kpi} by ${subheader}

**Comment by Rello** [comment]
Hi @lucentwolf ,

I can see your point - but there are different usecases.

the first chart matches your issue - several datasets but the first is shown.
chart 2 and 3 are the reason why I implemented it. It will take the last record (=last version) and show it, so I know which it is.
<img width="493" alt="Bildschirmfoto 2021-07-12 um 19 15 57" src="https://user-images.githubusercontent.com/13385119/125329283-97905800-e345-11eb-81e1-74eb3598b226.png">

I think the solution might be to check for the chart?

- if there is no chart (table = KPI = the last record counts), then the KPI title is displayed
- for charts, the subtitle is displayed

would this match your usecase also?

**Comment by Rello** [comment]
update: I tried it with my various report and this case actually makes sense.
Subtitle when Chart; KPI when Table;

<img width="653" alt="Bildschirmfoto 2021-07-12 um 19 34 54" src="https://user-images.githubusercontent.com/13385119/125331404-3e75f380-e348-11eb-8ae6-27130d936717.png">

this would also match the dashboard display
<img width="341" alt="Bildschirmfoto 2021-07-12 um 19 38 49" src="https://user-images.githubusercontent.com/13385119/125331834-cbb94800-e348-11eb-9c0f-32e446c28cc8.png">

what do you think?

**Comment by lucentwolf** [comment]
...absolutely makes sense, I like it!
