### ISSUE TITLE
automatic refresh of report

### ISSUE THREAD

**Issue by Himra** [Rello/analytics#182]
Hello Rello,

I have an idea for an advanced feature on the shared charts.
Is it possible to have the display update automatically at a predefined interval?
This would be interesting for the presentation of photovoltaics or even other data on a presentation display.

Maybe this is also interesting for others

Thanks for the great project

Greetings Himra

**Comment by Rello** [comment]
Hello,
good suggestion. I had this in mind already for the dashboard.
I am preparing this. the setting will be part of the report options.
what time frames would you expect?

<img width="187" alt="Bildschirmfoto 2021-07-12 um 21 18 37" src="https://user-images.githubusercontent.com/13385119/125343758-ba773800-e356-11eb-81cc-c31d02c65594.png">

<img width="118" alt="Bildschirmfoto 2021-07-12 um 21 18 52" src="https://user-images.githubusercontent.com/13385119/125343793-c400a000-e356-11eb-85a7-f60e098f2755.png">

**Comment by Himra** [comment]
The proposed time intervals are perfect
