### ISSUE TITLE
Data with only day/month

### ISSUE THREAD

**Issue by tobiasKaminsky** [Rello/analytics#184]
https://github.com/Rello/analytics/wiki/Advanced-chart-options#examples-from-user-questions

> Input data just has day/month like "12.03" and missing year
{"scales": {"xAxes": {"time": {"parser" : "DD.MM"}}}}

This worked pretty good so far, but after one update, I now see:
![image](https://user-images.githubusercontent.com/5836855/124935393-e5cfef00-e005-11eb-9f17-5473d8cedc32.png)

Data is like
2019 01.01 0
2019 02.01. 50
…
2020 01.01 0
2020 02.01. 50

**Comment by Rello** [comment]
I found the issue.
for the database, the date is just a string. and this is being sorted ASC as a string.
see below.
<img width="966" alt="Bildschirmfoto 2021-07-12 um 11 16 19" src="https://user-images.githubusercontent.com/13385119/125262577-97bb3400-e302-11eb-9f13-0b36b0a911f8.png">
and a timeline will connect the dots in this sequence
<img width="956" alt="Bildschirmfoto 2021-07-12 um 11 17 32" src="https://user-images.githubusercontent.com/13385119/125262795-c2a58800-e302-11eb-93bd-c6ed7eb49119.png">

you could use a normal line chart. but this will only work if the date values per year are exactly the same (no date may be missing in one or the other).

I need to think how this could be handled in the reporting. no idea yet

**Comment by tobiasKaminsky** [comment]
Thanks for your help!
If needed, I can also change syntax of my data.

**Comment by Rello** [comment]
Hi,
sorry for the delay. still testing on this...

**Comment by Rello** [comment]
found a solution.
if a dedicated parser is maintained for a report, the report will sort by this parser setting
will test a little...

```
let parser = JSON.parse(OCA.Analytics.currentReportData.options.chartoptions)["scales"]["xAxes"]["time"]["parser"];

test.sort(function (a, b) {   
    return a[0] - b[0] || moment(a[1],parser).toDate() - moment(b[1],parser).toDate();
});
```

**Comment by Rello** [comment]
![Bildschirmfoto 2021-11-11 um 19 40 57](https://user-images.githubusercontent.com/13385119/141351639-ee37f250-1c4b-41b2-9ae7-ddec4bd8f5c6.png)

- data is sorted according to parser (DD.MM)
- timeseries chart
- gapless

**Comment by Rello** [comment]
without parser:

![Bildschirmfoto 2021-11-11 um 19 53 38](https://user-images.githubusercontent.com/13385119/141353075-a8cd492f-2f3e-4cce-9311-314b8859a1c9.png)

**Comment by tobiasKaminsky** [comment]
> sorry for the delay. still testing on this...

No need to be sorry! I am glad that you work on it and found a solution!

**Comment by tobiasKaminsky** [comment]
I cloned master of this repo, added my cvs file  and added
` {"scales": {"xAxes": {"time": {"parser" : "DD.MM"}}}} `
to chart and data options:
![image](https://user-images.githubusercontent.com/5836855/141609171-c06f4e24-7ea5-4043-89bc-039dec3d6ce2.png)


It now looks like this on master:
![image](https://user-images.githubusercontent.com/5836855/141609184-bba30bce-29aa-456b-b821-6a20b2b2f9ef.png)

And on latest stable:
![image](https://user-images.githubusercontent.com/5836855/141609192-4c52b198-f085-4d1d-993c-e6330d78d022.png)


Data set is here, read-only until 30.11.: 
https://nextcloud.kaminsky.me/s/2gpqap3d6WejsNx

Thank you for your amazing work!

**Comment by Rello** [comment]
Hi,
cloning the repo is a little risky. there is some major rework currently.
this means that you now migrated your report structure already to the new setup. means you can not go back to stable.
...but it should be ok. its final fixing so should be good to go...

I cant download the csv. does not work

**Comment by tobiasKaminsky** [comment]
It is only my local test setup, so no worries 😁

Download should work, it is a public link.
Or do you have problems to download as text editor is directly shown?

**Comment by Rello** [comment]
Does it work for you with the report now?

I see this result after importing your data
![Bildschirmfoto 2021-11-13 um 22 58 56](https://user-images.githubusercontent.com/13385119/141660180-9f8056e7-19e4-4241-8425-b1f6b412ca8e.png)

**Comment by Rello** [comment]
@tobiasKaminsky the dev for the next version is coming close to its end.
some more changes ware pushed.
did you have any issues when using the current status of the app?

**Comment by tobiasKaminsky** [comment]
After latest "git pull" it looks awesome!
Thanks for making this work again!

Ps: If you are on next conference (whenever this will be), I will buy you a beer (or similar) 🎉
