### ISSUE TITLE
DatasetService removes first favorite

### ISSUE THREAD

**Issue by jhaan1979** [Rello/analytics#185]
In the function `getOwnFavoriteDatasets` on line 148 if the first element in either `$ownDatasets` or `$sharedDatasets` is a match, its index is returned as `0` and evaluates to falsy, meaning that element gets deleted from your favorites in the following code.
Reproduce it by creating one report, marking it favorite, and either reloading the reports page or loading the dashboard with the analitics widget enabled.

I've done a quick fix locally by using:
```
        foreach ($favorits as $favorite) {
            if (gettype(array_search($favorite, array_column($ownDatasets, 'id'))) != integer
                && gettype(array_search($favorite, array_column($sharedDatasets, 'id'))) != integer) {
                unset($favorits[$favorite]);
                $this->tagManager->load('analytics')->removeFromFavorites($favorite);
            }
        }
```

Not sure if this would qualify as a fix, but nevertheless, the bug is still there.

**Comment by Rello** [comment]
Hi,

thank you for that finding. took me a while to reproduce it because its pretty special.
the first report (sorted by groupfolder + alphabetically) needs to be a fav for this to occur.

will fix it.
thank you!
