### ISSUE TITLE
Dynamic text variables for filter

### ISSUE THREAD

**Issue by lordleicester** [Rello/analytics#186]
I am using Analytics to track the energy output of my PV modules each minute (*).
Every morning i have to set my filter to the new date (today) and safe the view.
Else the overview can be quite overwelming and take some time to load. 

I would consider it a big improvement, if i could set the filter to either:
- Show last n datapoints
- Show today (dynamic)
- Show last week/month/year (dynamic)
- Show last n minutes/hours/days (dynamic)

![image](https://user-images.githubusercontent.com/88026033/127118053-71ede3a9-de72-44c5-9f9d-8d9b47811f98.png)

------
(*) Using JSON-Data-Load (Analytics), Shelly 2.5 (Energy Meter), Synology Planned Task to trigger occ analytics:load

**Comment by Rello** [comment]
Hi,
that is defiantly a todo. perhaps I manage to include this in the next release.
there were preparations already for this in the database schema.
the current release also prepared the topic of text-variables
...

**Comment by lordleicester** [comment]
Hey,
thank you! I really appreciate it!
And regardless of the outcome: Thank you for all the work you have put in this awsome plugin already! 
I wish being capable of creating somthing as awsome as this =)
Keep it up!

**Comment by Rello** [comment]
Text filters can be used in the filter dialog. An optional formatting can be added with () in case the time column does have a different format.
![Bildschirmfoto 2022-02-22 um 23 00 02](https://user-images.githubusercontent.com/13385119/155226688-667cee60-141c-4cd8-bd86-0f7a441b7f80.png)

The filter is indicated in the report as "clean" output
![Bildschirmfoto 2022-02-22 um 23 05 25](https://user-images.githubusercontent.com/13385119/155227410-be4b3ebc-c377-43bb-9903-d78077ccf8b4.png)

All available filters can be found in the [wiki](https://github.com/Rello/analytics/wiki/Filter,-chart-options-&-drilldown#filter)
