### ISSUE TITLE
Add a WIzard to help people setup the data

### ISSUE THREAD

**Issue by Mannshoch** [Rello/analytics#188]
I'm not a Dataexpert but I e.g. even I wish to show som JSON data. What do I have to do?

Example wizard flow:

1. Enter the Datasource e.g. 
  [Swiss Parties since 1971](https://www.pxweb.bfs.admin.ch/api/v1/de/px-x-1702020000_104/px-x-1702020000_104.px)
  [Swiss Votings since 1982](https://ckan.opendata.swiss/api/3/action/package_show?id=nationalratswahlen-parteistimmen-und-parteistarke-seit-1971-bezirke-und-gemeinden)
2. Analytics lodad data and analyse 
3. Show data in a way and request People to e.g. select example values so Analytic could take the selected example 
4. With the selected example data create diagram
5. User select the diagram that fit best for his approach
6. Finish with entering missing data like Name and others

**Comment by Rello** [comment]
Hello @Mannshoch 
the next Release will add a new report/dataset wizard.
**"New report" & "New Dataset" Wizard #197**

Then you mentioned an additional point which is a wizard for external data with something like preview.
This is also a todo already - bot not for this release anymore.
**Preview and data picker for external datasources #101**

I will track the changes in the other issue and mention you there

**Comment by Mannshoch** [comment]
Thanks for the Update:
I have a little request about using your tool.
I looked into the Gov website I mentioned above and tried to get how to insert the data connection into Analytics. One way would be the CSV but the dynamic way will be a JSON request. From the Tutorial of the Gov website I found this advice:

Use this URL
`https://www.pxweb.bfs.admin.ch/api/v1/de/px-x-1702020000_105/px-x-1702020000_105.px`

And send this request to get the data:

```
{
  "query": [
    {
      "code": "Bezirk (>>) / Gemeinde (......)",
      "selection": {
        "filter": "item",
        "values": [
          "0001"
        ]
      }
    },
    {
      "code": "Ergebnisse",
      "selection": {
        "filter": "item",
        "values": [
          "1"
        ]
      }
    }
  ],
  "response": {
    "format": "json-stat"
  }
}
```
How do I have to put it into Analytics?
