### ISSUE TITLE
Chart axis assignment not working

### ISSUE THREAD

**Issue by fellowbx** [Rello/analytics#189]
<img width="969" alt="スクリーンショット 2021-08-22 16 41 15" src="https://user-images.githubusercontent.com/89334692/130346753-d9d28639-30a2-4710-b2cd-a595a5d2b8a0.png">

NextCloud Analytics

Set a new report. But don't working "Chart options" function.

3.5.1 is well, but 3.6.0 is no good.

I set Temperature's "Vertical axis" to secondary  in "Chart options". Then Vertical axis changed value 0 to 1. In 3.5.1, The value had been  optimized in automaticaly.

**Comment by Rello** [comment]
Hello,
took a while to take care. sorry.
is fixed for the next release
