### ISSUE TITLE
Navigation layout issue

### ISSUE THREAD

**Issue by Rello** [Rello/analytics#190]
@AleksovAnry @ sibergad

are you currently using Analytics?
I started 2 clean test instances for NC21/NC22 and the display looks strange to me:
![Bildschirmfoto 2021-08-30 um 19 39 13](https://user-images.githubusercontent.com/13385119/131381277-30aec2fc-3c7c-4c8b-ab0f-7e4f5a240582.png)

ok for you?

**Comment by AleksovAnry** [comment]
Yes, i see this issue. NC 22.1.1 
Looks like a missing text-indent. Fix this, or u know what's happening?

+Little localisation issues )

**Comment by Rello** [comment]
I know how to fix it.
I think I will move away from using NC standard css and keep copies in my own css file.
NC suddenly changing something is anoying
