### ISSUE TITLE
Ads a 0 in front of 2 digit month

### ISSUE THREAD

**Issue by hirehamva** [Rello/analytics#191]
Data is collected with JSON from a thermometer. Today changed to: 2021-010-01 12:20:13

![kép](https://user-images.githubusercontent.com/66569812/135628518-dfe7250c-c736-4a2e-8ef5-f93e76a12c9a.png)

**Comment by Rello** [comment]
can you post an example of a record in your json format for testing?

**Comment by hirehamva** [comment]
Not in front of computer, but I'm tring my best on the mobile.
  
Object path:   StatusSNS/AM2301/Temperature
  

  
Time comes from timestamp.
  

  
JSON:
  

  
 {"StatusSNS":{"Time":"2021-10-01T19:25:24","AM2301":{"Temperature":16.8,"Humidity":62.4,"DewPoint":9.6},"TempUnit":"C"}}
    

  

  
  
  
  
  
>

**Comment by tobiscode** [comment]
Same problem when the data is POSTed through Python & the API. It also affects the hover tooltip displayed date:

![screenshot](https://user-images.githubusercontent.com/47008700/135776961-5b4300c5-55f3-42a2-bde6-1c9ccfd2dcc7.png)

Thanks for looking into this!

**Comment by Rello** [comment]
Hello,
sorry for the delay. I was held up with a major enhancement of the Analytics app.
The error war pretty simple in JS frontend (the backend data is all fine)

now.getMonth() was not doing what expected. Its not getting the month (Oct=10) but the month-index (Jan=0)....

@dgedgedge
