### ISSUE TITLE
Report shared by link no chart is displayed

### ISSUE THREAD

**Issue by hirehamva** [Rello/analytics#192]
[https://sharelink.hu/index.php/apps/analytics/p/WK276he7bRwsw65](url)
![kép](https://user-images.githubusercontent.com/66569812/135629705-334a804e-9f0f-47ec-bb48-d7167b8cdac9.png)

**Comment by Rello** [comment]
![Bildschirmfoto 2021-10-01 um 15 48 52](https://user-images.githubusercontent.com/13385119/135631112-78537b7d-6736-4ff1-8694-ccdc933bf617.png)
I am seeing an error in Javascript.
I will have a look

thank you
