### ISSUE TITLE
Enable Activity Integration

### ISSUE THREAD

**Issue by Rello** [Rello/analytics#2]
Activity settings for Reports and Report Data

 ![Screenshot 2019-11-16 at 21 41 52](https://user-images.githubusercontent.com/13385119/68998991-02ac3180-08ba-11ea-9bc7-7d6406e94bf9.png)

Activities for various events

![Screenshot 2019-11-16 at 21 56 33](https://user-images.githubusercontent.com/13385119/68999104-0771e500-08bc-11ea-98e8-3b7170814f5a.png)

Activity filter

![Screenshot 2019-11-16 at 21 57 28](https://user-images.githubusercontent.com/13385119/68999108-19ec1e80-08bc-11ea-9206-6fadaa902677.png)

Subjects:

```
const SUBJECT_DATASET_ADD = 'dataset_add';
const SUBJECT_DATASET_DELETE = 'dataset_delete';
const SUBJECT_DATASET_SHARE = 'dataset_share';
const SUBJECT_DATA_ADD = 'data_add';
const SUBJECT_DATA_ADD_API = 'data_add_api';
```

**Comment by Rello** [comment]
@juliushaertl
I integrated Activity into my new app. works quite well - your Deck helped here as a reference
I have one issue, where I can't proceed. I hope you have a suggestion

within `OCA\Analytics\Activity\ActivityManager` i am referring to a service, because I need to read a name-tag from the dataset.
`use OCA\Analytics\Service\DatasetService;`
works until here

but within DatasetService I want to trigger activities. As soon as I include the ActivityManager within the same service as mentioned before, PHP stalls.
`use OCA\Analytics\Activity\ActivityManager;`

I assume that I can't do it in both ways because I am creating a cycle? is this correct?

**Comment by juliushaertl** [comment]
Yes, you have introduced a cyclic dependency between ActivityManager and DatasetService. Without having a deeper look at the code, it's hard to give a quick solution, but you could extract the reading in a separate class (as i assume that reading doesn't need the ActivityManager as a dependency). Otherwise try to move the "read a name tag" out of your activityManager and make sure that the data is passed into the method itself.

**Comment by Rello** [comment]
I solved it by accessing the DbController and not the DatasetService. not 100% nice but still clearer from the reading

thank you
