### ISSUE TITLE
Analytics Testing

### ISSUE THREAD

**Issue by Rello** [Rello/analytics#200]
Hello @dgedgedge
you recently opened several tickets for Analytics.
I did a quite big enhancement to AP.

- new report wizard
- multiple reports on 1 dataset 
- ...

I am searching for some pre-testers on my test instance to get some external feedback.
would you like to support me here?

**Comment by Rello** [comment]
@sibergad 
@AleksovAnry

**Comment by dgedgedge** [comment]
> Hello @dgedgedge you recently opened several tickets for Analytics. I did a quite big enhancement to AP.
> 
>     * new report wizard
> 
>     * multiple reports on 1 dataset
> 
>     * ...
> 
> 
> I am searching for some pre-testers on my test instance to get some external feedback. would you like to support me here?

I only have an production instance of nextcloud yet.
I don't realy know how to include a prerelease of such a feature....
I don't know if it's compatible with the stable stream.

If you had some hint I could try.
Regards.

**Comment by Rello** [comment]
Hello,
Dont beta test in your instance ;-)
I will provide an account on **my** test instance

**Comment by dgedgedge** [comment]
> Hello, Dont beta test in your instance ;-) I will provide an account on **my** test instance

We can try yes.
