### ISSUE TITLE
Translations for new Analytics release

### ISSUE THREAD

**Issue by Rello** [Rello/analytics#201]
Please support your translations for the upcoming Analytics version.

This time, there are some pretty long texts as a New-Report-Wizard was created

- [x] @simmstein fr
- [x] @hirehamva hu
- [ ] @sibergad @AleksovAnry ru

thank you

**Comment by hirehamva** [comment]
[hun.zip](https://github.com/Rello/analytics/files/7526097/hun.zip)
Translation done.

**Comment by simmstein** [comment]
https://github.com/Rello/analytics/pull/204

**Comment by Rello** [comment]
I will switch to Transifex after this release for easier maintenance.
I will try to migrate the existing files

**Comment by AleksovAnry** [comment]
Completed. Sorry for the long reply, I was on little sick leave)

**Comment by hirehamva** [comment]
![Screenshot_20211116-221718](https://user-images.githubusercontent.com/66569812/142067286-67b2441e-11a3-4a80-b122-eede27987add.png)
Not everything appears translated. I did something wrong, or is a bug?

**Comment by Rello** [comment]
Let me check

**Comment by hirehamva** [comment]
Nice job on 4.0.1, but the translation issue above is stil there.

**Comment by hirehamva** [comment]
Sorry I missed a coma, now the translation works fine.

**Comment by Rello** [comment]
hello @hirehamva 
I am in the progress to switch the translations to Transifex. do you know this/use this/have a user there?
https://www.transifex.com/nextcloud/nextcloud/nextcloud-analytics/

its much easier to have many people work on the correct translations

**Comment by hirehamva** [comment]
Ok. No problem, I made an account.
