### ISSUE TITLE
l10n: Correct text strings

### ISSUE THREAD

**Issue by Valdnet** [Rello/analytics#203]
- In the following text strings, extract the spaces that appear before or after the words:

`' records inserted, '` -> `'records inserted,'`
`' records updated, '` -> `'records updated,'`
`' errors'` -> `'errors'`
`'Records to be deleted: '` -> `'Records to be deleted:'`
`' has added new data to dataset {report}'` -> `'has added new data to dataset {report}'`
`' has importet data in dataset {report}'` -> `'has importet data in dataset {report}'`

This will eliminate translation errors in Transifex.

- Remove spaces:

`'extract / store / visualize'` -> `'extract/store/visualize'`

- Remove the exclamation mark in front of the sentence:

`'! This dataset is not used !'` -> `'This dataset is not used!'`

One exclamation mark at the end of the sentence is enough.

- Change to a capital letter:

`'first'` -> `'First'`
`'previous'` -> `'Previous'`
`'next'` -> `'Next'`
`'last'` -> `'Last'`
`'advanced'` -> `'Advanced'`
`'none'` -> `'None'`

- Change the three dots to ellipsis:

`'More Information ...'` -> `'More Information …'`

- Separate the ellipsis with a space:

`'More information…'` -> `'More information …'`

- Change to lowercase:

`'Timeline (Date in column 2)'` -> `'Timeline (date in column 2)'`

**Comment by Rello** [comment]
Hi,
thank you!
the project was just activated in TX today.
will fix them before the next index run

thank you!

**Comment by rakekniven** [comment]
Hello @Valdnet ,

this time the developer is looking at the issues directly reported at Transifex.
If you like we can stay there.
About 20 issues have been reported already.

**Comment by Valdnet** [comment]
@rakekniven Well 👍.

It's great that the developer is active in Transifex 😁.

**Comment by Rello** [comment]
@Valdnet 

`'extract / store / visualize' -> 'extract/store/visualize'`
this is a headline in the appstore. has to remain for marketing reasons

others are also commented or corrected. thank you!
