### ISSUE TITLE
php7.3 incompatibility

### ISSUE THREAD

**Issue by dgedgedge** [Rello/analytics#209]
I have upgraded to Analytics 4.0.0.
Graphics are still present, but when I try to update/modify the information of upload information of data set, I end up to a never handling wait.

![Capture d’écran 2021-11-16 à 18 34 42](https://user-images.githubusercontent.com/17098018/142036459-92cddff8-472c-4c32-a948-e6f88b6a7d3c.png)

This happens also with New dataset.

**Comment by Rello** [comment]
Hi
Can you please check the browser console and nextcloud.log for details?

**Comment by Rello** [comment]
I am trying different setups but could not reproduce it yet...

**Comment by dgedgedge** [comment]
> Hi Can you please check the browser console and nextcloud.log for details?

At the moment when I click to see the data oad tab I get an error : 



Error | index | ParseError: syntax error, unexpected 'LoggerInterface' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)/var/www/nextcloud/lib/composer/composer/ClassLoader.php - line 346: Composer\Autoload\includeFile("/var/www/ne ... p")<<closure>>Composer\Autoload\ClassLoader->loadClass("OCA\\Analyt ... r")<<closure>>spl_autoload_call("OCA\\Analyt ... r")/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 112: ReflectionClass->__construct("OCA\\Analyt ... r")/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 131: OC\AppFramework\Utility\SimpleContainer->resolve("OCA\\Analyt ... r")/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 460: OC\AppFramework\Utility\SimpleContainer->query("OCA\\Analyt ... r")/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 432: OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("OCA\\Analyt ... r")/var/www/nextcloud/lib/private/AppFramework/App.php - line 143: OC\AppFramework\DependencyInjection\DIContainer->query("OCA\\Analyt ... r")/var/www/nextcloud/lib/private/Route/Router.php - line 302: OC\AppFramework\App::main("OCA\\Analyt ... r", "read", OC\AppFramew ... {}, { _route: "a ... "})/var/www/nextcloud/lib/base.php - line 1006: OC\Route\Router->match("/apps/analytics/dataload")/var/www/nextcloud/index.php - line 36: OC::handleRequest()
-- | -- | --

**Comment by Rello** [comment]
Hi,
this is strange. which php version?

do you have access to the backend?
The issue seems to be coming from here
https://github.com/Rello/analytics/blob/master/lib/Controller/DataloadController.php#L25-L26

my idea would be to edit the lines and change from
```
    private LoggerInterface $logger;
    private DataloadService $DataloadService;
```
to
```
    private $logger;
    private $DataloadService;
```

**Comment by dgedgedge** [comment]
Server configuration detail

Operating system: Linux 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64

Webserver: Apache (apache2handler)

Database: mysql 10.3.31

PHP version: 7.3.31-1~deb10u1

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, exif, msgpack, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, memcached, Zend OPcache

Nextcloud version: 22.2.3 - 22.2.3.0

Updated from an older Nextcloud/ownCloud or fresh install:

Where did you install Nextcloud from: unknown

<details><summary>Signing status</summary>

Array ( )

</details>

<details><summary>List of activated apps</summary>

Enabled:
 - accessibility: 1.8.0
 - activity: 2.15.0
 - admin_audit: 1.12.0
 - analytics: 4.0.0
 - announcementcenter: 6.1.1
 - bruteforcesettings: 2.2.0
 - calendar: 2.3.4
 - carnet: 0.24.2
 - checksum: 1.1.2
 - circles: 22.1.1
 - cloud_federation_api: 1.5.0
 - collectives: 0.15.22
 - comments: 1.12.0
 - contacts: 4.0.6
 - contactsinteraction: 1.3.0
 - cookbook: 0.9.6
 - dashboard: 7.2.0
 - dav: 1.19.0
 - deck: 1.5.5
 - documentserver_community: 0.1.11
 - drawio: 1.0.1
 - federatedfilesharing: 1.12.0
 - files: 1.17.0
 - files_external: 1.13.0
 - files_markdown: 2.3.4
 - files_mindmap: 0.0.25
 - files_pdfviewer: 2.3.1
 - files_rightclick: 1.1.0
 - files_sharing: 1.14.0
 - files_trashbin: 1.12.0
 - files_versions: 1.15.0
 - files_videoplayer: 1.11.0
 - firstrunwizard: 2.11.0
 - geoblocker: 0.5.1
 - keeweb: 0.6.6
 - logreader: 2.7.0
 - lookup_server_connector: 1.10.0
 - mail: 1.10.5
 - maps: 0.1.9
 - music: 1.4.1
 - nextcloud_announcements: 1.11.0
 - notes: 4.2.0
 - notifications: 2.10.1
 - oauth2: 1.10.0
 - onlyoffice: 7.2.0
 - password_policy: 1.12.0
 - photos: 1.4.0
 - privacy: 1.6.0
 - provisioning_api: 1.12.0
 - recommendations: 1.1.0
 - serverinfo: 1.12.0
 - settings: 1.4.0
 - sharebymail: 1.12.0
 - spreed: 12.1.2
 - support: 1.5.0
 - survey_client: 1.10.0
 - systemtags: 1.12.0
 - tasks: 0.14.2
 - text: 3.3.0
 - theming: 1.13.0
 - twofactor_backupcodes: 1.11.0
 - updatenotification: 1.12.0
 - user_status: 1.2.0
 - viewer: 1.6.0
 - weather_status: 1.2.0
 - workflowengine: 2.4.0
Disabled:
 - encryption
 - federation
 - files_texteditor
 - user_ldap



</details>

<details><summary>Configuration (config/config.php)</summary>

{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
xxx
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/xxx",
    "dbtype": "mysql",
    "version": "22.2.3.0",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "loglevel": 2,
    "logtimezone": "Europe\/Paris",
    "logfile": "\/var\/log\/nextcloud.log",
    "log_rotate_size": 0,
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "share_folder": "\/SharedWithMe",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "default_phone_region": "FR",
    "updater.release.channel": "stable",
    "mail_smtpauth": 1,
    "mail_sendmailmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mysql.utf8mb4": true,
    "trashbin_retention_obligation": "auto, 100",
    "has_rebuilt_cache": true,
    "app_install_overwrite": [
        "files_reader"
    ],
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}


</details>

External storages: yes

<details><summary>External storage configuration</summary>

No mounts configured


</details>

Encryption: no

User-backends:

OC\User\Database

Talk configuration:

STUN servers

owncloud.fager.fr:3478

TURN servers

turn:owncloud.fager.fr:3478 - udp,tcp

Signaling servers (mode: internal):

no custom server configured

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:94.0) Gecko/20100101 Firefox/94.0

**Comment by dgedgedge** [comment]
> Hi, this is strange. which php version?
> 
> do you have access to the backend? The issue seems to be coming from here https://github.com/Rello/analytics/blob/master/lib/Controller/DataloadController.php#L25-L26
> 
> my idea would be to edit the lines and change from
> 
> ```
>     private LoggerInterface $logger;
>     private DataloadService $DataloadService;
> ```
> 
> to
> 
> ```
>     private $logger;
>     private $DataloadService;
> ```

Yes it corrects the issue.

**Comment by Rello** [comment]
ok, seems to be a php 7.3 thing.
I will remove it and push an update soon.
thank you for testing
