### ISSUE TITLE
Datasource: JSON

### ISSUE THREAD

**Issue by Rello** [Rello/analytics#21]
Provide a datasource to read json data by a given array-string

Input Parameter:
- URL of json
- Authentification
- json path
- timestamp t/f

Use Case / Example:
Monitor the Nextcloud instance via its internal API
- URL: http://server/nextcloud/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
- Auth: user:token
- Path: ocs/data/nextcloud/storage
- timestamp t/f

Example Output:
![Screenshot 2020-02-04 at 21 30 39](https://user-images.githubusercontent.com/13385119/73784357-998bda00-4795-11ea-8680-7ab337cc5b61.png)

**Comment by Rello** [comment]
https://github.com/Rello/analytics/wiki/Datasource:-JSON

**Comment by GH2204** [comment]
Nice function!!  I tried your Example 2 and it works fine.
Then i tried my own JSON - data-collector with API-Methode 2 at https://creativecommons.tankerkoenig.de/  (there is a demo-link within a demo-key) and it does not work. Where is the different?
I'd cut the JSON-request to one requested id: https://creativecommons.tankerkoenig.de/json/prices.php?ids=4429a7d9-fb2d-4c29-8cfe-2ca90323f9f8&apikey=[API-DEMO-KEY seen at https://creativecommons.tankerkoenig.de/] and in a browser it works.
used object-path: prices/4429a7d9-fb2d-4c29-8cfe-2ca90323f9f8/e5

Is there a problem with these URL-parameters ("ids", "apikey") or parsing the JSON-string?

**Comment by Rello** [comment]
Hello,
there is an issue with de-/coding an & sign during the dataload. I will take care...
