### ISSUE TITLE
CSV import error, forces numbers on Punycodes

### ISSUE THREAD

**Issue by thepra** [Rello/analytics#22]
Here's the datasource as a csv:
https://tld-list.com/df/tld-list-details.csv

At import time it throws an error about a number at the 3rd column which is the column of the punycode, something like this: xn--80akhbyknj4f
Which triggers wrongly the parsing I guess because the import believes it's a number when it's just an alfanumeric string with dashes(-)

For now I will delete that column and hope in a successful import, nice job overall 😉

**Comment by thepra** [comment]
Ok, I was wrong on the last point, event after the deletion the 3rd column is in error but this time there are no numbers in there(except empty fields) 😌

**Comment by Rello** [comment]
Hello,
in general, there is still a todo to enhance the datamodel for more dimensions and more flexibility. currently everything is framed around a value + 2 dimensions. 

but regarding to your data: I don´t see any keyfigure. what are you trying to report/visualise here?

**Comment by thepra** [comment]
For each "Sponsor"(category, size on 1 unit) see the TLDs as rows in the graph. I guess it's beyond a simple graph. 😅
