### ISSUE TITLE
Filter does not work on the graph shared by link

### ISSUE THREAD

**Issue by hirehamva** [Rello/analytics#224]
https://sharelink.hu/index.php/apps/analytics/p/WK276he7bRwsw65

**Comment by Emporea** [comment]
will 4.0.1 also fix that a shared link shows this strange time AM PM format? I had this issue in early 2020 and you fixed it. But it seems like its back.

https://files.iamspecial.rip/apps/analytics/p/BkMna6LYEOdJolH

(screenshot of shared link)
![image](https://user-images.githubusercontent.com/21969523/142702082-c12214c0-630c-4b62-b101-4abe70a1ab5c.png)

What it should show is this:

(screenshot of graph while logged into nextcloud)
![image](https://user-images.githubusercontent.com/21969523/142702148-4be250a2-d15f-4eb1-bd76-1be7514f5fdf.png)

**Comment by Rello** [comment]
oh, did not see this
will fix this also and then push the change soon

**Comment by Emporea** [comment]
> oh, did not see this will fix this also and then push the change soon

Thank you!

**Comment by Rello** [comment]
Hello,
it actually works as expected. reason for your behavior is the screen width.
when logged in, you have the navigation an the screen is smaller. chartjs is adopting the axis automatically.
what you can do is to manually set the chart formatting using the chartoptoins so it will always be the same.

e.g.
{"scales": {"xAxes": {"time": {"unit" : "month"}}}}
https://github.com/Rello/analytics/wiki/Advanced-chart-options
