### ISSUE TITLE
Color of closure icon

### ISSUE THREAD

**Issue by Valdnet** [Rello/analytics#225]
I propose to change the color of the "X" closure icon from black to white in the welcome window of the application for a light theme.

![obraz](https://user-images.githubusercontent.com/47037905/142241249-e3ff5c6e-6f39-44d5-85a6-3de6771272e8.png)

Apps:
Nextcloud 22.2.3
Analytics 4.0.0

**Comment by Rello** [comment]
i changed it to a brighter background. the icon itself gives me css headaches.
will make a better fix later
