### ISSUE TITLE
No default text in dropdown

### ISSUE THREAD

**Issue by Valdnet** [Rello/analytics#226]
In the selection for "Datasource" there should be a text string, eg "None", which informs that the data source was not selected. Currently, an empty position is selected.

![obraz](https://user-images.githubusercontent.com/47037905/142244855-60a3256d-cc22-4756-824f-6e3be549b63b.png)

Apps:
Nextcloud 22.2.3
Analytics 4.0.0

**Comment by Valdnet** [comment]
It's the same here, no text string:

![obraz](https://user-images.githubusercontent.com/47037905/142250316-f72c03ea-b34a-4901-a69f-8e9bd6ffa691.png)

**Comment by Rello** [comment]
> It's the same here, no text string:
> 
> ![obraz](https://user-images.githubusercontent.com/47037905/142250536-af36c503-07f8-4b54-a564-51e661e5cea3.png)

Hello,
you should see the column descriptions there. I guess in your case you did not maintain a text for column 1?
but a good find anyway - I will introduce a fallback tex
![Bildschirmfoto 2021-11-17 um 18 55 42](https://user-images.githubusercontent.com/13385119/142255684-01f62b0f-9d9a-4e9c-9acc-76156f501ec4.png)
t

**Comment by Rello** [comment]
> In the selection for "Datasource" there should be a text string, eg "None", which informs that the data source was not selected. Currently, an empty position is selected.

ok. correct. "none" is no valid selection. I will add an "please choose" or so

thank you

**Comment by Valdnet** [comment]
> you should see the column descriptions there. I guess in your case you did not maintain a text for column 1?

Exactly 😉.

> ok. correct. "none" is no valid selection. I will add an "please choose" or so

👍
