### ISSUE TITLE
Need access to individual array entries in JSON data

### ISSUE THREAD

**Issue by mossholderm** [Rello/analytics#229]
I have a similar issue to #99 , where I need to load JSON data that contains an array. However, in my case, the issue is that the JSON from the source is always a single entry array, like this:

```
{
  "ZbStatus3": [
    {
      "Device": "0xXXXX",
      "IEEEAddr": "0xXXXXXXXXXXXXXXXXXX",
      "ModelId": "lumi.weather",
      "Manufacturer": "LUMI",
      "Endpoints": [
        1
      ],
      "Config": [
        "T01"
      ],
      "Temperature": 19.83,
      "Pressure": 1015,
      "Humidity": 53.82,
      "Reachable": false,
      "BatteryPercentage": 92,
      "LastSeen": 865040,
      "LastSeenEpoch": 1636387179,
      "LinkQuality": 86
    }
  ]
}
```

Would it be possible to always take the first array entry in such situations? Or perhaps if a path entry is just a number (e.g. /ZbStatus3/0/Temperature), treat it as an array index?

**Comment by Rello** [comment]
let me check. I think I solved the same issue for myself somehow...
