### ISSUE TITLE
JSON data source: POST body; reading arrays

### ISSUE THREAD

**Issue by Aarkon** [Rello/analytics#233]
There is no (or at least apparent or documented) way to provide a body for a HTTP POST request when using JSON. This is unfortunate as there are APIs out there which won't give you data unless you provide specific information this way.

I don't believe this would be too hard:  An optional text input field which's content is parsed to json would do the trick I think.

Thanks for the great work so far non the less!

**Comment by Rello** [comment]
Hello,
do you have an example for this API?

**Comment by Aarkon** [comment]
Of course: https://cex.io/rest-api#chart

**Comment by Rello** [comment]
ok, 
interesting. Think it should be do-able with limited effort.
I will have a look...

**Comment by Rello** [comment]
Hello,
I am looking at the API but don´t get anything meaningfull. the return will not be values but a chart if I understood correctly?
or did I miss anything? I was trying BTC/USD as pair. 
do you have a working example?

**Comment by Aarkon** [comment]
Oh yeah, I could have figured out this would be useful before you even asked. ^^
This one is the example from the documentation and it works in bash:
```
curl -L -X POST "https://cex.io/api/price_stats/BTC/EUR" -H "Content-Type: application/json" --data-raw "{
  \"lastHours\": 24,
  \"maxRespArrSize\": 100
}"
```

**Comment by Rello** [comment]
Hello,
I don´t get any usefull result when trying with Postman to simulate a json post.
what do you expect?

![Bildschirmfoto 2021-11-25 um 10 22 56](https://user-images.githubusercontent.com/13385119/143414561-796988c7-b846-4cd6-aeeb-403f66ea4d25.png)

**Comment by Aarkon** [comment]
Hmm, that's odd. Maybe try using raw data?
![image](https://user-images.githubusercontent.com/4244486/143423766-5fab6767-98df-4882-af89-57fa6d5d077d.png)

**Comment by Rello** [comment]
Hi,
little update. this is an interesting case.
The datasource can handle POST + Body after the enhancement.

But the current concept is, that you read a dedicated single value - and not a whole array.
This screenshot shows your example:
![Bildschirmfoto 2022-02-23 um 16 35 29](https://user-images.githubusercontent.com/13385119/155352350-90d98d48-b13b-467a-aa36-2dbc7aa412c2.png)

2 values could be read. but in your case you want to read one array of tmsp/price as one record combination into the report, correct?
and then all of these arrays.
I mean you expect to do a chart on the whole history of timestamps+price, correct?

seems reasonable - but need to find a way to make the datasource that flexible

**Comment by Rello** [comment]
OK, this is the plan:

The path-input field is extended to indicate an array-input by using {}. inside the brackets, the required columns need to be selected.
![Bildschirmfoto 2022-02-23 um 17 10 34](https://user-images.githubusercontent.com/13385119/155359311-82d160e3-721a-45ac-9cdc-228b68b42f90.png)

using this, the values can be shown in a report
![Bildschirmfoto 2022-02-23 um 17 12 05](https://user-images.githubusercontent.com/13385119/155359624-75759bfd-7bf1-4d49-b870-9bd3898c2299.png)

note: as the data uses the timestamp format, this needs to be specified in the chart options. see [wiki](https://github.com/Rello/analytics/wiki/Advanced-chart-options#examples-from-user-questions)

I guess this is what you wanted?

**Comment by Rello** [comment]
Addition: the object path also allows text for not used columns.
e.g. `{BTC,tmsp,price}`

will result in 
![Bildschirmfoto 2022-02-23 um 17 33 20](https://user-images.githubusercontent.com/13385119/155363610-139b702e-03c7-49c9-9965-efb522d6ef69.png)
by this, several currencies could be loaded

**Comment by Rello** [comment]
https://github.com/Rello/analytics/wiki/Datasource:-JSON

**Comment by Aarkon** [comment]
This looks quite nice! It will take some time for me to really try this out though because I'm horribly busy atm with taking care of my family. I hope I'll remember to come back here once e.g. child care is open again. But again, it looks promising.
