### ISSUE TITLE
Search error

### ISSUE THREAD

**Issue by elhananjair** [Rello/analytics#234]
Hello there, I am not sure if this analytics issue or a Nexcloud Server issue, every time I start typing something inside the search field, the above error shows up for each input I type. 

![image](https://user-images.githubusercontent.com/69236638/144606352-8bb5ae11-6b13-42ae-9536-15292a7ba549.png)

**Comment by Rello** [comment]
oh. nice finding.
i am also getting this error. Will check today

**Comment by Rello** [comment]
4.0.2 released

**Comment by elhananjair** [comment]
> 4.0.2 released

Hello @Rello thank you so much for quick fix, but I am still facing that issue and am on NC 22.2.0. I have updated Analytics to 4.0.2, I've refreshed my Browser and and the problem still persist, here is the log from Nextcloud.

> {"reqId":"Ya2iB_pi2pzP-oP8w7tk8QAAhgk","level":3,"time":"2021-12-06T05:39:19+00:00","remoteAddr":"192.168.22.210","user":"Amanuel Kumera","app":"no app in context","method":"GET","url":"/ocs/v2.php/search/providers/analytics/search?term=IT+T&from=%2Fapps%2Fdeck%2F","message":"Call to undefined method OCA\\Analytics\\Service\\DatasetService::search()","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0 Waterfox/91.3.3","version":"22.2.0.2","exception":{"Exception":"Exception","Message":"Call to undefined method OCA\\Analytics\\Service\\DatasetService::search()","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/nextcloud/ocs/v1.php","line":62,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/nextcloud/ocs/v2.php","line":23,"args":["/var/www/html/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":158,"Previous":{"Exception":"Error","Message":"Call to undefined method OCA\\Analytics\\Service\\DatasetService::search()","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/lib/private/Search/SearchComposer.php","line":162,"function":"search","class":"OCA\\Analytics\\Search\\Provider","type":"->"},{"file":"/var/www/html/nextcloud/core/Controller/UnifiedSearchController.php","line":115,"function":"search","class":"OC\\Search\\SearchComposer","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"search","class":"OC\\Core\\Controller\\UnifiedSearchController","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/nextcloud/ocs/v1.php","line":62,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/nextcloud/ocs/v2.php","line":23,"args":["/var/www/html/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/html/nextcloud/apps/analytics/lib/Search/Provider.php","Line":50},"CustomMessage":"--"},"id":"61ada3c8a143e"}

**Comment by Rello** [comment]
thats really strange.
it works for me.
this file here was updated corretly
https://github.com/Rello/analytics/blob/master/lib/Search/Provider.php

hmmm

**Comment by Rello** [comment]
Hi.
Is the error still existing?
Only reason i can think off is that the pho cached an old file version?

**Comment by elhananjair** [comment]
> Hi. Is the error still existing? Only reason i can think off is that the pho cached an old file version?

yes you're right I rebooted the server and now its working. Thanks @Rello
