### ISSUE TITLE
Make dataload faster

### ISSUE THREAD

**Issue by sirdrakeistda** [Rello/analytics#236]
I learned Python, so I'm not really familiar with php. I hope my hints will still help.

When I load bigger datasets with Analytics on my Raspberry Pi the dataload often gets killed while loading the same Data with Pandas (Python) is not a problem. So I looked a little bit into the code and I think I have an idea how to improve the code.

If I understood the code correctly you append the array after every new line. According to this site it would be faster to first create an empty array and then fill it instead of append an extisting array:
https://stackoverflow.com/questions/559844/which-is-faster-in-php-array-value-or-array-pusharray-value

Thanks for your great work. It would be nice to save resources on older/slower hardware in future.

**Comment by Rello** [comment]
Hi,
which code section are your referring to?

**Comment by sirdrakeistda** [comment]
https://github.com/Rello/analytics/blob/master/lib/Datasource/ExternalFile.php
line 109

**Comment by Rello** [comment]
ok, interesting. I will definitely look at it!
do you have a url/file which you use and where the performance is noticeable?

In general, Analytics will never be close to Pandas, as this is much more made for big data.
Analytics is more generic.

But any insights like this. are very helpful!

**Comment by sirdrakeistda** [comment]
On my raspberry Pi is the process killed with this datasource:
https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv
columns: 3,4,37

I understand, that pandas has a different use case. I looked into pandas to learn a little bit what they do and what could be done different/better. Of course a comparison is not really fair, but I think learning from them is a good idea.

**Comment by Rello** [comment]
Hi,
I will definitely have a look and try to optimize
i will keep you posted

**Comment by sirdrakeistda** [comment]
I see also the check in line 108 where you check if the columns are numerical numbers. Is there a reason for doing this in a loop? I think it would be faster to check before the loop if the columns are numbers and then start the loop. Normally are if operations in a loop very slow.

If I made a mistake, please correct me.

**Comment by sirdrakeistda** [comment]
I tried to restructure the program. I'm not sure if this code could work, but it gives an idea what I meant with the previous comment (line 108 and 106). I tried to restructured line 102 to 124 to prevent multiple unnecessary if functions. The code is just a sketch, not a finished program. Also the part with changing to a fixed instead of appending an array is not yet included. I hope this could help:

```
if (count($selectedColumns) !== 0) {
	foreach($selectedColumns as $selectedColumn) {
		#convert selected_column to int_selected_column
	}
	foreach ($rows as &$row) {
        	$row = str_getcsv($row, $delimiter);
        	$rowMinimized = array();
        	foreach ($selectedColumns as $selectedColumn) {
                	array_push($rowMinimized, $row[$int_selected_Column - 1]);

                }
                if ($headerrow === 0) {
                	$header = $rowMinimized;
                	$headerrow = 1;
            	} else {
                	array_push($data, $rowMinimized);
            	}
	}
}
               
else {
	foreach ($rows as &$row) {
        	$row = str_getcsv($row, $delimiter);
        	$rowMinimized = array();
        	$rowMinimized = $row;
        	if ($headerrow === 0) {
        		$header = $rowMinimized;
               	$headerrow = 1;
        	} else {
               	array_push($data, $rowMinimized);
        }
}
```

**Comment by Rello** [comment]
Hi,
sorry for the delay. picking up everything the next days finally...

**Comment by Rello** [comment]
Hello,
some topics were tested with your datasource example:

- default: Memory issue due to amount of data and wrong loop handling
`foreach ($rows as &$row)` The "&" was removed as a writeback to the original array is not required
=> Execution time now 12s

- replace all array_push 1:1 with array[]
no measurable effect
=> Execution time still 12s

- remove `if (count($selectedColumns) !== 0)` from loop
no measurable effect; but still cleaner; will separate
=> execution time still 12s

will try some other column handling.
but I think the obsolete "&" did the trick

**Comment by Rello** [comment]
Update:
code was drastically improved. its now loading all the 35k records in under a minute.
you can have a look already here
https://github.com/Rello/analytics/blob/master/lib/Datasource/ExternalFile.php#L102-L115

**Comment by sirdrakeistda** [comment]
Sounds great. I'm excited to see this update!

**Comment by Rello** [comment]
4.0.3 was released.
let me know if it works for you
