### ISSUE TITLE
Cannot set "can navigate" for other than the very first user in the list

### ISSUE THREAD

**Issue by fthommen** [Rello/analytics#238]
Setting "can navigate" seems to only set it for the first sharing user in the list, but not for others.  No matter, for which user I set it. You can see in the following short screencast, that if I change this setting for the second user, it is still applied to the first user instead:

https://user-images.githubusercontent.com/279232/145729632-91018757-b91d-467a-9914-f9e5de03abbc.mov

  * Nextcloud Version: 21.0.7
  * Analytics App:  4.0.2
  * Operating system: CentOS 7.9
  * Browser: Firefox 95.0 and Google Chrome 96.0.4664.93 (both running on mac OS 12.0.1 Monterey)

**Comment by fthommen** [comment]
Maybe similar to (solved) #125 ?

**Comment by Rello** [comment]
sorry for the delay.
issue is found and fixed with the next version

**Comment by Rello** [comment]
4.0.3 was released.
let me know if it works for you

**Comment by fthommen** [comment]
Works!.  Thanks a lot
