### ISSUE TITLE
file picker not working

### ISSUE THREAD

**Issue by fthommen** [Rello/analytics#239]
Hi,

in Advanced configuration -> Dataload clicking in the "File" field (when local files are specified as data sources) doesn't open a file select dialogue.  How should the data file be specified in this field?

**Comment by Rello** [comment]
Let me check. It should work this way?!

**Comment by Cyberseal89** [comment]
I'll leave this here, but might be new, having issues with both the file picket whether a cxv or spreadsheet underneath basic settings data import which always fails, and in the data under advanced configuration. Was able to utilize the tool succesfully, but had to manually input everything, if I can get to file import, and also select which columns to display in the graphs would be huge with larger datasets.

**Comment by Rello** [comment]
4.0.3 was released.
let me know if it works for you

**Comment by fthommen** [comment]
The file picker works again.  Thanks
