### ISSUE TITLE
Feature Request Colored Graphs

### ISSUE THREAD

**Issue by Emporea** [Rello/analytics#24]
Hey there,

is it somehow possible to specify the color of a graph inside a csv? Maybe add a forth column or so.
I am not able to find any documentation to what is possible with the nextcloud analytics app, but its so useful!

**Comment by Rello** [comment]
Hello,
I am just redoing the charts because I have to switch to another library. once I have more insight, I can answer this question, ok?

**Comment by Rello** [comment]
Hello,
the next version of Analytics will be based on chart.js.
There I am using the plugin 
https://nagix.github.io/chartjs-plugin-colorschemes

the current default scheme is `tableau.ClassicLight10`
Further customization like scheme selection will come later.

![Screenshot 2020-03-10 at 12 51 52](https://user-images.githubusercontent.com/13385119/76309852-ed766b00-62cd-11ea-851c-aacf9281be0c.png)

This is a general setting. To maintain color values within data itself is a very limited usecase and not on the roadmap currently.
I plan to use the Threshold setting in the future. currently it defines colors within the datatable. perhaps this can be connected to the chart later.

thank you,
Rello
