### ISSUE TITLE
Cannot delete Analytics Dashboard

### ISSUE THREAD

**Issue by hufnala** [Rello/analytics#241]
Hello,
thanks for supporting the analytics function. I tried to use it, but loading data fails (see issue #237). 
I unfortunately cannot remove the non working report. Didn't try by now on the working sample ones not to lose them.

ReCreate:
- drop down menu of the report (3 dots)
- select "delete"
- confirm security request to delete "OK"
- sandwatch cursor is showing endless
- If I go back to "Analytics" all dashboards remain there
I tried several times waiting up to 5 min without success.

Nextcloud is hosted externally at "wolkesicher.de", so I'm not sure how to support additional information / logfiles.

BR hufnala

**Comment by hufnala** [comment]
Hi, issue is still there, no log entries (see issue #237). Also when I delete the full app and re-install all reports I made are still there. If I can support more, please let me know.

**Comment by Rello** [comment]
237 ist not related to the deletion button.
I tried it in my setups - working everywhere.

do you have the chance to create a temporary testuser for me on your instance?
please let me know at `analytics at scherello dot de`
