### ISSUE TITLE
Wrong data in bargraph

### ISSUE THREAD

**Issue by Rauhaardackel** [Rello/analytics#247]
Hi,
@Rello: Awesome tool, thank you.

I have the following csv file:
```
Status,Bearbeiter*in,Anzahl
"in Bearbeitung",p1,2
"in Bearbeitung",p2,7
"in Bearbeitung",p3,107
offen,p3,13
"in Bearbeitung",p4,131
offen,p4,63
"in Bearbeitung",p5,29
offen,p5,25
"in Bearbeitung",p6,28
offen,p6,31
"in Bearbeitung",p7,54
offen,p7,48
"in Bearbeitung",p8,40
offen,p8,6
"in Bearbeitung",p9,15
offen,p9,2
"in Bearbeitung",p10,16
offen,p10,14
"in Bearbeitung",p11,42
offen,p11,17
"in Bearbeitung",p12,57
offen,p12,35
"in Bearbeitung",p13,10
"in Bearbeitung",p14,5
offen,p14,5
"in Bearbeitung",p15,125
offen,p15,11
"in Bearbeitung",p16,65
offen,p16,10
"in Bearbeitung",p17,7
offen,p17,6
offen,p18,3
"in Bearbeitung",p19,63
offen,p19,11
"in Bearbeitung",p20,25
offen,p20,10
"in Bearbeitung",p21,52
offen,p21,6
"in Bearbeitung",p22,12
offen,p22,11
"in Bearbeitung",p23,1
offen,p23,15
```
It creates the following plot:
![image](https://user-images.githubusercontent.com/88343783/151034473-052c3aa7-efbe-49c5-b5dc-92dc53f8a125.png)
As you can see, the value in the bargraph for p7 is wrong. However, the table shows the correct value.

**Comment by Rello** [comment]
I think I see the issue. 
p1 and p2 dont have open counts 

a bar chart is matching all values sequentially. It expects the categories to be the same. 

Is it possible that you have the data incl. 0 for missing values?
I will test later on my side and will get back…

**Comment by Rauhaardackel** [comment]
You are right. I will adapt my scripts which write the csv files. That's no problem for me. However, I think it's worth to fix analytics. It's already in its early stage a very useful tool for me.

Thank you very much for your quick answer.

**Comment by Rello** [comment]
Hello,
thank you for the feedback. 
There is no fix that I could imagine. because what should the tool do?
It would need to loop all possible dimensions and compare them; match them; add missing ones.
And for missing ones, what should be added? not existing != 0
adding 0 for example might help your case - but not everyone as it is altering the date that is existing


Regards,...
