### ISSUE TITLE
l10n: Rebuild text string

### ISSUE THREAD

**Issue by Valdnet** [Rello/analytics#252]
Suggestion to rebuild the following text string:

https://github.com/Rello/analytics/blob/5cf9370c74eaa5c595ba11d04e0b027481a72bcd/js/filter.js#L121-L122

1. The string should be combined into one sentence. _(Reported on Transifex.)_
2. Extract the link's address from the text string (replace it with a variable). This will eliminate mistakes when translating by translators.
3. Change the word "wiki" to "Wiki".
4. Remove comment for translators. After the change, it will no longer be needed.

**Comment by Rello** [comment]
done. thank you

**Comment by Rello** [comment]
@Valdnet 
just checking the new strings in Tran.
I also put in the technical ones from the JSON request:
Request body
Header Content-Type

I think they have to be removed because they are technical terms, correct?

**Comment by Valdnet** [comment]
Show me some of these text strings 😉.
