### ISSUE TITLE
l10n: Text strings in demo

### ISSUE THREAD

**Issue by Valdnet** [Rello/analytics#254]
There is no translation for the demo version. The demo version should also be created in the user's native language.

![obraz](https://user-images.githubusercontent.com/47037905/155284526-bcbf78d9-f38e-4a7d-97b7-9d26f2817f69.png)

**Comment by Rello** [comment]
do I also need to translate the table entries? I think no. 
the rest is prepared

**Comment by Valdnet** [comment]
> do I also need to translate the table entries?

It would be nice to have the examples translated in mother tongue. In my opinion there will be too much of a mix of languages.
What do you think about @rakekniven?

**Comment by Rello** [comment]
ok, I added these texts also. lets see what happens tomorrow
