### ISSUE TITLE
l10n: Untranslated messages

### ISSUE THREAD

**Issue by Valdnet** [Rello/analytics#255]
Add the following text strings for translation:

https://github.com/Rello/analytics/blob/94b62862f3c0a69d0f103259a632dab227cfaa8a/js/sidebar.js#L475
https://github.com/Rello/analytics/blob/94b62862f3c0a69d0f103259a632dab227cfaa8a/js/sidebar.js#L477
https://github.com/Rello/analytics/blob/94b62862f3c0a69d0f103259a632dab227cfaa8a/js/sidebar.js#L479

![obraz](https://user-images.githubusercontent.com/47037905/155284613-a1f7b5b7-cdae-48e4-bc44-71bba0f240a6.png)

Check other messages as well.

**Comment by Rello** [comment]
thank you.
actually these are not missing - these are leftovers from old code 😳
will clean up

**Comment by Rello** [comment]
done
thanks
