### ISSUE TITLE
Text string for filter

### ISSUE THREAD

**Issue by Valdnet** [Rello/analytics#256]
Steps:

1. Create a new report with no data.
2. Choose your filter settings.

Unknown text string for filter setting:

![obraz](https://user-images.githubusercontent.com/47037905/155290412-aa20dab4-606b-44c6-ae25-9587acd766f9.png)

**Comment by Rello** [comment]
Hi,
this can not be translated, as this is the actual name of your data column.
in the demo report thats just the default name
![Bildschirmfoto 2022-02-23 um 10 32 52](https://user-images.githubusercontent.com/13385119/155292919-62b67e43-1370-4923-9a91-fb402e0cc86d.png)

**Comment by Valdnet** [comment]
> this can not be translated

@Rello I do not mean translating this text string.

In my opinion, if there is no data yet, it should not show up at all for a filter setting. This is a bit of a strange value for a user who doesn't know where it came from.
