### ISSUE TITLE
Analysis functions (beta): Aggregate / disaggregate values

### ISSUE THREAD

**Issue by Rello** [Rello/analytics#258]
***still in beta***
Use the new function to calculate single values form cumulative numbers 
![Bildschirmfoto 2022-02-26 um 14 30 05](https://user-images.githubusercontent.com/13385119/155845099-c0861b67-2dcf-4b1a-810d-2969c45bcafb.png)

**Comment by tatrapikao** [comment]
I have a Dataset of wich i use Value1 as column, Value2 is Date and Value3 is my Measurment. Is there possibility to only show the disagregated Measurements of a given Column as Bars and save that View? I try to plot the change in Energy consumption based on a couple of power-meter readings aggregated via the tables app.
