### ISSUE TITLE
Update from 4.0.3 to 4.1.0 → App with id analytics has invalid signature

### ISSUE THREAD

**Issue by nursoda** [Rello/analytics#260]
There's something wrong with the signature of version 4.1.0

**Comment by Rello** [comment]
thank you for the message.
I got app-store failures and did not even know that it was released there!?

I just signed everything fresh and released 4.1.1
lets try

**Comment by Rello** [comment]
works now.
thanks

**Comment by nursoda** [comment]
I see that 4.1.1 is in the Nextcloud App store. However, my cloud that got the 4.1.0 update does not offer to install it. Not sure where it may be cached. That cloud doesn't see the 4.1.0 any longer, but it also doesn't see the 4.1.1. yet. Will retry tomorrow.

**Comment by nursoda** [comment]
> …Will retry tomorrow.

Update is there and installed fine. Thanks!
