### ISSUE TITLE
l10n: Add translations to Transifex

### ISSUE THREAD

**Issue by Valdnet** [Rello/analytics#261]
I propose to add translations to Transifex of the following text strings:

https://github.com/Rello/analytics/blob/487e786abd574874116953ae3d1e476d5bb323c5/templates/wizard.php#L149
https://github.com/Rello/analytics/blob/487e786abd574874116953ae3d1e476d5bb323c5/templates/wizard.php#L152

![obraz](https://user-images.githubusercontent.com/47037905/157255817-59a30ae3-0fe0-4909-a51a-c0776ee68bd7.png)

https://github.com/Rello/analytics/blob/75698ef64074240633972df598bd6aa2e6948944/templates/part.content_advanced.php#L34-L37

![obraz](https://user-images.githubusercontent.com/47037905/157256623-ec0ecc18-d8db-44ec-b372-16a838868ec4.png)

App:
Analytics 4.1.1

**Comment by Rello** [comment]
thank you
will take care

**Comment by Valdnet** [comment]
There is no translation for the following strings.

- Demo: Analytics Downloads

![obraz](https://user-images.githubusercontent.com/47037905/157282334-1ae9c50e-9734-4d5f-a497-46598e368673.png)

- Demo: Population Data

![obraz](https://user-images.githubusercontent.com/47037905/157282531-e67b38ae-aa71-4cd5-ac2c-046b75a24434.png)

**Comment by Rello** [comment]
first one (from Github) is changed.
second one is dependent on the datasource. its a csv file and this does not have language support
