### ISSUE TITLE
Quick start closure

### ISSUE THREAD

**Issue by Valdnet** [Rello/analytics#264]
Source text
After clicking "Create Demo" in the quick start the window should **close automatically**.
Currently, the user is clicking and not knowing if a demo is created. When you click again, the demo is created again (it is duplicated).

![obraz](https://user-images.githubusercontent.com/47037905/157260538-353d3d98-f4de-4d4f-855d-52db583558e1.png)

App:
Analytics 4.1.1

**Comment by Rello** [comment]
Good point.
thank you
