### ISSUE TITLE
l10n: Character to translate

### ISSUE THREAD

**Issue by Valdnet** [Rello/analytics#266]
I suggest adding the sign `&` to translate to Transifex, because this conjunction is spelled differently in different languages, e.g.: in Polish you do not use "&" only "i".

You can also add a note for translators so that they know what this sign applies to.

![obraz](https://user-images.githubusercontent.com/47037905/157410875-553d8908-1f99-40bf-8272-a60ce9d8e690.png)

**Comment by Rello** [comment]
done
