### ISSUE TITLE
Couldn't see charts and tables based on my imported CSV, 

### ISSUE THREAD

**Issue by elhananjair** [Rello/analytics#268]
Hello @Rello I am amazed how the Analytics app is evolving to be the best app of nextcloud, I have used Analytics lately I am totally newbie to the new UI, I couldn't even knew how can I create Groups 😂, I suggest if there is any video or any tutorials for basic functionalities of Analytics. 

I wanted to see detailed info of some imported CSV file in charts but I couldn't achieve that, I am struggling with the new UI. Please check out the attached video. Thank you 

https://user-images.githubusercontent.com/69236638/157659721-2c5b5788-f94f-4bec-a6e0-90be306036b6.mp4

**Comment by Rello** [comment]
Hello,

thank you for getting back.
correct - the group thing is a todo. it needs to be more obvious.

regarding your issue - you did everything correct as far as I can see. Just that you did not load the data.
you chose to load/import the data (you could also use the realtime version for the CSV).
you created the dataload corretly.

but then - you need to press the "load" button on the right. first with the simulation flag set. it will give you a preview of the data. when it looks correct, you can real-load (without the flag set).

give it a try....

**Comment by Rello** [comment]
naja, thats a tricky one. thats some very bad file format.
Analytics has to work with defined columns (up to 3 for now) and endless rows.
here you have column based data with the years across and not in rows.
This can not work out of the box here.

first, the data seems to have 3 leading rows (need to be ignored; there is an input field for this).
second, you would need to select which columns you want to see by entering their numbers in the other textbox.

I would assume e.g.
`1,3,70` (being country name; Indicator name; year 2020 e.g.)
the load would then select these columns.

its little difficult with this strange format.
feel free to post a portion of the file as CSV here

**Comment by elhananjair** [comment]
oww I see let me share you the CSV file, I don't think it is compatible with analytics. 
[API_NY.GDP.MKTP.KD.ZG_DS2_en_csv_v2_3731395.csv](https://github.com/Rello/analytics/files/8223482/API_NY.GDP.MKTP.KD.ZG_DS2_en_csv_v2_3731395.csv)

**Comment by Rello** [comment]
Hi,
did you find a workaround here for your file?
the format is really complex in this example

**Comment by elhananjair** [comment]
> Hi, did you find a workaround here for your file? the format is really complex in this example

I just downloaded some random CSV file, As you explained to me once, I think the Analytics app is somehow limited to some kind of spreadsheet structure, like only three columns to support. In my case, I usually want to use Analytics to view some statistics in charts or tables.

**Comment by Rello** [comment]
yes, correct. when loading data into an internal data set, only 3 columns are possible.
I am thinking about extending. but it will alway be a given number as I am still dependent on the Nextcloud ecosystem and can not freely create variable tables for every different report as other pure reporting tools can do

**Comment by elhananjair** [comment]
Thank you so much, @Rello for the great job you're doing.
