### ISSUE TITLE
Widget not loading

### ISSUE THREAD

**Issue by XHyperDEVX** [Rello/analytics#269]
Hello,

the Widget on the Nextcloud Dashboard is not loading!

I use the newest Version of Nextcloud.

How i can fix that?

**Comment by Rello** [comment]
Hi,

first I need more details.
can you please check the NC log or the browser-log?
it is working in all my test-instances

**Comment by XHyperDEVX** [comment]
Hello

I'm sorry I haven't said this information yet, I was under stress.

On my PC, MS Edge, that loads the widget not, see here:

![Screenshot 2022-03-21 151508](https://user-images.githubusercontent.com/68189420/159280022-f4f8f55d-0e2f-4ab4-b3ec-eada1ffca872.png)

On my Andorid phone, also MS Edge, loads the widget, but there is no option to set it, see here:
[even if I open the website in desktop mode]

![Screenshot_20220321-151342_Edge](https://user-images.githubusercontent.com/68189420/159280300-0178ced7-3e3c-47ec-aa37-657c8eebf0ea.png)

Thx for your answer, do you have an idea?

**Comment by XHyperDEVX** [comment]
The problem has been solved, thanks for your answer!
