### ISSUE TITLE
 当旭日图中有负值的时候显示的问题

### ISSUE THREAD

**Issue by weixingcai** [Rello/analytics#27]
https://jshare.com.cn/temp/ZOGGQw 当旭日图中有负值的时候显示的问题

**Comment by aszlig** [comment]
translation: Problems showing when there are negative values in the sunburst chart

**Comment by aszlig** [comment]
Maybe duplicate of #26?

**Comment by Rello** [comment]
Hello,
this charttype is not supported by DA at the moment.
Additionally, the next release will switch from highcharts to chart.js for licensing reasons.

thank you
