### ISSUE TITLE
How can I set the date and time to the X-axis?

### ISSUE THREAD

**Issue by sha-marsig** [Rello/analytics#270]
I would like to show the labels on the X-axis in the following format:

'YYYY-MM-DD HH:mm'

How can I do it?

At the moment I was only able to show the date or the time with the diagram options but not together.

**Comment by Rello** [comment]
Hi,
did you play with this setting already?
`{"scales": {"xAxes": {"time": {"unit" : "month"}}}}`
https://github.com/Rello/analytics/wiki/Advanced-chart-options

**Comment by sha-marsig** [comment]
> Hi, did you play with this setting already? `{"scales": {"xAxes": {"time": {"unit" : "month"}}}}` https://github.com/Rello/analytics/wiki/Advanced-chart-options

Yes and I have not found a setting to get both date and time.

**Comment by Rello** [comment]
Hi,

I just tried this:
`{"scales": {"xAxes": {"time": {"unit" : "day","displayFormats":{"day":"YYYY-MM-DD HH:mm"}}}}}`

and it worked for me.
https://www.chartjs.org/docs/latest/axes/cartesian/time.html#display-formats

**Comment by sha-marsig** [comment]
> Hi,
> 
> I just tried this: `{"scales": {"xAxes": {"time": {"unit" : "day","displayFormats":{"day":"YYYY-MM-DD HH:mm"}}}}}`
> 
> and it worked for me. https://www.chartjs.org/docs/latest/axes/cartesian/time.html#display-formats ![Bildschirmfoto 2022-05-02 um 16 49 31](https://user-images.githubusercontent.com/13385119/166255028-a280767c-17b9-4037-9531-0d9d2e6e11cb.png)

Yes, perfect. That's what I was looking for.
