### ISSUE TITLE
Syntax error or access violation: 1072 Key column 'dataset' doesn't exist in table

### ISSUE THREAD

**Issue by zasquash** [Rello/analytics#271]
Hello everyone,

I have issue when i would like install analytics app.

I have NC 23.0.3
`MariaDB [(none)]> SELECT VERSION();
+----------------------------------------+
| VERSION()                              |
+----------------------------------------+
| 10.6.7-MariaDB-1:10.6.7+maria~bullseye |
+----------------------------------------+
1 row in set (0.000 sec)
`

Error is:
"An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1072 Key column 'dataset' doesn't exist in table"

I don't understand error.
Can someone help me ?

best regards,

**Comment by Rello** [comment]
Hello
Anything in the nextcloud log?

**Comment by zasquash** [comment]
thank you so much for your answer:

log:

`
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1072 Key column 'dataset' doesn't exist in table
/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php - line 1780:

Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert()
/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php - line 1719:
Doctrine\DBAL\Connection->handleDriverException()
/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php - line 1067:
Doctrine\DBAL\Connection->convertExceptionDuringQuery()
/var/www/nextcloud/lib/private/DB/Connection.php - line 237:
Doctrine\DBAL\Connection->executeQuery()
/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php - line 1809:
OC\DB\Connection->executeQuery()
/var/www/nextcloud/lib/private/DB/Migrator.php - line 175:
Doctrine\DBAL\Connection->query()
/var/www/nextcloud/lib/private/DB/Migrator.php - line 76:
OC\DB\Migrator->applySchema()
/var/www/nextcloud/lib/private/DB/Connection.php - line 546:
OC\DB\Migrator->migrate()
/var/www/nextcloud/lib/private/DB/MigrationService.php - line 463:
OC\DB\Connection->migrateToSchema()
/var/www/nextcloud/lib/private/DB/MigrationService.php - line 417:
OC\DB\MigrationService->migrateSchemaOnly()
/var/www/nextcloud/lib/private/Installer.php - line 154:
OC\DB\MigrationService->migrate()
/var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php - line 452:
OC\Installer->installApp()
/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217:
OCA\Settings\Controller\AppSettingsController->enableApps()
/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126:
OC\AppFramework\Http\Dispatcher->executeController()
/var/www/nextcloud/lib/private/AppFramework/App.php - line 157:
OC\AppFramework\Http\Dispatcher->dispatch()
/var/www/nextcloud/lib/private/Route/Router.php - line 302:
OC\AppFramework\App::main()
/var/www/nextcloud/lib/base.php - line 1006:
OC\Route\Router->match()
/var/www/nextcloud/index.php - line 36:
OC::handleRequest()

Causé par Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[42000]: Syntax error or access violation: 1072 Key column 'dataset' doesn't exist in table

/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Connection.php - line 87:
Doctrine\DBAL\Driver\PDO\Exception::new()
/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php - line 1062:
Doctrine\DBAL\Driver\PDO\Connection->query()
/var/www/nextcloud/lib/private/DB/Connection.php - line 237:
Doctrine\DBAL\Connection->executeQuery()
/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php - line 1809:
OC\DB\Connection->executeQuery()
/var/www/nextcloud/lib/private/DB/Migrator.php - line 175:
Doctrine\DBAL\Connection->query()
/var/www/nextcloud/lib/private/DB/Migrator.php - line 76:
OC\DB\Migrator->applySchema()
/var/www/nextcloud/lib/private/DB/Connection.php - line 546:
OC\DB\Migrator->migrate()
/var/www/nextcloud/lib/private/DB/MigrationService.php - line 463:
OC\DB\Connection->migrateToSchema()
/var/www/nextcloud/lib/private/DB/MigrationService.php - line 417:
OC\DB\MigrationService->migrateSchemaOnly()
/var/www/nextcloud/lib/private/Installer.php - line 154:
OC\DB\MigrationService->migrate()
/var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php - line 452:
OC\Installer->installApp()
/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217:
OCA\Settings\Controller\AppSettingsController->enableApps()
/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126:
OC\AppFramework\Http\Dispatcher->executeController()
/var/www/nextcloud/lib/private/AppFramework/App.php - line 157:
OC\AppFramework\Http\Dispatcher->dispatch()
/var/www/nextcloud/lib/private/Route/Router.php - line 302:
OC\AppFramework\App::main()
/var/www/nextcloud/lib/base.php - line 1006:
OC\Route\Router->match()
/var/www/nextcloud/index.php - line 36:
OC::handleRequest()
Causé par PDOException: SQLSTATE[42000]: Syntax error or access violation: 1072 Key column 'dataset' doesn't exist in table
/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Connection.php - line 82:
PDO->query()
/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php - line 1062:
Doctrine\DBAL\Driver\PDO\Connection->query()
/var/www/nextcloud/lib/private/DB/Connection.php - line 237:
Doctrine\DBAL\Connection->executeQuery()
/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php - line 1809:
OC\DB\Connection->executeQuery()
/var/www/nextcloud/lib/private/DB/Migrator.php - line 175:
Doctrine\DBAL\Connection->query()
/var/www/nextcloud/lib/private/DB/Migrator.php - line 76:
OC\DB\Migrator->applySchema()
/var/www/nextcloud/lib/private/DB/Connection.php - line 546:
OC\DB\Migrator->migrate()
/var/www/nextcloud/lib/private/DB/MigrationService.php - line 463:
OC\DB\Connection->migrateToSchema()
/var/www/nextcloud/lib/private/DB/MigrationService.php - line 417:
OC\DB\MigrationService->migrateSchemaOnly()
/var/www/nextcloud/lib/private/Installer.php - line 154:
OC\DB\MigrationService->migrate()
/var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php - line 452:
OC\Installer->installApp()
/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217:
OCA\Settings\Controller\AppSettingsController->enableApps()
/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126:
OC\AppFramework\Http\Dispatcher->executeController()
/var/www/nextcloud/lib/private/AppFramework/App.php - line 157:
OC\AppFramework\Http\Dispatcher->dispatch()
/var/www/nextcloud/lib/private/Route/Router.php - line 302:
OC\AppFramework\App::main()
/var/www/nextcloud/lib/base.php - line 1006:
OC\Route\Router->match()
/var/www/nextcloud/index.php - line 36:
OC::handleRequest()
`

**Comment by Rello** [comment]
found it. new version will be pushed in some minutes

**Comment by Rello** [comment]
4.2.1 released

**Comment by zasquash** [comment]
thank you so much
I test
