### ISSUE TITLE
API GET with curl Problems

### ISSUE THREAD

**Issue by Himra** [Rello/analytics#275]
Hello all,

I am trying to fetch data via the GET API.

![grafik](https://user-images.githubusercontent.com/15324567/161766425-0ce7d1d2-648f-4e9c-8dc7-9509c9ae4cea.png)

But unfortunately I get in all four cases which are described in the documentation no data, only a bool(false) or nothing at all.

What am I doing wrong?

Basically I want to get the values of the last entry of an ID

Thanks in advance

Himra

**Comment by Rello** [comment]
Hi,
did you try with plain curl in the console/terminal?

I just tried and it works as expected
`curl -u Admin:rq...iEnj -X GET -H "Content-Type: application/json" https://nc23/nextcloud/apps/analytics/api/3.0/datasets`

=>
`[{"id":2,"name":"Demo: Finance","dimension1":"Segment","dimension2":"Year","value":"\u20ac","type":2},{"id":1,"name":"Demo: Thresholds","dimension1":"Type","dimension2":"Thresholds","value":"Value","type":2},{"id":4,"name":"on column","dimension1":"Object","dimension2":"Date","value":"Value","dataloads":1,"schedules":0,"type":2},{"id":3,"name":"Power","dimension1":"Type","dimension2":"Date","value":"Value","dataloads":1,"schedules":0,"type":2}]`

**Comment by Himra** [comment]
Hi,

now I test all four ways of GET with [Insomnia](https://insomnia.rest/)

GET /nextcloud/apps/analytics/api/3.0/datasets
GET /nextcloud/apps/analytics/api/3.0/reports
is working

GET /nextcloud/apps/analytics/api/3.0/report/5
GET /nextcloud/apps/analytics/api/3.0/data/5
doesn't work

What's my fault?

**Comment by Himra** [comment]
Now I did manage to get a result on one.

I think I am expecting something different than GET can return here.
My goal is to read the stored measurement data and GET only gives me the configurations of the individual statistics, right?

**Comment by Rello** [comment]
hey, the first ones are the definitions. thats correct.
the data one is the content.
let me try....

**Comment by Rello** [comment]
Hi,
both works on my side. what is your error?

Report definition:
`curl -u Admin:rq9...iEnj -X GET -H "Content-Type: application/json" https://nc23/nextcloud/apps/analytics/api/3.0/report/4 --insecure`

`{"id":4,"dataset":2,"name":"Demo: Finance","subheader":"Sales and revenue of the last years.","type":2,"visualization":"ct","chart":"column","parent":0,"dimension1":"Segment","dimension2":"Year","value":"\u20ac","chartoptions":"","dataoptions":"[{\"yAxisID\":\"primary\",\"type\":\"bar\"},{\"yAxisID\":\"primary\",\"type\":\"bar\"},{\"yAxisID\":\"primary\",\"type\":\"bar\"},{\"yAxisID\":\"primary\",\"type\":\"line\"}]","filteroptions":"{\"filter\":{\"dimension2\":{\"option\":\"GT\",\"value\":\"2011\"}}}","refresh":null}`

Report data:
`curl -u Admin:r...Enj -X GET -H "Content-Type: application/json" https://nc23/nextcloud/apps/analytics/api/3.0/data/4 --insecure`

`[["Channel Partners","2012","18540.00"],["Channel Partners","2013","30216.00"],["Channel Partners".....`

**Comment by Himra** [comment]
I am a chump after all, I constantly tested the ID of the group instead of a real report. So the result was always empty.
My mistake at the beginning was that I used the dataset number instead of the report id.
Sorry for wasting your time.

**Comment by Himra** [comment]
hi
tested it now with PHP and always got this error
`string(48) "SSL certificate problem: certificate has expired"`

after adjusting my PHP script as follows:
```php
<?php
$curl = curl_init();
curl_setopt($curl, CURLOPT_URL, "https://xxxxx.xx/index.php/apps/analytics/api/3.0/data/9");
curl_setopt($curl, CURLOPT_USERPWD, "xxxxx:xxxxx");
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($curl, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
$response = curl_exec($curl);
$err = curl_error($curl);
curl_close($curl);

echo "--<pre>";
var_dump($err);
echo "</pre>";

$decoded_response = json_decode($response, true);
echo "<pre>";
var_dump($decoded_response);
echo "</pre>";
?>
```

it worked then.

Thanks and greetings
Himra

**Comment by Rello** [comment]
this has nothing todo with analytics. perhaps this?
https://stackoverflow.com/questions/35504771/php-curl-allow-calls-with-expired-certificate
