### ISSUE TITLE
issue in dataload: URL parsing replace &amp;

### ISSUE THREAD

**Issue by GH2204** [Rello/analytics#278]
Hi folks,

I want to create a selfrising dataset with prices of fuels with auto-dataload.
In the URL for the JSON data, there are two html-parameters, concatenated with an interampersand "&".
After I have saved the input, the interampersand "&" is changed to "&amp;" and the URL doesn't work. The test run ends with an error.
Found this: 

- https://stackoverflow.com/questions/3541711/url-encode-sees-ampersand-as-amp-html-entity
- https://stackoverflow.com/questions/9084237/what-is-amp-used-for
- https://stackoverflow.com/questions/16622504/escaping-ampersand-in-url

I'm using this URL: https://creativecommons.tankerkoenig.de/json/prices.php?ids=[ID_OF_FUELSTATION]&apikey=[MY_KEY]
After saving input-set URL is: https://creativecommons.tankerkoenig.de/json/prices.php?ids=[ID_OF_FUELSTATION]&amp;apikey=[MY_KEY]
After saving twice URL is: https://creativecommons.tankerkoenig.de/json/prices.php?ids=[ID_OF_FUELSTATION]&amp;amp;apikey=[MY_KEY]
...
or is there a mistake in my way of proceeding?

**Comment by Rello** [comment]
Hello,
thank you. this seems to be the result of an XSS-Protection fix. 
I will have a look. this does not make sense. you are correct

**Comment by Rello** [comment]
4.3.0 released

**Comment by paspil** [comment]
Looks to me like this is still broken.
With a URL like
`https://hostname.tld/data?foo=bar&baz=qwe`
and running
`occ analytics:load 1`
i will get
`> GET /data?foo=bar&amp;baz=qwe HTTP/1.1`
in the output and an error response from the server.

**Comment by Rello** [comment]
Hi,
this should be fixed.
can you please try to execute the dataload in the browser with the simulation flag?

then in the console of this request, you will see the url used
<img width="557" alt="Bildschirmfoto 2022-10-06 um 15 55 58" src="https://user-images.githubusercontent.com/13385119/194331875-cb2906d7-fb19-49e9-ad53-6d9362295b24.png">

**Comment by Rello** [comment]
oh wait. i found the issue. a fix was not commited.
I will push a bug fix release the next days. this will then be included

**Comment by paspil** [comment]
It works now. Thank you very much!

**Comment by Rello** [comment]
did you commit the patch locally???

**Comment by paspil** [comment]
> did you commit the patch locally???

Yes, for testing.
