### ISSUE TITLE
double category labels

### ISSUE THREAD

**Issue by Emporea** [Rello/analytics#28]
Since you moved to Chart.js i am missing some documentation guides.
With Highchart it was possible to have a csv like this to have multiple graphes

> Name,Date,Amount
testname,2020-02-14,108
testname,2020-02-15,68
testname,2020-02-16,60
testname,2020-02-17,96
testname,2020-02-18,103
differentchart,2020-02-14,53
differentchart,2020-02-15,30
differentchart,2020-02-16,22
differentchart,2020-02-17,40
differentchart,2020-02-18,42

Now such file looks like this since the migration to chart.js.
![image](https://user-images.githubusercontent.com/21969523/76514288-f85d0700-6457-11ea-82c5-5633ee3b8cf7.png)

Whats the correct way of using chart.js features trough a csv file? Are there even all features available, like horizontal bars or different point styles?

**Comment by Rello** [comment]
Hello,
thats strange. i wonder where the empty lines are coming from.
its a timeline chart?

can you please drop me the file for analysis here:
https://home.scherello.de/owncloud/s/riTNoMMrpPxNjHW

**Comment by Emporea** [comment]
So the time bug resolved by using the time chart. But this doesnt solve the problem. I have just uploaded a file which does the same and duplicates the x axis.

**Comment by Rello** [comment]
got it. will check tonight. I think I can see the problem

**Comment by Emporea** [comment]
Thank you. Should i open another issue for a feature request, that allows for more use of chart.js like doughnuts and so on? Or is it unneccesary because its not in your planning right now.

**Comment by Rello** [comment]
on the roadmap already. just had to bring the "as-is" out as quick as possible

**Comment by Rello** [comment]
Hello,
I found the issue. when doing a non-time-chart, the categories (X-axis) need to be the same for all datasets (which it is for your example). 
But the error is adding the categories of every dataset on top - so double.
will send a fix

**Comment by Rello** [comment]
![Screenshot 2020-03-12 at 21 11 50](https://user-images.githubusercontent.com/13385119/76562640-18b3b280-64a6-11ea-92db-5b3a8404fb9e.png)

**Comment by Emporea** [comment]
So I just updated to 2.1.1. but cant see any difference. I dont know if I understood your answer correctly, do I have to change anything to the csv i uploaded to your nextcloud?

**Comment by Rello** [comment]
I hope it helps already. The axis texts will be next...

**Comment by Emporea** [comment]
I really like the Analytics app. It is very good and so useful. Keep up the good work!

Thank your for this quick fix to 2.1.1
