### ISSUE TITLE
Feature Request: If right settings window is open allow to change X/Y/Line/Bar on table

### ISSUE THREAD

**Issue by Mannshoch** [Rello/analytics#281]
At momen tI have to acitvely design  the Datasource in wa way so Analytics is able to understand the Values.
If the settings is open add a Dropdown menu over the title on every column which allows to chang which diagram element it represent.

If I have:
`Title, Year, Value `

Ontop of this Table on every column-subject there should be a burgermenu which dropdown and allow to setup what data it is:

```
Line, X, Y
Title, Year, Value
```

That way I do not have to change the CSV. An I'm also able to use one CSV for several diagrams.

**Comment by Mannshoch** [comment]
In a way yes. It's not easy to get how it works. I'm strugelin now a bit wit the contentype of the column. But for that case I found a Wiki entry.

**Comment by Rello** [comment]
Hi,
I am subsequently working on adding more and more user information and guidance to the app.
there are more features in than visible at the first sight :-)

**Comment by Mannshoch** [comment]
Thank you very much for your Work. 💪👍
