### ISSUE TITLE
Icons for share users too big

### ISSUE THREAD

**Issue by fthommen** [Rello/analytics#282]
When I share an analytics report, the icon of the user which I share it with, is shown too big a) in the selection dropdown and b) in the final list.  This is new since a recent update from NC from 21.0.9 -> 24.0.1 and update of the Analytics app.

See the example below:

![analytics_4 3 0_shareuser_icon_too_big](https://user-images.githubusercontent.com/279232/174561438-c36ec26b-8f2e-471f-9ffa-dfe48e4a62dc.png)

The user (group) marked "W" was in the share list _before_ the updates, while the user marked "T" is a new share user since _after_ the updates.

Nextcloud version is 24.0.1, the Analytics app is in version 4.3.0

**Comment by Rello** [comment]
thank you. did not find this one in the tests. I will check
