### ISSUE TITLE
Shared report not shown

### ISSUE THREAD

**Issue by fthommen** [Rello/analytics#283]
Hi,

since a recent update of Nextcloud from 21.0.9 to 24.0.1 and of the Analytics app to 4.3.0, shared reports are not seen by the shared-to users any more. Unfortunately I cannot say much more than "it doesn't work any more" :-).  Please let me know if I you need any further data/information

**Comment by Rello** [comment]
Hello,
I will check. I have a lot of automated tests, but this one is not yet covered.
I will have a look
