### ISSUE TITLE
Usernames shown as IDs instead of readable names

### ISSUE THREAD

**Issue by fthommen** [Rello/analytics#286]
Hi,

thanks for solving the latest issues.  Great work!

Unfortunately I got one more which is not new, but I realized it only now: In the sharing list, users from AD (Active Directory/LDAP) are not listed with their name but with some AD ID:
![Sharing_Analytics](https://user-images.githubusercontent.com/279232/176006927-7c2b3d9f-d548-466f-a0ba-54883e0b94ae.png)

Compare to the share list of a file:
![Sharing_Files](https://user-images.githubusercontent.com/279232/176006980-7649668b-4ccc-4fa5-95e3-7f48ab2ce81a.png)

Interestingly **group** names are printed as names and not as IDs

**Comment by Rello** [comment]
AD Setup!?
puh. need to have a look how to debug this

**Comment by fthommen** [comment]
:-).  From our side it would of course be nice to have this fixed, but it's also not a _huge_ problem.  So from my side it can have a low prio

**Comment by Rello** [comment]
@fthommen send it to `analytics at scherello . de`

**Comment by fthommen** [comment]
I apologize, I completely for forgot this and was also away in the meantime.  This is probably/hopefully what you are looking for:

![Screenshot 2022-07-15 at 19 27 17](https://user-images.githubusercontent.com/279232/179278715-e48f7e74-9277-4e37-b99d-ee336406c3ae.png)

A = Name
B = AD ID
C = Email address

**Comment by Rello** [comment]
Hi,
I finally found it. the information above was looking at the search. 
Is my assumption correct, that the real names are shown when you search for an employee to share with?
Its just shown wrong once the member is part of the share-list. this is how I could just reproduce it...

**Comment by Rello** [comment]
solved with the next release...

**Comment by fthommen** [comment]
Great (as usual). Thanks in advance
