### ISSUE TITLE
Fifth and later series is always disabled by default in the graph

### ISSUE THREAD

**Issue by fthommen** [Rello/analytics#287]
Hi,

it looks as if in the graphs by default only the first four series are shown and all others are disabled.  This is a little bit annoying, as we have quite some graphs with 5-10 series where we always need to see all of them.  After each opening of the graphs we have to manually enable all hidden series with individual clicks....

Is this configurable somewhere?  By graph or globally?  I could find an appropriate setting.

**Comment by Rello** [comment]
Hello,
with the latest update the feature was introduced, that when enabling >5, the setting can be saved (orange icon right top corner). this still requires initial selection of what you want to see - but at least only once.

does this help?

**Comment by fthommen** [comment]
Great && thanks a lot. The icon is so lightly colored and "diskret" that I hadn't even noticed it :-).  I can't stop being impressed about this app and your reactivity to requests.  Kudos!
