### ISSUE TITLE
Display series are persistently listed in the legend even if not present

### ISSUE THREAD

**Issue by fthommen** [Rello/analytics#288]
When displaying analysis data (e.g. trends), selecting them for display and saving the state, then these series are persistently listed in the legend, but as "undefined, after a refresh of the report, as the state doesn't also include analysis results. Please see this screencast as a better description:

https://user-images.githubusercontent.com/279232/176128710-9b157c54-7db3-4d42-a917-73c4d36070d0.mov

**Comment by Rello** [comment]
Hi,
good finding. the visibility settings are persisted per data series. some cleanup is missing in case the number of data series differs...

**Comment by Rello** [comment]
sorry for the delay. picking it up finally...
