### ISSUE TITLE
Data Analytics Flow errors

### ISSUE THREAD

**Issue by Rello** [Rello/analytics#29]
@juliushaertl @blizzz

I need your support again. I am seeing several logs related to the workflowengine and my app:

```
[workflowengine] Debug: Cannot handle event \OCP\Files::postWrite of Symfony\Component\EventDispatcher\GenericEvent against entity OCA\WorkflowEngine\Entity\File and operation OCA\Analytics\Flow\Operation

[no app in context] Debug: Deprecated event type for \OCP\Files::postWrite: Symfony\Component\EventDispatcher\GenericEvent

```
regarding the first one: am I still using the right generic Event?
https://github.com/Rello/analytics/blob/master/lib/Flow/Operation.php#L28

```
[workflowengine] Debug: Flow activation: rules were requested for operation Data Analytics

[workflowengine] Debug: No flow configurations is going to run Data Analytics

[PHP] Error: Undefined index: operation at /mnt/analytics/lib/Flow/Operation.php#97

```

the 3 last seem strange. if I understand correctly, workflow determines that DA is not relevant (I setup a rule for post-write and file name, but the file name was not matched).
But why is my `onEvent` Operation still being accessed afterwards?
https://github.com/Rello/analytics/blob/master/lib/Flow/Operation.php#L97

thank you!

**Comment by Rello** [comment]
@juliushaertl @blizzz
anyone, please?

**Comment by Rello** [comment]
@juliushaertl @blizzz
anyone, please?

**Comment by blizzz** [comment]
Hey @Rello, sorry for the delay. 

> regarding the first one: am I still using the right generic Event?

Nothing has changed within the 18 cycle.

> the 3 last seem strange. if I understand correctly, workflow determines that DA is not relevant (I setup a rule for post-write and file name, but the file name was not matched).
But why is my onEvent Operation still being accessed afterwards?

The flow.log is more talkative, perhaps it contains more info?
