### ISSUE TITLE
Chart.js Advanced Chart Options

### ISSUE THREAD

**Issue by jkannik** [Rello/analytics#290]
Hi,
I have a sensor which writes data to a csv file. I can add it to Analytics and it works.
I used the example from the Wiki for the unix timestamp, this works. Can I somehow make it so that it automatically rearranges or can I set the intervals in days or weeks? 

Unfortunaly I don't understand how I can put in other options, I googled a lot but everything I try gives me a error.

Thanks

**Comment by Rello** [comment]
Hello,
I need more input what you need. grouping in the chart that not the timestamps but the weeks are shown?

from the wiki:
```
change the x-axis to write months and not days 
{"scales": {"xAxes": {"time": {"unit" : "month"}}}}
```

**Comment by PVince81** [comment]
@jkannik see https://github.com/Rello/analytics/issues/321 for using values like "%today%" with Unix timestamp, there's a workaround there
