### ISSUE TITLE
[question] Is there a way to Read / Datasource from Prometheus ?

### ISSUE THREAD

**Issue by erik78se** [Rello/analytics#291]
Is there an easy way to add a prometheus datasource?

I'd love to make use of this since I collect alot of data using prometheus.

Here are some docs from prometheus: https://prometheus.io/docs/prometheus/latest/querying/basics/

**Comment by Rello** [comment]
Hello,
there is a simple API available. could be interesting to look at. 
I don´t have a prometheus and its not the highest prio. but perhaps this would even work with a json datasource for some simple selections? did you try?

for a better integration, a real datasource-type would be required.
I will add a backlog to the analytics_sources packages. this will be published later as a dedicated app for specialized datasources

**Comment by Rello** [comment]
closing here for now....

**Comment by Rello** [comment]
https://github.com/Rello/analytics_sourcepack/issues/3
