### ISSUE TITLE
Navigation drag & drop

### ISSUE THREAD

**Issue by JosephChataignon** [Rello/analytics#292]
Currently it seems that the only way to create a folder is by clicking the "+" button in any report's settings. It is not very intuitive. As most of the interaction with folders happen in the left sidebar, it would be better to have a "new folder" button there, next to the "new report" button.

Also, that's less important but it would be great to be able to reorganize folders and report by drag-and-drop in that sidebar.

**Comment by JosephChataignon** [comment]
Also, all the folders get minimized when the page is reloaded

**Comment by Rello** [comment]
Hello,
was planned since longer already. I will implement drag&drop with the next version

**Comment by Rello** [comment]
@JosephChataignon 
@lucentwolf

can you have a look at this video what you think? I added more options to create report groups + drag&drop. what do you think?

![animated](https://user-images.githubusercontent.com/13385119/186751660-2b556ed5-4492-404b-bf61-52607dd774fe.gif)

**Comment by JosephChataignon** [comment]
@Rello it looks really good overall ! 
From the video, it is unclear whether clicking the small triangle toggles the expand/collapse action (it should). Also, it looks like drag&dropping an element out of the folder resets the folder to collapsed state, it would be better not to change the collapse/expand state unless the user explicitly clicks it.

**Comment by Rello** [comment]
yes. minor UI details. in the video i noticed the issue with the triangle
