### ISSUE TITLE
Notification issue for occ dataload

### ISSUE THREAD

**Issue by sirdrakeistda** [Rello/analytics#294]
Steps to produce:
Create Datasource:
- Type: Github
- username: bigbluebotton
- Repository: bigbluebutton
- limit: 1
- Date: false
- delete data: true

Testrun in frontend works and gives following expected output:
```
[["v2.6.0-alpha.2",0]]
```

But if I try to update the data from the terminal with following command:
```
sudo -u www-data php /var/www/nextcloud/occ analytics:load 25
```
I get following output:
```
An unhandled exception has been thrown:
TypeError: Argument 1 passed to OC\Notification\Notification::setUser() must be of the type string, null given, called in /var/www/nextcloud/apps/analytics/lib/Notification/NotificationManager.php on line 47 and defined in /var/www/nextcloud/lib/private/Notification/Notification.php:154
Stack trace:
#0 /var/www/nextcloud/apps/analytics/lib/Notification/NotificationManager.php(47): OC\Notification\Notification->setUser()
#1 /var/www/nextcloud/apps/analytics/lib/Service/ThresholdService.php(109): OCA\Analytics\Notification\NotificationManager->triggerNotification()
#2 /var/www/nextcloud/apps/analytics/lib/Service/StorageService.php(127): OCA\Analytics\Service\ThresholdService->validate()
#3 /var/www/nextcloud/apps/analytics/lib/Service/DataloadService.php(170): OCA\Analytics\Service\StorageService->update()
#4 /var/www/nextcloud/apps/analytics/lib/Command/Load.php(48): OCA\Analytics\Service\DataloadService->execute()
#5 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Analytics\Command\Load->execute()
#6 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#7 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#8 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#9 /var/www/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#10 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#11 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
```

Other non github datasources work without any problem.

**Comment by Rello** [comment]
Hi,

this is no issue regarding github - its an issue with the notification.
It looks like that on one of the reports for this dataset, you set a treshold with the type "notification". can you check?

I will look at the issue - but removing this, will make your dataload work for now.
<img width="324" alt="Bildschirmfoto 2022-08-17 um 21 11 55" src="https://user-images.githubusercontent.com/13385119/185223466-d0ed8626-09cf-4bb4-bc27-69edee9fef85.png">

**Comment by sirdrakeistda** [comment]
![Bildschirmfoto vom 2022-08-17 21-20-19](https://user-images.githubusercontent.com/35723909/185224801-9e96f512-12fc-4147-96df-c21612cc6edc.png)
There is a rule, but I would expect that unequal would work also with strings (it worked in the past). I just want to get a notification when there is a new item in the dataload. I haven't found a better solution then giving a notification like this (maybe it would be good to implement it).

**Comment by Rello** [comment]
Hi,
with your notification you would get a message every time new data is loaded. is this the plan?
If I understand correctly, thats not the case. you want to get an alert if a new record is added (like a new version in the downloads) and NOT when just an existing one is updated with a higher number?

...in any case, the notification still has a technical bug...

**Comment by sirdrakeistda** [comment]
No this is not the plan. I haven't found a option to notify only for new version. So this was more like a workaround (obviously not a really good one). Should I open a feature request? Thanks for looking at this issue.

**Comment by Rello** [comment]
problem for the technical error is solved (with the next version coming soon)
