### ISSUE TITLE
Add Deck Integration

### ISSUE THREAD

**Issue by camurcadolinux** [Rello/analytics#295]
Add Deck Dashboards as a Reporting Data Source.

**Comment by camurcadolinux** [comment]
the deck app allows you to attach users to cards. My wish is for there to be a way to generate a graph with the productivity of each employee, showing how many cards he was marked on, and dividing by list.

**Comment by Rello** [comment]
ok, interesting. should not be a big deal.
can you verify with more details what you want to report?

like e.g. in a chart/table, which columns/numbers?
this makes it easier to understand the request

**Comment by camurcadolinux** [comment]
I need a bar graph essentially. The data I want is the assigned users, tags and step.
