### ISSUE TITLE
New notification type: "new record"

### ISSUE THREAD

**Issue by Rello** [Rello/analytics#297]
...I haven't found a option to notify only for new version...

_Originally posted by @sirdrakeistda in https://github.com/Rello/analytics/issues/294#issuecomment-1218509511_

**Comment by Rello** [comment]
@sirdrakeistda
regarding your request for getting a notification for new records. Technically I have all data I need in the backend.
But I have no real idea for the UI

this is the current setup:
![Bildschirmfoto 2022-08-30 um 23 12 53](https://user-images.githubusercontent.com/13385119/187544206-13e1eb9e-9821-4f2b-9fbc-6213efba02f6.png)

How to integrate this in a meaningful way?
would this be a new option in the dropdown like "new record"? I think thats the best way to put it in. but somehow it does not feel perfect.

any suggestion by you?

**Comment by sirdrakeistda** [comment]
I think an extra checkbox would be better. Maybe name it "only notify for new record". In this menu it would be possible to use operators and to notify only one time for every data point options together.


Am 30. August 2022 21:16:10 GMT+00:00 schrieb Rello ***@***.***>:

**Comment by Rello** [comment]
I went for this option now, as it is simpler to integrate without doing and database adjustments.
![Bildschirmfoto 2022-09-12 um 15 35 48](https://user-images.githubusercontent.com/13385119/189668254-d624b67a-ebdc-4b4d-b239-d4f5b119de32.png)

not perfect, but has to be ok for now

https://github.com/Rello/analytics/wiki/Thresholds
