### ISSUE TITLE
Structure of Controller & Services

### ISSUE THREAD

**Issue by Rello** [Rello/analytics#3]
Hello @nickvergessen

an I ask for your recommendation here:

I am trying to use the controller/service setup as recommended. But for keeping the app-structure similar to its modular setup, I am not sure what the recommendation is:

![Screenshot 2019-11-20 at 18 47 06](https://user-images.githubusercontent.com/13385119/69263854-6a1df600-0bc6-11ea-8d58-60eda48e8c69.png)

I want to implement an ApiDataController to enable REST/CORS. Generally, it would be a controller in the /Controller folder
But in Analytics context its a datasource - so I would like to group all of them in a /lib/Datasource folder

- does this make sense? is it best practise?
- would this still work with the route-setup?
```
'name' => 'apiservice#addData',
'url' => '/api/1.0/adddata/{datasetId}',
```

what is your idea on this?

**Comment by nickvergessen** [comment]
Well, Controllers have to be in the controllers folder.  I also find this unpleasing from time to time, but that's just how it is right now.
But you could just have a Service for the very same thing, and (that is actually what it should be like) the controller just forwards all data after a generic verification to the service.
This allows you to have a dump controller in the controller folder and all the data resource handling in the Datasource folder.

**Comment by Rello** [comment]
thank you
i went via the ApiController now...
