### ISSUE TITLE
Advanced chart options (e.g. timeline segments)

### ISSUE THREAD

**Issue by Emporea** [Rello/analytics#30]
Hey there again .. :),

Apparently when I have less than 22 rows to be shown in a timeline chart the date changes to this weird 12AM, 4AM, 2AM format instead of the well formated date like Feb 20. Btw the csv file obviously doesn't change and the second column is 2020-02-20 for example.  Bug or Feature? 💃 

The expected one ( or when i have above 21 rows in a csv ):
<img width="1124" alt="Annotation 2020-03-12 221007" src="https://user-images.githubusercontent.com/21969523/76567447-0d18b980-64af-11ea-911f-75fe60c98b93.png">

The weird time formatted one ( below 22 rows in csv):
<img width="1115" alt="Annotation 2020-03-12 221007_wrong" src="https://user-images.githubusercontent.com/21969523/76567546-43563900-64af-11ea-9663-9c80c4abb62f.png">

**Comment by Rello** [comment]
Yes
Still finding out how to limit the axis display. Highcharts was better here to offer a cleaner UI

**Comment by Rello** [comment]
Hello,
thats how chartjs works. it has some internal algo to determine the best number of selectors.
there is a config option but it can not be set in general because it also has bad effect on others.

I am working on an option to include chart-specific parameters on report level so the user can optimise standard settings based on the personal needs. this will cover this part

**Comment by Rello** [comment]
Advanced chart options can be entered in a new field
![Screenshot 2020-04-01 at 23 19 47](https://user-images.githubusercontent.com/13385119/78187847-7cab1480-746f-11ea-8cd1-99fdba7df51f.png)

The format needs to match the chartjs api. e.g.:
https://www.chartjs.org/docs/latest/axes/cartesian/time.html

The example value for the issue mentioned above - fixing the scale to day would be:
`{"scales": {"xAxes": [{"time": {"unit" : "day"}}]}}`
