### ISSUE TITLE
Simplify "New record" notification maintenance

### ISSUE THREAD

**Issue by sirdrakeistda** [Rello/analytics#303]
Actual behavior:
When adding a notification for new record, I'm forced to add a value. This value is never used, so it is confusing.

Solution:
Allow also empty values if 'new record' is used.

Additional question:
If I understand correctly the notification appears on every dataload (if the condition is fullfilled). Would it be also possible to notify only if the data changed since the last dataload? (I'm unsure how new records is implemented. Will it notify if a new entry is added or also if data changes? At the moment I'm missing an option to notify only after data changed and if a condition is full filled (interesting for e.g. Covid data, to notify only if new data is availeable and value is above certain value)).

**Comment by Rello** [comment]
Hello,

thank you for the feedback. indeed, the current setup is too confusing.
I separated this new check into a new section/button. what do you think?

![Bildschirmfoto 2022-10-30 um 19 46 24](https://user-images.githubusercontent.com/13385119/198896083-2e005c19-bb19-4c56-90cb-d2920204ec1c.png)

For the new: for technical reasons (without adapting the threshold backend including tables), "`new record`" does only check for any new record. the other checks for updated+new

**Comment by sirdrakeistda** [comment]
It's good to separate them. In the future it would be nice to filter new records, but for now it's a good solution. Thank you for your great work.
