### ISSUE TITLE
Multiple columns not rendering for me on graph

### ISSUE THREAD

**Issue by BiglifeMatt** [Rello/analytics#304]
I have a basic csv.  The first column is a list of Years and then I have two category columns with numbers to track per Year.  If I only select the first two columns, I get the expected results in a graph.  I add the third column expecting a secondary line on my area graph but then the second column wants to be the x axis and there isn't any clear data presented.  Not sure if I need to use the Data Options and/or Chart Options to address this.  I cannot find examples of how to use the Data Options fields as well.

**Comment by Rello** [comment]
Hello,
yes, the current setup is expecting different data series in the rows (not in 2 keyfigure columns). This is how the internal datastore is working and the chart.js was configured to work with this setup.

but for external data your request is valid.
I need to look at it how this can be achieved in a flexible way.
I will leave this request open

**Comment by Janokisu** [comment]
Currently everything is handled according to the scheme
```
|----------------------|
| Name | Time  | Value |
|----------------------|
| a    | 14:00 | 45    |
|----------------------|
| b    | 14:00 | 20    |
|----------------------|
| a    | 14:01 | 47    |
|----------------------|
| b    | 14:01 | 18    |
```


Scheme like this is currently not possible
```
|------------------------------------------|
| Time  | a  | b  | c  | d  | f  | g  | h  |
|------------------------------------------|
| 14:00 | 12 | 67 | 34 | 12 | 1  | 4  | 5  |
|------------------------------------------|
| 14:01 | 13 | 50 | 12 | 54 | 2  | 2  | 7  |
|------------------------------------------|
```

maybe a workaround would be to convert this schema to the default schema with for loop during import
i = row
j = column

`| column[0][j] | column[i][0] | column[i][j] |`


or for free configuration, in which column the time is located

`| column[0][j] | column[i][x] | column[i][j] |`

**Comment by Rello** [comment]
I know what you mean.
the only workaround I have at the moment is to use separate datasources and select the desired column for the reporting. the text will be used a a constant

1. a,0,1
2. b,0,2
3. ...

then you could either do one realtime report per name, or if you want to combine them, you could use several datasources and load them regularly into one dataset.

both not perfect at all - but a workaround

**Comment by Janokisu** [comment]
Do you mean this?
https://github.com/Rello/analytics/wiki/Automation-(load-&-delete)

Yes, it works. Not perfect at all, but works
