### ISSUE TITLE
Export data to file

### ISSUE THREAD

**Issue by hirehamva** [Rello/analytics#310]
Hy, It would be nice an export accumulated data to file function. Not an issue, just a suggestion.

**Comment by Rello** [comment]
Hi,
you mean you use Analytics to aggregate data in the report and this dataset (e.g. on monthly data vs daily) you would like to export?

**Comment by hirehamva** [comment]
Yes, I woud like to export data to a csv file. Like a database table.

**Comment by hirehamva** [comment]
Thank you very much for the export option.

**Comment by Rello** [comment]
Hello,
I am not sure here. is the existing export function working for you here already?
Alternatively there is the API also available. An export of the data itself is currently not in focus

**Comment by hirehamva** [comment]
Hello,
Yes the export function is working. Thank you again.
