### ISSUE TITLE
recognize dates in spreadsheet data source

### ISSUE THREAD

**Issue by kevinkuan1969** [Rello/analytics#311]
Hi,

Just started to explore the functionalities of Nextcloud Analytics and would like some advice on how to define informat setting so that the system can understand the right format from the source file such as dd-mm-yyy, yyyyy-mm-dd and etc. 

Here the sample of source file in excel format:

SEGMENT    SHIP DATE       SALES 
Consumer    2020-11-11     261.96
Consumer    2020-12-12     234.00
Consumer    2020-1-10       987.87

After loaded and display in the table, the date values seem to be wrong and different from the source 
SEGMENT    SHIP DATE       SALES 
Consumer    43107    261.96
Consumer    43109    234.00
Consumer    43209    987.87

Your help is very much appreciated. Thanks.

Regards,
Kevin

**Comment by Rello** [comment]
Hello,
the problem is, that what you see in excel is not what is actually in the cell. if you switch the cell display in excel to "number/Text", you will see this number.
I solved this on my side previously already. need so search for it....

**Comment by kevinkuan1969** [comment]
Thanks Rello. 
Even have tried to convert the values supported format in Excel manually, but it did not work.
Based on my experience in other BI tools, we can use the 'informat' to teach the system how to read it to ensure it is supported by the BI system.

**Comment by Rello** [comment]
Hi,
just do update here: I modified the spreadsheet datasource to take care of this.
it will recognize a date field and convert this magic running number (days since 1990) to a usable date format...
