### ISSUE TITLE
Sharing of groups should not be possible

### ISSUE THREAD

**Issue by lherbolt** [Rello/analytics#313]
Sharing group report to other users does not work. When opening the report from user being shared to we get "Call to a member function readData() on null" error. Users are coming from LDAP.  Sharing of report works normally. So it looks like just groups of reports 
cannot be shared.

**Comment by Rello** [comment]
Hello,
thank you for the report. that is correct. for technical reasons, groups can not (yet?) be shared. its an error, that the tab is shown there.
will be corrected
