### ISSUE TITLE
Text variables for API

### ISSUE THREAD

**Issue by Rello** [Rello/analytics#314]
question: is it possible to have the timestamp be generated by PHP itself ? ex: passing a value "$timestamp" to tell the app to replace it with the current timestamp

the challenge I have is that the ESP has no time info and I don't want to ping NTP frequently before sending measurements.

**Comment by PVince81** [comment]
note: in our chat you had suggested that it might be possible to enable some already existing variables like "%today%" which might be suitable

**Comment by Rello** [comment]
what do actually need? unix-timestamp? or formatted date/time-string?

**Comment by Rello** [comment]
manual data load:
![Bildschirmfoto 2022-10-28 um 20 11 37](https://user-images.githubusercontent.com/13385119/198704265-dc2a279b-b673-4c50-ae4a-f706f6b46108.png)

API:
`curl -u xxx:xxx -d '{"data":[{"dimension1": "%currentDate%", "dimension2": "%now%", "value": "2"}]}' -X POST -H "Content-Type: application/json" https://nc25//nextcloud/apps/analytics/api/3.0/data/18/add --insecure`
![Bildschirmfoto 2022-10-28 um 20 17 24](https://user-images.githubusercontent.com/13385119/198705135-5b5cb4a8-7f1e-4ccf-a8f7-97b3876ea4e6.png)
