### ISSUE TITLE
Schedule deletion jobs per dataset to clean up old data

### ISSUE THREAD

**Issue by guyou** [Rello/analytics#316]
I'm using analytics to store timebased data, provided by a IoT. I few weeks, the oldest data will need to be deleted.
Is it possible to add a way to delete data before (or after) a given data?

**Comment by Rello** [comment]
Hi,
this is currently not possible in an automated way.

within the data maintenance of the report/dataset (the screen where you can manually add data), you can also delete data. if you combine this with wildcards, you can cleanup old data manually (e.g. in the time field, enter '2021*').
Does this work for the moment?

**Comment by guyou** [comment]
> within the data maintenance of the report/dataset (the screen where you can manually add data), you can also delete data. if you combine this with wildcards, you can cleanup old data manually (e.g. in the time field, enter '2021*').
> Does this work for the moment?

Oh yes, it works! Great feature. Clearly enough currently for me. Perhaps should it be explained in documentation.
If needed, I will add a cron based job to clean data monthly.

**Comment by Rello** [comment]
@guyou 
a flexible data deletion was added to the automation section.
please have a look here. I assume this is what you need?
https://github.com/Rello/analytics/wiki/Automation-(load-&-delete)
