### ISSUE TITLE
Missing dataset id in example API call

### ISSUE THREAD

**Issue by PVince81** [Rello/analytics#317]
### Steps

1. Create a new report of type timeline with defaults
2. Edit the report's dataset
3. Click on the clipboard button under "API" to get the target path

### Expected result
Target path contains dataset id

### Actual result
Dataset id is undefined

<img width="690" alt="image" src="https://user-images.githubusercontent.com/277525/201775399-8fbe8383-6d5b-488f-bbb4-8d1f65c8db44.png">

### Version
Nextcloud 24.0.7
Analytics app 4.5.0

**Comment by Rello** [comment]
Thank you Vincent.
the link is correct when you are in the report - the error is on the section of the dataset maintenance. did not see that one

will take care.
thank you
