### ISSUE TITLE
[API] Get data by range (time series)

### ISSUE THREAD

**Issue by PVince81** [Rello/analytics#318]
Currently using the v3 data get API, one always receives all results as JSON.
In the case of IoT measurements spanning over multiple days, months, it can be a lot of data.

It would be good to extend the API as follows
- endpoint to query "number of values"
    - ex: `GET /nextcloud/apps/analytics/api/3.0/data/{reportId}/count` => `{count: 123}`
- allow to read one single value by index (would make it possible to retrieve only the last value):
    - ex: `GET /nextcloud/apps/analytics/api/3.0/data/{reportId}?index={index}`
- allow read a range of values: from index A to index B
    - ex: `GET /nextcloud/apps/analytics/api/3.0/data/{reportId}?rangestart={index1}&rangeend={index2}`

Now, specifically for time series, the second dimension contains time, so the above could be extended:
- allow to read a range of values with specified start time and end time. If one is omitted it's open-ended
    - ex: `GET /nextcloud/apps/analytics/api/3.0/data/{reportId}?rangetimestart={time1}&rangetimeend={time2}`
    - or: `GET /nextcloud/apps/analytics/api/3.0/data/{reportId}?dimesion2rangestart={time1}&dimension2rangeend={time2}`

For the analytics UI, it means the following:
- makes it possible to only retrieve data points that are visible in the current chart (ex: drill down)
- improve performance when reading data as not everything would be read but only the currently viewed range

**Comment by PVince81** [comment]
also, negative values like "rangestart=-10" could mean "the last 10 values" which would be convenient as well and would save a trip to the proposed "/count" endpoint

**Comment by Rello** [comment]
Hi,

this is a challenging request. currently the API reads data the same way a report does. all filters applied to a report are also applied to getData. its basically getting the same information.

but you now want to use the Analytics data store also for flexible external queries. 
I can have a look if there is a way to implement it

**Comment by PVince81** [comment]
before going into the use case "ability to query specific data", it might be more important to cover the scalability use case "display a chart with lots of data point, on mobile".

In my test use case, I have temperature data measured every minute. Maybe it's too much I agree, I should measure less frequently. Still, after several days it's a lot of data points.
So if I were to view the chat on a mobile network, it will use increasingly more data over time.

Hence the request to have at least a data range request, and that one should also be used by the UI when rendering the charts. Like only fetch the last X values (100?), not all of them. And with time series it could be the last day or so.
Still, the default might depend on the use case.

I understand that it's challenging, especially considering that a lot of data is rather generic, even the timestamps as value. So it's difficult to come up with a generic solution for partial chart data fetching that would cover all the cases.

**Comment by PVince81** [comment]
to illustrate my case, this is what I had so far:
<img width="456" alt="image" src="https://user-images.githubusercontent.com/277525/202756386-eadc0f85-9711-4150-a925-8cd56cf7d5e2.png">

this is the temperature in my home office as I'm trying to save heating costs :smile: 

It was interesting to see how opening the window or being absent would affect the room temperature. Some of the dips were when I opened the window for ~5 minutes. I couldn't have captured those with a lower time resolution.

**Comment by Rello** [comment]
Hi,
I am not sure if I understand it correctly. you want to restrict the data shown. did you try the filter already?
dynamic text variable were introduced a while ago.
e.g. I am monitoring bluetooth moisture sensors since over a year - but just reporting 1 month

![Bildschirmfoto 2022-11-18 um 21 19 51](https://user-images.githubusercontent.com/13385119/202795354-a0aba16b-d67a-4617-aa83-56b37e809c46.png)
once you filter and press the yellow save button next to the "...", this will be peristed

**Comment by PVince81** [comment]
@Rello alright, thanks for pointing at the filter. I missed it because in my use case I have an unprivileged separate user to gather data and that user shares the report with my own user. Apparently when sharing, even with "can navigate", there is no filter button for the target user. I can report this separately.

so regarding the usage of "get data by range" it is for me mostly reduced to "query the very last value" so that I can show it elsewhere. but it was just a wild idea.

if the charts can already scale (and reduce data usage) using filtered reports, then this feature request might not be important/valid any more, I'm fine if you decide to close it

note: it seems "%today%" is not working, I'll raise separately

**Comment by PVince81** [comment]
raised https://github.com/Rello/analytics/issues/321 for the filtering issues

**Comment by Rello** [comment]
Hello,
can you come back regarding the shared report filter?
i tested again in nc24/nc25. its working for me. "can navigate" will show the filter icon top right

**Comment by Rello** [comment]
regarding the original request here, I would keep it with the existing setup: filter something in a report and use this as a basis for extraction. this is much simpler than enabling the API to do similar things

**Comment by PVince81** [comment]
> Hello, can you come back regarding the shared report filter? i tested again in nc24/nc25. its working for me. "can navigate" will show the filter icon top right

Let's continue here so we don't mix up topic: [TODO](https://github.com/Rello/analytics/issues/324)

**Comment by PVince81** [comment]
I believe we have adressed all the topics and could close this as won't fix ?

**Comment by Rello** [comment]
I think so. api on an existing report should be the first way to go
