### ISSUE TITLE
No data received on JSON

### ISSUE THREAD

**Issue by hirehamva** [Rello/analytics#319]
Everithing was working fine until 2022.11.16 12:00. Updated the app. I have a year of temperature data accumulated. Data is recived, but not written to database.
![Képernyőkép 2022-11-18 140726](https://user-images.githubusercontent.com/66569812/202713375-c9990ec2-595c-4ab0-b15d-24c454e53d56.png)
![Képernyőkép 2022-11-18 140627](https://user-images.githubusercontent.com/66569812/202713662-50deab4f-22ab-499e-a33c-489c4c4a8778.jpg)

**Comment by Rello** [comment]
Hi,
I found the issue. somehow it was overlooked during the  automated tests.
will release the fix on short notice

**Comment by hirehamva** [comment]
Now it works. Tanks for the fast repair.

**Comment by Rello** [comment]
Hi,
thanks for letting me know.
i will include a feature to notify in case of data load errors via a notification in the future
