### ISSUE TITLE
Error 9002 from API

### ISSUE THREAD

**Issue by berho** [Rello/analytics#32]
I want to POST data to the internal database with the following command but get an error message! Can you tell me what I am doing wrong?

`curl -v -H Content-Type:application/json -u user:supersecretepassword -X POST -d {"dimension1":"Temperature","dimension2":2020-03-24T15:57:32.000Z,"dimension3":48} https://myserver.dom/index.php/apps/analytics/api/1.0/adddata/4`

answer from server: `{"success":false,"error":{"code":9002,"message":"Dimension 1 required"}}`

Server: 18.0.2
DataAnalytics: 2.1.1

Regards

**Comment by Rello** [comment]
I will check...

**Comment by Rello** [comment]
Hey,
you forgot to escape the time. put it in " " and its working

**Comment by berho** [comment]
U r my hero!
Thank you :)
