### ISSUE TITLE
Can I monitor 3 servers?

### ISSUE THREAD

**Issue by PrzemekSkw** [Rello/analytics#320]
Hello, I have three devices in homelab. One of them have nextcloud installed.
All have dietpiOS (debian 11).  Is it possible to monitor all three servers with Analytics app from my nextcloud on one dashboard?

Regards.

**Comment by Rello** [comment]
Hello,
what is your expectation on the data you want to monitor.
Analytics can access different data sets via its data sources like csv, json, ...
Its a question of the API that you want to read. once an api is there, you can do a lot in Analytics then...

**Comment by PrzemekSkw** [comment]
Hi @Rello thanks for answer. I would like to monitor 3 servers with CPU, temperature, Memory, services, dockers, storages.
It is possible?

**Comment by Rello** [comment]
Hello,
analyitcs can not do any monitoring by it self. it can only collect data.
If this data is available in an API for example, we can look at it.
any details?
