### ISSUE TITLE
What is the name of the axis for chartOptions ?

### ISSUE THREAD

**Issue by PVince81** [Rello/analytics#323]
I have datasets like:
```
[["Temperature","1669207343","19.14"],["Temperature","1669207416","19.15"]]
```

and I'm trying to set the options for the y axis, I tried the following:
- `{"scales": {"xAxes": {"time": {"parser" : "X", "tooltipFormat":"YYYY-MM-DD HH:mm:ss"}}, "yAxes": {"min": -10, "max": 40}}}`
- `{"scales": {"xAxes": {"time": {"parser" : "X", "tooltipFormat":"YYYY-MM-DD HH:mm:ss"}}, "Temperature": {"min": -10, "max": 40}}}`

but it always appears as a new axis:
<img width="438" alt="image" src="https://user-images.githubusercontent.com/277525/203549749-beac6de0-8a7a-41ac-b406-8753e3ec3f8c.png">

the answer should probably be in https://github.com/Rello/analytics/wiki/Advanced-chart-options

bonus request: make the chartOptions a resizable textarea to make it easier to edit more options there

**Comment by Rello** [comment]
Hi,
chartJS is using "primary" and "secondary"

one helpfull hint for your advanced testing: in the console, you can access the chart object with all properties with  `OCA.Analytics.chartObject`

**Comment by PVince81** [comment]
perfect, "primary" works.

should this be added as a hint to the wiki ?
and/or the hint about the `OCA.Analytics.chartObject` ? (I don't have write access so can't contribute to the wiki)

**Comment by Rello** [comment]
added to the wiki...

**Comment by Rello** [comment]
> bonus request: make the chartOptions a resizable textarea to make it easier to edit more options there

Hi,
I changed to textarea.
Plus, I put all topics in collaps-able sections to minimize the layout when not in use

![Bildschirmfoto 2022-11-28 um 18 38 19](https://user-images.githubusercontent.com/13385119/204344312-7fb25f54-7aea-4570-9b6d-a07539a8b677.png)

**Comment by PVince81** [comment]
@Rello thanks a lot, you rock :smile:
