### ISSUE TITLE
No update permission when sharing to group

### ISSUE THREAD

**Issue by PVince81** [Rello/analytics#324]
### Steps

1. Create a report with a time series graph
2. In the basic settings share with a **group**
3. Click the three dots and allow navigating
4. Login as a user in the group
5. Open the report

### Expected resut
Filter icon appears

### Actual resut
Filter icon is missing

#### Sharer
<img width="569" alt="image" src="https://user-images.githubusercontent.com/277525/208091193-897d1be7-836e-4713-ab88-38ecf6ed7b46.png">

#### Recipient
<img width="427" alt="image" src="https://user-images.githubusercontent.com/277525/208091248-719e49c9-c91c-46bd-99fb-ff6185640d3b.png">

### Versions
Nextcloud 24.0.7.1
Analytics app 4.5.1

### Notes

- The navigation permission seems to work at least because I can select a range on the chart for zooming in.
- I tried recreating the share, but same result.
- Maybe what worked for you was a user share and not a group share ?

**Comment by Rello** [comment]
ah! thank you!
my automated testing was only covering the share-link.
user-share seems to be the issue here.
will check. thank you for the details

**Comment by Rello** [comment]
solved
will push the new version this weekend
