### ISSUE TITLE
JSON: read array data which is not on the first level

### ISSUE THREAD

**Issue by gloomytrousers** [Rello/analytics#326]
I'm trying to graph a dataset from https://api.carbonintensity.org.uk/regional/intensity/2022-12-31T14:00Z/fw48h/postcode/RG10

The data is inside an array `data/data` but the [JSON example 3](https://github.com/Rello/analytics/wiki/Filter,-chart-options-&-drilldown) assumes the array is at the top level, so I am unable to address the columns I want in the Object path.

I think  `{...}` syntax needs some way to specify the location of the array, rather than just defaulting to the top level - perhaps something like `data/data | {intensity, from, intensity/forecast}`.

Related to this, I haven't been able to test yet... is it possible to put `%...%` placeholders (like in [filters](https://github.com/Rello/analytics/wiki/Filter,-chart-options-&-drilldown#filter)) in URLs to insert date/times? Let me know if I should log an issue for that.

**Comment by Rello** [comment]
Hi,

I will have a look. I am always looking for real world use cases to make the app more advanced.
what is the expected output in terms of dimentions/values you are looking at?

**Comment by gloomytrousers** [comment]
Something like this, which I have achieved via `cron`, `wget` and `jq` pre-processing to a CSV file (that's inelegant!):
![Carbon intensity forecast](https://user-images.githubusercontent.com/17237854/210185153-3cb9757a-fc1d-4f01-8613-4e444b762568.png)

The date (x axis) is `data/data/*/from` and the value (y axis) is `data/data/*/intensity/forecast` in the url I gave.

**Comment by Rello** [comment]
Hi,
the solution is the combination of an absolute path to get to the array and then select the array values.
I enhanced the coding and the solution would be like this.
What do you think?

`data/data{forecast,to,intensity/forecast}`

![PNG-Bild](https://user-images.githubusercontent.com/13385119/210431586-fb37992d-50ee-44f1-9a4c-af0aab1e69b6.png)

**Comment by gloomytrousers** [comment]
Looks good to me :-)

**Comment by Rello** [comment]
This will be released with the next version.
Support is appreciated
https://github.com/rello/analytics/wiki/donate
