### ISSUE TITLE
Timestamp of dataloading is not set to JSON datasource

### ISSUE THREAD

**Issue by sowoi** [Rello/analytics#327]
I tried to recreate the example from the JSON wiki with my nextcloud instance. Timestamps are not created and the values are overwritten with every reload. 
This seems to be exactly the same problem as in [#106](https://github.com/Rello/analytics/issues/106)

**Comment by Rello** [comment]
Hello, 0106 is a real time report. no dataloading/automation.
can you send a screenshot for your settings?

**Comment by sowoi** [comment]
![Bildschirmfoto vom 2023-01-05 13-56-31](https://user-images.githubusercontent.com/10256263/210786392-763a26cd-da83-45ea-a57b-8fff70076de4.png)
![Bildschirmfoto vom 2023-01-05 13-56-44](https://user-images.githubusercontent.com/10256263/210786402-48276536-7057-4698-adba-ad70a5605541.png)
![Bildschirmfoto vom 2023-01-05 13-59-18](https://user-images.githubusercontent.com/10256263/210786412-7382d6f9-ba7a-4308-8226-146dbbb03e77.png)

**Comment by Rello** [comment]
ok. that is strange
let me check.

**Comment by Rello** [comment]
I just tried it. works for me as expected.
did you perhaps change the dropdown but not the save checkmark before doing the simulation?
the datasource always needs to be saved, before the change applies to the test run
![Bildschirm­foto 2023-01-05 um 20 22 43](https://user-images.githubusercontent.com/13385119/210863169-0e3f660f-c752-4d4a-9bd7-2e98f4e79f00.png)

![Bildschirm­foto 2023-01-05 um 20 22 16](https://user-images.githubusercontent.com/13385119/210863101-5fcdfec9-a55b-4fd5-87aa-c1625ea11026.png)
