### ISSUE TITLE
[BUG] table search box gets hidden

### ISSUE THREAD

**Issue by tobiasKaminsky** [Rello/analytics#329]
Have table and diagram.
Data is: year, date of year, value, e.g. 2022; 01.01; 0

Filter table and type "01.01", which shows then e.g. 4 years for "01.01", which works fine.
But then filter input is gone:

![image](https://user-images.githubusercontent.com/5836855/211288118-da1e3052-e144-4aec-be7a-b465f470fefe.png)

After reload:
![image](https://user-images.githubusercontent.com/5836855/211288183-8db4da49-5488-48f3-bd54-f1bac54d5bf1.png)

**Comment by Rello** [comment]
Hi Tobias,

there is a difference between the filter and the search.
filter is for the whole report - this restricts the amount of data being read from the backend.

the search below is just for the table. and this is hidden, when there less than 1 page of entries in the table.

do you see a problem or room for better explanation/hints here?

**Comment by tobiasKaminsky** [comment]
Sorry, then I mixed terms "filter" and "search".
I am referring to "search" bound to table.

My use case is to search for all "01.01" and then directly search for "01.02", to see how actual values change.
As after first search the input vanishes, I need to reload entire page to do it.
(sometimes I also mistype and suddenly search input is gone)

I do not see any reason to hide the search. Similar to search on NC in upper right an user should be able to search as often as they like.

**Comment by Rello** [comment]
Ok. understood - and found the issue!
the search should actually only be hidden when there are initially less than one page - because then you will never need it and the layout can be simplified.

that it is also hidden after performing a search is new!
seems to be related to one of the latest datatable-updates. will fix this

**Comment by tobiasKaminsky** [comment]
Many thanks 💙
