### ISSUE TITLE
overwrite or summation aggregation mode in data load

### ISSUE THREAD

**Issue by kevinkuan1969** [Rello/analytics#330]
Got excited and thinking it should be stable solution after version 4.6.0 but very disappointed the application is not even ready for any simple day-to-day reporting purpose.

The basic requirement of any reporting tool is not only the visualization but the most importantly is to handle and process data correctly.

Invested almost 3 days to learn all the steps and practice to generate simple reporting using Tableau standard demo Excel data.

Using Data Maintenance to load the data as below:
![image](https://user-images.githubusercontent.com/80019930/212593027-afc6f010-c85b-4e17-9b22-ac60b56ffdab.png)

Created 2 sets of reports but both gave 2 different set of answers as below:
![image](https://user-images.githubusercontent.com/80019930/212593307-be677071-5a37-4f48-8f2b-62228e45309a.png)

![image](https://user-images.githubusercontent.com/80019930/212593394-c5fee79f-d7a5-4871-a8f0-412cfbbbbfde.png)

Same source of data but with 2 set of different reports is not convincing for any reporting tool. 
Overall, the system is not stable in term of data loading as well as visualization. More testing is needed and hope no offence.

**Comment by Rello** [comment]
Good morning.
in order to make any use of the claim of an in-stable system, please provide the export of these 2 reports

**Comment by kevinkuan1969** [comment]
I have uploaded the text file and you can try to load and produce 2 reports.
Please confirm your 2 reports which are using the same source can produce the same result. [Thanks.]
[Sample - Superstore by Category.txt](https://github.com/Rello/analytics/files/10455741/Sample.-.Superstore.by.Category.txt)
e source can produce the same result. [Thanks.]

**Comment by Rello** [comment]
ok, I see the challenge.
the reporting database is based on unique keys + value. 
The columns are the key. so there is only one occurrence per Category/Date stored.

Current Analytics setup is based on overwrite, so the last value wins. As there is limited control on how the database processes the batches, the values can differ.
Last value wins

if you build a realtime report on the txt file, all values are shown - but not summed up. File access datasources are not that flexible compared to database.

What could be a solution?
Analytics could be adopted to provide the loading option of "overwrite" or "sum up" during imports

**Comment by kevinkuan1969** [comment]
Thanks Rello for your kind explanation.
The way of Analytics to manipulate or process data is very different from other typical BI reporting tool which by default to group or summarize the input data. 
In order to use Analytics, the input data has to be well define or must group beforehand. 
If not, garbage in garbage out. 
Without any simple ETL features, it is quite difficult to automate any reporting using Nextcloud. 
Anyway, good effort and thanks.

**Comment by Rello** [comment]
naja. but as mentioned above, this should work. I am testing already.
I will not redevelop an Alteryx into Analytics - this would be too much. but this case can be handled pretty easily by adding the aggregation rule - similar to other typical BI tools.

![Bildschirm­foto 2023-01-23 um 14 03 32](https://user-images.githubusercontent.com/13385119/214046544-17dca565-002d-4b27-9390-1fc024acac51.png)

**Comment by Rello** [comment]
one thing to test for you: set the "delete before load" to yes. As you are doing a full load. then the existing-record-check is disabled for better performance.
then all values will be written.
Please try

**Comment by Rello** [comment]
Hi,
the feature was developed in the backend but I will not enable it yet.
The use case is very limited and only makes the UI more complicated. 
in your case, please select the "delete before load". then the report will sum up the vales for you
