### ISSUE TITLE
how to get the matrix format of JSON

### ISSUE THREAD

**Issue by 2ipm1nd** [Rello/analytics#331]
Hi everyone, I want to retrieve PM25 data from `https://api.waqi.info/feed/shanghai/?token=demo` and the settings are as follows

```
URL: https://api.waqi.info/feed/shanghai/?token=demo
Object path:data/forecast/daily/pm25{avg,date}
Method: POST
Timestamp false
```

This message appears after setting, `Cannot access offset of type string on string`, how to fix it ? thanks.

**Comment by Rello** [comment]
Hi,
some issues:
- its "day", not "date"
- the value needs to be in the last column. switch them.
- to get to a usable format for a timeline chart, date needs to be in the second column. for this you can include a dummy text in the first column. i this case "pm25"? by this you could add more to one chart
- GET not POST

just use this Object path: `data/forecast/daily/pm25{pm25,day,avg}`
<img width="432" alt="Bildschirm­foto 2023-01-29 um 20 35 50" src="https://user-images.githubusercontent.com/13385119/215351422-023f4a55-ac36-422d-af0f-f6e24ee9b073.png">

you can use this in either a dataload or in realtime...
<img width="975" alt="Bildschirm­foto 2023-01-29 um 20 37 00" src="https://user-images.githubusercontent.com/13385119/215351478-6e6e2f4b-76e6-40ed-8240-a5ca564b5bf3.png">
