### ISSUE TITLE
decimal number formatting

### ISSUE THREAD

**Issue by merzak274j** [Rello/analytics#332]
I am having a lot of trouble trying to format the number of decimal points. I have been at it for a few days now with no success.

What is the syntax to format values to numbers with 4 decimal points in a table ?

I understand that this can be set in the visualization section and that syntax must be written in JSON and comply with the chartjs api.

I have a dataset configured to pull information from [https://www.bankofcanada.ca/valet/observations/FXUSDCAD/csv](url)

The documentation for this API is here : [https://www.bankofcanada.ca/valet/docs](url)

I wasn't able to use the JSON endpoint because it seems as though analytics will not extract nested fields, my objective is to have 2 columns, the date and the rate.

I was able to configure a dataset and load it to a report, but the report re-formats the exchange rate as a number with 2 decimal points. I would like to have the 4 decimal rate as it's necessary for accuracy. 

I have tried many combinations of syntax, and each time I try the table simply does not load, so there is no debugging possible. 

`{
    "scales": {
      "yAxes": [
        {
          "ticks": {
            "callback": function(value, index, values) {
              return value.toFixed(4);
            }
          }
        }
      ]
    }
}` 

Does anyone have experience with a similar issue ? 

I reviewed previous issues but did not see exactly the same situation.

I also noticed that when I chose table & chart, then the dashboard will always show a little image of the chart. However if it's just a table it shows the latest rate. Ideally the dashboard would always show the latest rate, and not the chart

**Comment by Rello** [comment]
Hi,

here is the thing. the database can only store 2 digits. That was a design decision at the beginning. Until now I never had the request for more digits.

regarding your request, its i still possible:
Use a realtime report. a little slower than a stored one, but it works.

Use these settings.
One tweak is that you add a description at the beginning to archive 3 columns with the date in the second column
![Bildschirm­foto 2023-02-07 um 21 03 51](https://user-images.githubusercontent.com/13385119/217352940-37c5c6b1-09c2-4744-87eb-45affcfbc436.png)

But with these settings, you can also display a timeline chart
![Bildschirm­foto 2023-02-07 um 21 05 14](https://user-images.githubusercontent.com/13385119/217353215-a55babff-e0d1-4b6f-accc-3f0dff5d5ee4.png)

does this work for you?

**Comment by Rello** [comment]
one addition: if you try, the table might not yet show the 3 digits. this is fixed with the next version

**Comment by merzak274j** [comment]
Hello, thank you very much for the detailed explanations and response.

I have created the realtime report, but will wait for the next version since as you mentioned it currently shows 2 decimal points.

My use case is particular, so I understand that users commonly will have no need for 4 digits.

Thank you once again for the reply and for this app.
