### ISSUE TITLE
Can't open reports.

### ISSUE THREAD

**Issue by playtoncz** [Rello/analytics#334]
When I click on report, demo, or my own in the analytics app. It doesn't show the report.  As you can see I have clicked on Demo: Finance and it doesn't show anything. The URL changes, but nothing opens.
![image](https://user-images.githubusercontent.com/11908925/218973415-9ca3b2f7-7ee3-4523-a762-9a767eb88949.png)

**Comment by Rello** [comment]
can you please have a look in the browser console for any error?

**Comment by playtoncz** [comment]
I just figured out that I had corrupted hard drive so yea, that could be the problem. If problem reappears after reinstalling to new drive I will reopen the problem.
