### ISSUE TITLE
Cannot change color of data series

### ISSUE THREAD

**Issue by Janokisu** [Rello/analytics#338]
Hi Rello,
as the title says, I can't change the color in the diagram.

When I change the color and click OK, it loads briefly and then doesn't even display the digram. Must then click on the report or reload the page. The color values are also not saved.

The console of Firefox gives as error message:
Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data
    sortDates https://{domain}/custom_apps/analytics/js/app.js?v=9ce6d92b-23:1105
    onreadystatechange https://{domain}/custom_apps/analytics/js/app.js?v=9ce6d92b-23:1076
    getData https://{domain}/custom_apps/analytics/js/app.js?v=9ce6d92b-23:1049
    processOptionsDialog https://{domain}/custom_apps/analytics/js/filter.js?v=9ce6d92b-23:430
    openChartOptionsDialog https://{domain}/custom_apps/analytics/js/filter.js?v=9ce6d92b-23:355
app.js:1105:22

**Comment by Rello** [comment]
I will try locally
