### ISSUE TITLE
automated data deletion not working

### ISSUE THREAD

**Issue by Janokisu** [Rello/analytics#339]
Hi Rello,

ich bin mir an der Stelle nicht ganz sicher, ob das ein Bug oder ein Bedienfehler meinerseits ist.

Ich habe testweise mal 6 Datenpunkte angelegt.
Unter "Automatisierung" gibt es die Möglichkeit "Datenlöschung". 

Wenn ich eine Bedingung anlege und speichere und dann auf "Jetzt laden" (Testlauf) zeigt es mir "2" an.

Wenn ich "Jetzt laden" ausführe, kommt die Nachricht "2 Löschungen" aber es sind dann immer noch alle 6 Datenpunkte vorhanden.

Ist das bei dir ebenfalls oder mache ich evtl. etwas falsch?

**Comment by Rello** [comment]
let me try....

can you please export the report and send it to analytics (at) scherello.de ?
will make it easier

**Comment by Rello** [comment]
Issue will be fixed with the next version
thank you
