### ISSUE TITLE
How to get combined charts as shown in readme.md in "flexible visualization" image

### ISSUE THREAD

**Issue by jlll23** [Rello/analytics#341]
Hello

I would like to be able to show on a single page multiple graphs coming from the same datasets as you show in the readme.md with the flexible visualization image.
I tried to follow the link [combined charts](https://github.com/Rello/analytics/wiki/Filter,-display-options-&-drilldown), in the readme.md but didn't succeed to reach my objective

Best regards

**Comment by Rello** [comment]
Hello,
what exactly is your issue?
Flexible visualizations is only a collection of screenshots - not one report.

one report can have one chart (in whatever color or column/line combination) you want.
if you mark a report as favorite, they are shown on the start page of Analyitcs or in Nextcloud Dashboard (if the widget is enabled)

**Comment by jlll23** [comment]
I would like multiple reports on the same page, not on the same unique graph.
For example, one graph sows to me number of jobs launched in a computation farm and a second graph on the same page shows number of jobs waiting for scheduling or suspended.
It don't want these different lines on the same graph as they are not in the same range and even if I use a secondary axis the result is too mixed and make the graph analysis painful

**Comment by Rello** [comment]
Hello,
this is not possible yet. This would be the next evolution of Analytics to create Dashboards or stories = combination of several reports.

This would require quite some implementation effort - and its a free time project at the end...

**Comment by jlll23** [comment]
Thanks for the clarification.
On my side I agree to close this issue if you agree too
