### ISSUE TITLE
sharing of report groups

### ISSUE THREAD

**Issue by jlll23** [Rello/analytics#342]
Hello

Thanks again for your great app.

I have a set of reports that I have grouped.
Now I would like to share this group with all reports it contains and not have to share reports one by one.

If this feature doesn't yet exist, I see 2 advantages for it:
1) It would be faster to share/unshare
2) Once shared, the users would see a single entry for the shared group and no longer one entry per shared report

Best regards

**Comment by Rello** [comment]
Hello,
I understand your point. unfortunately this is not how the system is currently structured. its a bigger redesign.
I will keep this request open and will look at it when a corresponding free time is available.

**Comment by jlll23** [comment]
I understand. No trouble as it just was a suggestion.
Thanks to your contribution in the opensource, your tool really is useful
