### ISSUE TITLE
String meaning/translation doubt removal

### ISSUE THREAD

**Issue by silopolis** [Rello/analytics#344]
Hi,

Checking translations I came to to the following two instances where I couldn't clearly determine if the filter is "for the Analytics app" or "for data analytics".

https://github.com/Rello/analytics/blob/master/templates/part.content.php#L106
https://github.com/Rello/analytics/blob/master/templates/part.content_advanced.php#L37

Thanks in advance for your clarification
TY
J

**Comment by Rello** [comment]
Hello,
I can try to comment it. 
this *analytics* should not be translated. its related to the pure string which is used in content filters.
the default popup blocker is filtering anything with *analytics* to catch things like google_analyitcs.
you know what i mean? ist a plain string - not the app name.

makes sence?

THANK YOU for your effort in the translations!

**Comment by silopolis** [comment]
Makes perfect sense, thank you.
Tried to make it a bit clearer in #345 

You're very welcome, thank _you_ for sharing your work
