### ISSUE TITLE
URL parsing replace &amp; in CSV datasource

### ISSUE THREAD

**Issue by xsiruse** [Rello/analytics#348]
still having problem while adding the source for remote CSV. replacement of & leads to double 'amp;' 

the error tracker on the other side shows
`==== Processing Request: ====
GET &#x2F;apex&#x2F;un&#x2F;fci_qst.DOWNLOAD_CSV_RPT?r_id=OSN_ATTR&amp;amp;username=foo&amp;amp;pwd=bar`

**Comment by Rello** [comment]
not good. should have been fixed already. 
let me check

**Comment by Rello** [comment]
Hello,
found the issue. the last fix was applied to the JSON datasource. 
I missed the CSV version :-(

I will release the next version shortly. need to finish some testing...

**Comment by xsiruse** [comment]
Great news! sincerely waiting for release

**Comment by Rello** [comment]
Hi,
it was planned for yesterday. unfortunately the testing showed an issue with the report sharing that needs to be solved first

**Comment by xsiruse** [comment]
The solution of the problem confirmed. Thank you!
