### ISSUE TITLE
datasource CSV - custom delimiter

### ISSUE THREAD

**Issue by xsiruse** [Rello/analytics#349]
Is it possible to make a choice of delimiter (at least) and quotations, while setting up the CSV data sources?
Some of our data contains commas inside the values and a source data compiler is way inflexible due to it's legacy.

Thank you in advance!

**Comment by xsiruse** [comment]
So sorry, it really works fine. I assumed, that error I met was due to delimiter problem.
while picking up columns the modal screen shuts down immediately and error says "Parameter missing", but if I enter the series with column index, then report reveals quite fine. The initial question is resolved. Issue can be closed

**Comment by Rello** [comment]
can you send a screenshot of your automation?
I would like to get an idea about the "parameter missing".
did you save it once (ok flag) before doing the column picker?

**Comment by xsiruse** [comment]
![image](https://user-images.githubusercontent.com/18045257/235589940-ec56cabe-844a-48d2-890e-fe4358be3e93.png)
hope this would be helpful

**Comment by Rello** [comment]
Hi,
i need the settings that you did for the datasource. url, header rows, deletion...

**Comment by xsiruse** [comment]
it was the simple report with locally (nextcloude) stored CSV. the semple file is below
[fci_qst_semicomma_delimited (1).csv](https://github.com/Rello/analytics/files/11373181/fci_qst_semicomma_delimited.1.csv)

**Comment by Rello** [comment]
I need the configuration of the dataload. for me it works:
![Bildschirmfoto 2023-05-02 um 19 40 27](https://user-images.githubusercontent.com/13385119/235742914-026720d6-b084-49f9-98ea-1137f1b2076e.png)

![Bildschirmfoto 2023-05-02 um 19 40 38](https://user-images.githubusercontent.com/13385119/235742957-60e37ae7-c5fc-4908-97b5-70cffebe7639.png)

**Comment by xsiruse** [comment]
Hm, so weird. Thought it was some problems with browser, but Edge, Chrome and Chromium shows the same. IE didn't even let me in)))
Well, thanks anyway, I'll try to dig into restriction policies of our nextcloud instance. Ether way it is not so tremendous to waste much time to.

**Comment by Rello** [comment]
![Bildschirmfoto 2023-05-14 um 20 38 38](https://github.com/Rello/analytics/assets/13385119/7515cb61-843c-4506-b79c-4b5657ab527f)

Hi,
thats strange. all working here. I will release the new version and then lets see if the error still shows up on your side
