### ISSUE TITLE
Donate button

### ISSUE THREAD

**Issue by ernesst** [Rello/analytics#35]
Hello,

I'm discovering your app, thanks
It seems that the button donate redirect to another of your app, it might be confusing for some person : 
![image](https://user-images.githubusercontent.com/11337464/78457975-d4b26880-7673-11ea-9e48-1e27cf6665e1.png)

**Comment by Rello** [comment]
yes, almost forgot about it.
but feel free to use it - it will arrive anyway :-)

I will correct it

**Comment by Rello** [comment]
thank you for the hint

**Comment by ernesst** [comment]
Done ;)
