### ISSUE TITLE
Tables as datasource

### ISSUE THREAD

**Issue by junewinter2013** [Rello/analytics#350]
Hi, thanks for such a great app!

I am wondering whether it is possible to use SQL tables as data source ?
Specifically I am looking at using data from the Nextcloud Tables App:
https://apps.nextcloud.com/apps/tables
https://github.com/nextcloud/tables

I can export data to CSV from Tables App and then import as CSV into Analytics App, but it is a bit of a pain :)

Thanks very much for your help.

Kind regards,
June

**Comment by Rello** [comment]
Hi,
since Tables v0.3.0, it delivers a data source for Analytics.
Check the data source dropdown and you should see "Nextcloud Tables"

**Comment by junewinter2013** [comment]
My goodness, that amazing!
How can I miss that!
Thanks very much for your help.

Kind regards,
June
