### ISSUE TITLE
yAxis does not start at 0

### ISSUE THREAD

**Issue by Himra** [Rello/analytics#352]
Hello all,

yAxis does not start at 0 see picture (it is the fifth value which has to be activated via the legend)

![image](https://user-images.githubusercontent.com/15324567/236820207-82c6a667-3b87-4666-a1dc-2580ef23dccb.png)

Actually the same as #152

the funny thing is that it works with older reports

![image](https://user-images.githubusercontent.com/15324567/236813731-6273ee88-4417-4460-9607-bf7367083994.png)

Greeting Himra

**Comment by Himra** [comment]
Hello Rello,

Thank you for your quick reply.

Unfortunately, I can only find the export for the configuration in the report section but none which can export the measurement data.

Where can I find this export function

Regards Himra

**Comment by Rello** [comment]
Hi,
the export button should export both in one file actually

**Comment by Himra** [comment]
Hello @Rello,

have again tried something with the chart options and this:
```js
{"scales":{"secondary":{"display":true}}}
```

replaced by this one:
```js
{"scales":{"secondary":{"display":true,"beginAtZero":true}}}
```

Now the display is correct:

![image](https://github.com/Rello/analytics/assets/15324567/4d8fb963-1b3b-43c1-b03a-3ad2163e3c9a)


Thanks and greetings

Himra

**Comment by Rello** [comment]
Hi,
i checked the docu.
https://www.chartjs.org/docs/latest/axes/cartesian/linear.html
chartjs does calculate it automatically if there is no 0 given in the records- unless mentioned by you.
for the moment you can choose your parameter.
on the long run I want to think about a way to include more of these parameters - like units and so on - into the UI to be set there...

**Comment by Himra** [comment]
thanks for your feedback and the great Nextcloud App
