### ISSUE TITLE
Sharing reports not possible any more

### ISSUE THREAD

**Issue by i-novis** [Rello/analytics#354]
after updating Analytics to version 4.9.1, sharing of reports (that already existed before the update) is no longer possible.
P.S.: We have a similar problem with NextCloud shares. However, this only affects shares that already existed before the update of NextCloud to version 26.0.1. New shares from other folders/files can also be created after the NextCloud update.

**Comment by Rello** [comment]
Hello,
I need more details please.

- can you share reports?
- share with link, user or group?
- new or old shares not working?
- can you create them?
- are they shown in the sidebar?

**Comment by CashAMatic** [comment]
Using Nextcloud Hub 4 (26.0.1)
Analytics 4.9.1

I also am unable to share a report with a user.  I tried making a report group and sharing that, same result.  The user shows up in the share tab, but when I navigate to Analytics as that user, there are no reports.  I also tried creating a new report and sharing it.

I can share a link.  That works.

**Comment by i-novis** [comment]
Do you also have problems with NextCloud shares, or only with sharing analytics reports?

**Comment by Rello** [comment]
I am still searching. working on my side. @CashAMatic which data source are you using in the shared report?
internal? file? ...

**Comment by Rello** [comment]
> Do you also have problems with NextCloud shares, or only with sharing analytics reports?

Hi @i-novis,
for file shares, were is the shared file located? locally or in an external storage? there is a known issue with shares on external storages. need to find the ticket...

**Comment by i-novis** [comment]
Hi @Rello 
wow, I completely missed that! Only SMB shares are affected, thanks for the great tip!

**Comment by Rello** [comment]
https://github.com/nextcloud/server/issues/37473

this involves SMB shares which are connected as User. Admin mounts would work.
will be fixed with 26.0.2, which is planned for tomorrow.

to be honest I did not know that this would have an effect on Analytics reports actually...

**Comment by i-novis** [comment]
great that you gave me this notice: We've been looking for a solution to the SMB sharing problems for weeks now. Good that they seem to be history tomorrow ;-)

**Comment by Rello** [comment]
I am still testing. 
I set up a 26.0.1 with SMB external storage; created a csv file; created a report on this; shared the report.
all working. really a mystery ...

**Comment by Rello** [comment]
@CashAMatic 
@i-novis 
fixed with updated 4.9.3

**Comment by i-novis** [comment]
@Rello 
many thanks for the competent, kind and quick support!
