### ISSUE TITLE
Error in journal after upgrade Nextcloud to 24.0.12

### ISSUE THREAD

**Issue by AstashovAndrey** [Rello/analytics#355]
From help.nextcloud.com

The issue is with the Analytics app.

From the looks of it I think [this change](https://github.com/Rello/analytics/issues/343) may have introduced an incompatibility with older NC installations. It implements Smart Picker support in the Analytics app. But the Smart Picker requires >=NC26.

https://help.nextcloud.com/t/error-in-journal-after-upgrade-nextcloud-to-24-0-12/163650/3

> What NC version did you upgrade from?

24.0.7.1 → 24.0.12.1

> Is that a one-time error message or recurring?

Recurring. 8 - 10 error messages in seconds.

> Are you experiencing any other issues with Nextcloud?

No. I don’t experience any other problems.

> Please always provide the full (raw) stack trace when asking for help. It’s necessary typically to get to the bottom of things.

{
	"reqId": "...",
	"level": 4,
	"time": "2023-06-08T17:54:04+00:00",
	"remoteAddr": "192.168.1.1",
	"user": "--",
	"app": "analytics",
	"method": "PROPFIND",
	"url": "/remote.php/dav/files/astashov/",
	"message": "Error during app service registration: Call to undefined method OCP\\AppFramework\\Bootstrap\\IRegistrationContext@anonymous::registerReferenceProvider()",
	"userAgent": "Mozilla/5.0 (Windows) mirall/3.8.2stable-Win64 (build 20230516) (Nextcloud, windows-10.0.22621 ClientArchitecture: x86_64 OsArchitecture: x86_64)",
	"version": "24.0.12.1",
	"exception": {
		"Exception": "Error",
		"Message": "Call to undefined method OCP\\AppFramework\\Bootstrap\\IRegistrationContext@anonymous::registerReferenceProvider()",
		"Code": 0,
		"Trace": [
			{
				"file": "/var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php",
				"line": 136,
				"function": "register",
				"class": "OCA\\Analytics\\AppInfo\\Application",
				"type": "->"
			},
			{
				"file": "/var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php",
				"line": 91,
				"function": "registerApps",
				"class": "OC\\AppFramework\\Bootstrap\\Coordinator",
				"type": "->"
			},
			{
				"file": "/var/www/nextcloud/lib/base.php",
				"line": 661,
				"function": "runInitialRegistration",
				"class": "OC\\AppFramework\\Bootstrap\\Coordinator",
				"type": "->"
			},
			{
				"file": "/var/www/nextcloud/lib/base.php",
				"line": 1111,
				"function": "init",
				"class": "OC",
				"type": "::"
			},
			{
				"file": "/var/www/nextcloud/remote.php",
				"line": 118,
				"args": [
					"/var/www/nextcloud/lib/base.php"
				],
				"function": "require_once"
			}
		],
		"File": "/var/www/nextcloud/apps/analytics/lib/AppInfo/Application.php",
		"Line": 48,
		"message": "Error during app service registration: Call to undefined method OCP\\AppFramework\\Bootstrap\\IRegistrationContext@anonymous::registerReferenceProvider()",
		"exception": {},
		"CustomMessage": "Error during app service registration: Call to undefined method OCP\\AppFramework\\Bootstrap\\IRegistrationContext@anonymous::registerReferenceProvider()"
	}
}

**Comment by Rello** [comment]
Hi,
thank you for the report. the fix will be released shortly

**Comment by Rello** [comment]
fixed
