### ISSUE TITLE
Jason not working HTTP error 0

### ISSUE THREAD

**Issue by hirehamva** [Rello/analytics#369]
Hy there!
Jason not working for me since 2023.08.22. I didn't changed anything. I get HTTP error 0 on test.

Off topic:
I made a small program wich sends data to Analitcs API- fom a comport arduino termometer.
[https://www.hirehamva.hu/wpblog/archivum/sdm_downloads/thermometer](https://www.hirehamva.hu/wpblog/archivum/sdm_downloads/thermometer)
Not perfect but working. :)

**Comment by Rello** [comment]
Hi,
can you send a screenshot of the data source config and the url?
i need some info to check

**Comment by hirehamva** [comment]
Response of site:

{"StatusSNS":{"Time":"2023-09-07T16:26:25","AM2301":{"Temperature":26.8,"Humidity":29.5,"DewPoint":7.5},"TempUnit":"C"}}

**Comment by hirehamva** [comment]
Please delete the error report. This is shameful. On my server, the dns setting is 127.0.0.53 for some reason, even though I didn't touch it. I did not notice. Sorry for the inconvenience.
