### ISSUE TITLE
broken graph with two data loads since version 4.11.0

### ISSUE THREAD

**Issue by mf8hd** [Rello/analytics#373]
I have a dataset with two data loads, both HTML grabbers with "timestamp of dataload" set to yes.
![Dataset](https://github.com/Rello/analytics/assets/21962549/fb23ebfb-19dc-4884-97ad-c0c2ba6b48cd)

In Analytics version 4.10.0 the line graph look good, but since the update to version 4.11.0 the graph looks like this:
![Line Graph](https://github.com/Rello/analytics/assets/21962549/47496ba8-9161-445b-a23c-f3c2cea2f3be)

When I change the graph style to "bar graph" it looks like this:
![Bar Graph](https://github.com/Rello/analytics/assets/21962549/92285b71-c0cd-42e6-9b98-5916106feb85)

I think there is something wrong with the cronological sort order of the second data row. The data point of the second data row, that are shown after the last data point of the first data row should fill in the gabs of the second data row.
![Bar Graph X Axis](https://github.com/Rello/analytics/assets/21962549/e0bc7145-91b0-48ea-b1d0-5dde8e72ea0e)

I have reset the data collection after the update to version 4.11.0, but nothing changed.

**Comment by Rello** [comment]
Hi,
thank you for the report.
I will check where the sorting got lost...

**Comment by Rello** [comment]
Hi, can you export the report and drop me the file here:
https://home.scherello.de/owncloud/s/FdwAJ52FkxTa7cm

I tried and I could not reproduce. 
what is the time format you are adding?

**Comment by mf8hd** [comment]
The report works fine if i use chart type "timeline" but does not work if i use chart type "line". (I uploaded the reports and sample data.). If thats the intended behaviour then it's ok with me.

Thank you for your great work!
