### ISSUE TITLE
Reports on Nextcloud files ? 

### ISSUE THREAD

**Issue by potagerGit** [Rello/analytics#374]
Hello, i have a nextcloud instance for my 4 family members.
Il would like to do some reports on my local NC files for each users, to better understand how everyone uses its quota
for exemple compare each user in these metrics : 
- nb of files by types (how many pictures, videos, pdf, etc..)
- volumes of files added or removed by range of time

Is this possible with Analytics or is there another NC app for this ? 
I installed Analytics, but I am confused how to set my local files as a new dataset

**Comment by Rello** [comment]
Hi,

currently the only way to get this kind of data out is to do reporting on the standards monitoring API of Nextcloud. This can be connected to Analytics.
have a look here:
https://github.com/Rello/analytics/wiki/Datasource:-JSON#example-1

but I am not sure if there is information on user level. you would need to check the raw data of that API
