### ISSUE TITLE
Combine 2 values on y axis and date/time on x axis ?

### ISSUE THREAD

**Issue by atelierscym** [Rello/analytics#375]
Hello Rello and all, I have 2 usecases that look very similar but that I can not display with Analytics. It is about representing dates on th x axis, and two distinct values on the y axis. 
- **use case 1** : ** blood pressure** represent diastolic and systolic blood pressure over a period of time, taken at irregular intervals
- **use case 2** : ** T°/Hr%** represent the temperature and humidity of a room over a period of time, taken at regular intervals (every 3 minutes)

I only found a way to display a single value in ordinates with the date in abcissa, and again, it is taken into account as a value and not as a date. My dates are in `2023-10-26 19:00:00` format. The data comes from csv files.

![Temperature over time](https://i.imgur.com/3WoeRxL.jpeg)

Is there a way to do what I want with Analytics, and if so, how?
Thank you in advance for your answers!

**Comment by Rello** [comment]
Hello,
is this topic still open?
you should be able to use the axis time formatting to make the chart understand almost any time-format
https://github.com/Rello/analytics/wiki/Advanced-chart-options
