### ISSUE TITLE
Certificate "4353" has been revoked 

### ISSUE THREAD

**Issue by himekifee** [Rello/analytics#38]
When installing analytics app from nextcloud web app store, it gave this error. Searched and guess it might be an error from release group.

**Comment by Rello** [comment]
Hello,
I just tried it again - no issue here.
which NC version?
can you show a screenshot of the issue?

**Comment by himekifee** [comment]
![图片](https://user-images.githubusercontent.com/22322294/80293913-74a47300-8796-11ea-9686-d71e24bb5c52.png)
snap Nextcloud 18.0.4 Build:2020-04-23T23:01:58+00:00 4bcbeffeb6dea9142d1088e1cc095a3ac2c945a4
`Linux BCS 5.3.0-46-generic #38-Ubuntu SMP Fri Mar 27 17:37:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by Rello** [comment]
Hello,
can you install any other app?

**Comment by Rello** [comment]
some issue in NC. I think something went wrong with the revoke-list

**Comment by himekifee** [comment]
OK. Waiting here.

**Comment by Rello** [comment]
issue located. i will push a new version

**Comment by MorrisJobke** [comment]
Fixed by issuing a new certificate. Sorry for the trouble.

**Comment by Rello** [comment]
@himekifee please try again
