### ISSUE TITLE
Nextcloud Tables name with "-"

### ISSUE THREAD

**Issue by hyperlink-skylight** [Rello/analytics#380]
Hi, 

there is an issue when renaming the Nextcloud table used as data source after setting up a background load job. 

To reproduce: 

1. Create a Nextcloud table. For example "Gewicht". 
2. Create an Analytics report with a dataset. 
3. Under "automation" choose the Nextcloud table as the source. 
4. Configure a hourly background load. 
5. Wait until the background job runs the first time and verify that everything works as expected. 
6. Rename the Nextcloud table and let it contain a "-". For example "Gewicht - Stefan". 
7. Wait for the next run of the background job and receive an error message via notifcation. 

I guess it has to do with the second issue that I noticed: 

In the automation area: 
If you want to choose a Nextcloud table from the dropdown list, it truncates the table names at the point where a "-" exists in the name. 
For example: The table name "Gewicht - Stefan" appears as "Gewicht " in the dropdown list. 

I think if the "-" problem is solved, then the issue with the failing background job is solved, too.

**Comment by Rello** [comment]
Hi,

the '-' caused just a display issue. it is corrected in the next version. 
But all data loads are via IDs, so that can not be the issue. 
is there anything on the nextcloud.log?

**Comment by hartsberger** [comment]
I fixed the load errors now. Had been strange values in the data source. Now it's working. 
Thanks for fixing the display issue.

**Comment by Rello** [comment]
Hi @hartsberger can you comment on the "strange values"?
I am always looking into making the app more error resistant...

**Comment by hartsberger** [comment]
Hi @Rello , 
sure. I have a Nextcloud table with some rows not having values in it (Null values). 
These null values get displayed as "NaN" in the tables app. 
When I try to load them, I get an error message, that the load has failed. But it does not tell me why. 

It would be nice, if the system tells my why it has failed to load the data. 
Or if it would just load these null values in the table. 
Or if it would ask me if I would like to include null values. 

Thank you
