### ISSUE TITLE
Filtering a time chart by text variables is not working

### ISSUE THREAD

**Issue by molbar** [Rello/analytics#382]
Hello,

I could not make filtering of Date happen on a time chart. Even though i found similar issue reported by @PVince81

I tried to follow:
Instructions: [https://github.com/Rello/analytics/wiki/Filter,-chart-options-&-drilldown##text-variables](url)
Reported issue/solution: #321 Filter variables to use same time format like chart

### Case description:
Data is POST-ed from a microcontroller using REST API
POST frequency: 1 min

### Dataset:
Object: "str" Data ID
Date: Text Variable %now% -> transformed to unix timestamp epoch to DB
Value: "int"

Applying multiple text filter for Object column works fine
![image](https://github.com/Rello/analytics/assets/95926513/fb77b73f-eb0c-45e7-90b1-1953efc68bf8)

Applying .js format parser on X axes  works fine:
`{"scales":{"xAxes":{"time":{"parser":"X"}},"secondary":{"display":true}}}`

**However:**
Adding an additional filter using the text variables could not bring me to the expected behavior:
Expected behavior: Only recent data is shown (today or not older than 24 hours)
Tried to use the following variations:

- "Date" "greater than" `%yesterday% (U)`  -> Same data, no filtering
- "Date" "greater than" `%yesterday%`   -> Same data, no filtering
- "Date" "equal to" `%today% (U)` -> No data found
- "Date" "greater than" `last 1 day`   -> Same data, no filtering
- "Date" "greater than" `last 1 day(U)`   -> Same data, no filtering
- "Date" "less than" `last 1 day (U)` -> No data found
- "Date" "greater than" `1704103112` -> working fine so no filter issue rather like a format text variable issue to epoch

**Comment by molbar** [comment]
I was checking the function: ` private function parseFilter($filter)` today

It seems to be working fine.

`$filter = "%last 1 day% (U)";`

returning:

> Array
(
    [value] => 1704672000
    [option] => GT
    [1$filter] => last 1 day
    [2$timestring] => -1 day
    [3$target] => 1704699662
    [4$target_clean] => 2024-01-08
    [5$startString] => today
    [6$startDate] => 2024-01-08
    [7$startTS] => 1704672000
)

So I still cannot figure out why 

**This works with returned value:**
![image](https://github.com/Rello/analytics/assets/95926513/9707a2cd-00fb-4deb-9d39-9b02794c7dab)

**This is not working:**

![image](https://github.com/Rello/analytics/assets/95926513/c97a2783-3c48-4033-9020-79370dfd9636)

**Comment by Rello** [comment]
Hi, what is the number format of your timestmap? just the number or including a U?
<img width="653" alt="Bildschirmfoto 2024-02-26 um 12 03 52" src="https://github.com/Rello/analytics/assets/13385119/4d1466c4-4dd6-4549-b8fd-d831295774ea">
