### ISSUE TITLE
Thousand separator/locale settings

### ISSUE THREAD

**Issue by valetrine** [Rello/analytics#383]
Do analytics had locale settings? Or it just follow nextcloud/server locale?
I had a problem for displaying date too from spreadsheet, it looked like this:
![image](https://github.com/Rello/analytics/assets/93907827/0a9ce17c-16d5-4ea6-a69a-f3a77ecc07f1)
Do this just a problem from MS excel?

Thank you

**Comment by Rello** [comment]
Hi,
there is a logic to recognize the format based on the number of almost any format.
what is the number in excel?

**Comment by valetrine** [comment]
Yeah, now that you mention it, it's Indonesian format. Thanks for clearing this.

Do you had solution for the thousand separator? I want to change it from comma to dot.

**Comment by Rello** [comment]
do you have a screenshot or so?
I am searching to make the setup working for everything if possible

**Comment by valetrine** [comment]
Here's some example I got:

![Screenshot 2024-01-04 185605](https://github.com/Rello/analytics/assets/93907827/b4a25a75-4940-4f1e-97e1-0f340ddff3e2)
![Screenshot 2024-01-04 185709](https://github.com/Rello/analytics/assets/93907827/1faea503-89c5-45bf-838f-f264b08d5304)
![Screenshot 2024-01-04 185846](https://github.com/Rello/analytics/assets/93907827/23633158-8c93-4ca6-a3cd-757331398d7d)

**Comment by Rello** [comment]
I need to know the source. because the Analytics logic will analyze the number coming from the backend and try to understand it

**Comment by valetrine** [comment]
Here's the sample data

[Data.xlsx](https://github.com/Rello/analytics/files/13831477/Data.xlsx)

**Comment by valetrine** [comment]
I apologize for asking OOT, but is notification severity only available in stored data? I couldn't locate it in my spreadsheet threshold, but I can find it when creating a report from stored data.

**Comment by Rello** [comment]
Hello,

with my current version, everything seems to be correct. the table display is being adopted right now so it will look good for the next release.

...just for the data I need to see if I can do anything here...
<img width="1264" alt="Bildschirmfoto 2024-02-26 um 11 52 37" src="https://github.com/Rello/analytics/assets/13385119/f4320823-cd33-494a-848c-522edf65ffa5">
