### ISSUE TITLE
console error when using timestamps for 1-column raw data

### ISSUE THREAD

**Issue by kevinkuan1969** [Rello/analytics#384]
Nextcloud 28.0.1
Analytics 4.12.0
Ubuntu 23.10
PHP 8.2

There are errors in log reader and wonder why it happened. 
Undefined array key -1 at /var/www/nextcloud/apps/analytics/lib/Controller/DatasourceController.php#146

**Comment by kevinkuan1969** [comment]
![image](https://github.com/Rello/analytics/assets/80019930/f0f4fb53-1552-415f-988d-de508a61824b)

**Comment by Rello** [comment]
Hi,
thank you for the input. I will look at the source here. some special condition ist not being processed correctly.

**Comment by Rello** [comment]
Issue will be fixed with the next release. it was caused by the raw data only containing 1 column...
