### ISSUE TITLE
Integration with NC Tables

### ISSUE THREAD

**Issue by intervisionlord** [Rello/analytics#385]
Hello,
it seems that integration of analytics with tables does not work properly.
For example i have a table with several columns (e.g. LTO Tape Type with fixed values (LTO5, LTO6, LTO7), and their fixed locations (e.g. datacenter 1 and datacenter 2))
When i try to build graph with count of some type of tapes in datacenters i can't do it.

First of all the problem in fixed values in tables app. The analytics app get their ID's but not names, so i have only values like 1, 2 or 3, not LTO5, LTO6, LTO7. And same about locations - i have values only 1 or 2, not names like datacenter1 or datacenter2.

Second problem - it is unable ti build graph with proper axises for example: horisontal axis must be a type and vertical axis mus be a count of tapes of same type, like X:LTO5 Y:100, X:LTO6 Y:500, X:LTO7 Y:1000, so i expect to see 3 bars on graph wich mean tape type and height of this bars depends of count of each type.

But i have only a blank graph...

**Comment by Rello** [comment]
Hi,
thank you for the report. let me check the topic of fixed values. I did not know about them...

**Comment by intervisionlord** [comment]
I have some screenshots to explain what i mean

![lto](https://github.com/Rello/analytics/assets/3979683/090fc481-ac5d-4171-920e-0e9b83f6a8e2)
![lto2](https://github.com/Rello/analytics/assets/3979683/399d7531-caa6-4522-b26b-3754aad07333)
![lto3](https://github.com/Rello/analytics/assets/3979683/35dfc765-92fe-489e-ab79-967273031b9c)
![lto4](https://github.com/Rello/analytics/assets/3979683/6c609da0-56db-47cc-b4a7-7b473fbef3c3)

**Comment by Rello** [comment]
fix is being processed within the Tables API

**Comment by Rello** [comment]
fyi: the fix has been merged in the tables app and will be part of the next version
