### ISSUE TITLE
"Parameter missing" in Nextcloud Tables data source

### ISSUE THREAD

**Issue by intervisionlord** [Rello/analytics#387]
Hello, after clicking on field "Select columns" a popup window shows for a second and disaperas after it with error "Parameter missing"
![select_table_00](https://github.com/Rello/analytics/assets/3979683/501de726-3844-4c27-aa9e-87edbbe53363)
![select_table_01](https://github.com/Rello/analytics/assets/3979683/38058807-f4fb-4f00-8d53-e2f93a4af72c)

**Comment by intervisionlord** [comment]
> Hi,
> i know of one issue that I need to take care of. this error can occur if you made a selection/change for e.g. the table but did not save the datasource afterwards.
> after changing the options, the datasource needs to be saved once. can you try?

Unfortunately I didn't succeed. 
Moreover, in analytics, the data source can no longer be changed, that is, when editing, clicking on the data source, the list does not open and nothing happens.
After saving (I assume by saving we mean the update button) by clicking on the column selection field, the error continues to appear.

**Comment by Rello** [comment]
Hello,
sorry, my mistake. you posted the screenshot of a realtime report. I was referring to the automation via data loads.
in there, there are more options.
...let me check...

**Comment by g-work** [comment]
I have the same issue using automation via data loads (and realtime report, too). In the logs it says
`OCA\Tables\Errors\PermissionError: no read access to table id` and
` 0. /volume1/web/nc/apps/tables/lib/Api/V1Api.php line 46
    OCA\Tables\Service\ColumnService->findAllByTable(11, null, "admin")`

My username ist not admin, the table wasn't created by an admin and I'm not logged in as one. Could this be some kind of permission problem?

**Comment by Rello** [comment]
sorry for the delay. will be fixed with the upcoming update...
