### ISSUE TITLE
Thresholds not working in table

### ISSUE THREAD

**Issue by christoschronopoulos** [Rello/analytics#39]
The thresholds, even though set, are not working. I tried on both graphs and tables. My source file is a csv from a local NC folder. Additionally, the notification option when a threshold is met is not available. ![Screenshot_20200426-005540](https://user-images.githubusercontent.com/12989098/80292750-186f2e00-8759-11ea-8d98-bda0091581c4.png)

**Comment by Rello** [comment]
Hello,
I need some info: 
- threshold in charts don´t work - yet
- threshold in tables should mark them in colours. **you found a bug there**. I will take care

**Comment by christoschronopoulos** [comment]
Thank you for taking care of this! I appreciate your commitment!
