### ISSUE TITLE
Can't access all datasets in legend.

### ISSUE THREAD

**Issue by thisiszeev** [Rello/analytics#390]
As you can see from the image below... because I have so many datasets, I can only turn on and off my first three control datasets. I can't scroll down to the others.

TIA

![analytics-bug-cant-see-all-datasets](https://github.com/Rello/analytics/assets/114545290/3714fe84-87b2-491b-9cc3-87f6cf0f3c7d)

**Comment by Rello** [comment]
Hi,
sorry for the late reply. currently I do not have a solution for this.
This is a very special case and to change the Analytics app to the so called "html legend" just for this is too much effort at the moment.
If someone is submitting a pull, I can check. But I cannot fulfill this request at the moment.

https://www.chartjs.org/docs/latest/samples/legend/html.html
