### ISSUE TITLE
CSV-column with emails leads to broken column in analytics table

### ISSUE THREAD

**Issue by pamuche** [Rello/analytics#391]
First off: wonderful app, very useful !! Thanks a lot.
Got a little bug while rendering following csv content:

```
name,address,mail
Roger,London,roger@rabit.com
```

Leads to 
![ksnip_tmp_pXkTxx](https://github.com/Rello/analytics/assets/986531/5be98f39-544a-493f-935d-4ad572088b75)

Here you can see, that the mail column is not rendered. 

Thanks a lot once again for this great app
@pamuche

**Comment by Rello** [comment]
Hey,
yes, thats a "feature" with the current setup. as it is focused on reporting, Analytics expects a number in the last column.
its a todo to make this more flexible.

but in your case; can you add a "1" column for the moment until I found a better way to handle this?

**Comment by pamuche** [comment]
:smile_cat: Ah ok thanks a lot. Added a column to the end now the mails are shown. Should I add it to the docs? (https://github.com/Rello/analytics/wiki/Datasource:-csv)

**Comment by Rello** [comment]
wiki updated
