### ISSUE TITLE
charts: select account- (values in columns) or kpi-model (values in rows)

### ISSUE THREAD

**Issue by wildernessfamily** [Rello/analytics#393]
I installed NextCloud tables and the NextCloud Analytics extension. I created a Table with sixteen columns. The first column is Date, and the next sixteen columns are water sample types (ex. lead, mercury, iron, etc.). I then created two rows of two type of water sample readings. From there, I went to Analytics extension. Created a new bar chart using real-time data from the NextCloud table. The chart is created but the X,Y are incorrect. The Y should be the date and X should be the different column names. I have looked all around and can't find anywhere on how to define what the X and Y axis should be. I'm not sure what I'm doing wrong. Any suggestions?
![screenshot-office mtnwilderness family-2024 04 19-10_31_28](https://github.com/Rello/analytics/assets/84930441/d5cc1b48-84db-4ceb-a7cf-481fbfadaf45)

**Comment by Rello** [comment]
Hi,
interesting usecase. I will check...

**Comment by Rello** [comment]
Hi,
some background: Currently Analytics is based on a key figure fact table - meaning the dimentions (of your chart in this case) are in the rows and not in the columns. if the table would have multible lines per date, with the categories in the second column plus the value in the third, it would work out of the box.

But I see the case here. makes sense to find an alternative display here. I will check

**Comment by Rello** [comment]
prototype is working. need to see where it can be added to the settings.
its basically switching from the KPI to Account Model view...

![Bildschirmfoto 2024-04-26 um 15 37 16](https://github.com/Rello/analytics/assets/13385119/3a09e496-addb-4e31-a4f7-b5c395e60be8)
