### ISSUE TITLE
No graphs using data from NC tables

### ISSUE THREAD

**Issue by intervisionlord** [Rello/analytics#394]
![image](https://github.com/Rello/analytics/assets/3979683/1db07294-f1f9-40af-8298-6ab5569c9382)

**Comment by Rello** [comment]
Hello,
every report needs a key figure to be displayed in the chart.
if you e.g. add a count at the end, it should work.
can you give it a try?

**Comment by intervisionlord** [comment]
I’m a little confused, but I don’t quite understand how to add a count (in the tables themselves there is no function for counting or creating intermediate tables with summarized data - https://github.com/nextcloud/tables/issues/1184 , and in analytics it’s not clear how to add this)

**Comment by Rello** [comment]
Hello,
what is the expected display in a chart from your data above?
...what you could do is to add a column with a value of 1 at the end? now sure what you actually want to visualize

**Comment by intervisionlord** [comment]
Helo, 

> Hello, what is the expected display in a chart from your data above? ...what you could do is to add a column with a value of 1 at the end? now sure what you actually want to visualize

Hello, i have several cases:
1. multiple values of each type of objects, e.g.: Object_(with unique name) has location_1 or location_2 or location_3
I try to make a chart which represents how many objects in first location, second location and third location
2. multiple objects with different types, e.g. Object_(with unique name) has type_1 or type_2 or type_3
in this case i try to make a chart which represents how many objects of each type i have.
3. each location has objects with different types and i try to make a chart which represents how many objects of each type have each location
4. each location has objects with data and clear objects
in this case i try to represent how many filled and clear objects have each location

in mentioned example i have 4th case

**Comment by Rello** [comment]
Hello,

the charts work basically like this:

- fist column is the data series to be reported (for 1. => location, for 2.=>type)
- the second column (optional) is the values on the x-axis
- the last column is the number to be reported

in your case it should work if you add a "1" to the Nextcloud Table (perhaps I include a counter per default in the data source at some point of time).
then in the report, select just the column to be counted on + the counter. so just 2 columns. then you should be able to show the bar chart

**Comment by intervisionlord** [comment]
Adding 1 to the table was not part of the plan 😄 I guess I should wait to see if the counter will be implemented. Perhaps I will create a solution myself, receiving data from tables through the API.
Thank you for explanation.
