### ISSUE TITLE
wrong decimal handling for certain numbers

### ISSUE THREAD

**Issue by MMM-Tech-Support** [Rello/analytics#397]
Hey,

I use the JSON Datasource to get the atmospheric pressure via a HTTP GET command.
![Screenshot 2024-07-08 at 14-00-43 Analytics - Nextcloud](https://github.com/Rello/analytics/assets/154433718/c6b493ea-3fd9-481e-8ac2-081dedc7787b)
It work's quite well.

When I analysed the data I recognized, that everytime the pressure has more than 2 decimal places the value is 1000 times to high.

So the value 1014.375 becomes 1014375
Please see the 3. column.

![Screenshot 2024-07-08 at 14-03-11 Barometrischer Luftdruck in hPa - Analytics - Nextcloud](https://github.com/Rello/analytics/assets/154433718/7b61be64-26b5-4c58-88ae-b4cd3fefcae7)

Here is the Graph and the the jumps between 1000 and 1000000 are clearly visible.

![Screenshot 2024-07-08 at 14-03-35 Barometrischer Luftdruck in hPa - Analytics - Nextcloud](https://github.com/Rello/analytics/assets/154433718/236e371d-5f0a-4c14-bef2-4a698c8d56d3)

I checked the JSON file and the values are all correct. 
So I think there is a bug in the JSON Parser.

Best regards and thanks for your work!
Heinrich

**Comment by MMM-Tech-Support** [comment]
Hey again!

Here are some more informations to isolate the bug.
When I run the JSON Datasource in Test Run Mode, i get a correct reading and the value is correct parsed with 3 decimal places.

![Screenshot 2024-07-22 at 22-53-33 Analytics - Nextcloud](https://github.com/user-attachments/assets/97f96b4c-277a-4648-9474-c0e420b7b902)

When I load the same data in non test mode the bug happens and 1014.375 becomes 1014375.

![Screenshot 2024-07-22 at 23-07-43 Luftdruck aktuell - Analytics - Nextcloud](https://github.com/user-attachments/assets/561a7bc6-d66c-4ff9-b8a9-acc04e5a4fa7)

Best regards!

**Comment by Rello** [comment]
Hi,
for simpler debugging, can you attach the json example here?

**Comment by MMM-Tech-Support** [comment]
Hey,

Sure, it's attached. The JSON path to atmospheric pressure is data/values/**0 to 720**/110_133_828

The first datapoint with more than 2 decimal places is at data/values/1/110_133_828

[atmos.json](https://github.com/user-attachments/files/16410932/atmos.json)

Please let me know if you need more information and again thanks for your great work!!!
Best regards

**Comment by Rello** [comment]
working for me. I will do some more testing.
is the error coming up when loading via the "load now" or during scheduled loads?

![Bildschirmfoto 2024-07-29 um 20 48 23](https://github.com/user-attachments/assets/f7a2b568-9a6e-4e83-b330-e73b3417c730)

![Bildschirmfoto 2024-07-29 um 20 48 42](https://github.com/user-attachments/assets/e08f4f35-9c88-4a73-b14f-d4bae9837e19)

**Comment by Rello** [comment]
fyi
<img width="958" alt="Bildschirmfoto 2024-07-30 um 10 44 10" src="https://github.com/user-attachments/assets/27341fd5-ba09-42a7-8b4f-13253b760f13">

**Comment by tatrapikao** [comment]
same when using data from tables app. Value with 3 decimal values is parsed like:  9,600 -> 9,6 but 9,612 -> 9.612
