### ISSUE TITLE
Stacked Bar Chart?

### ISSUE THREAD

**Issue by Himra** [Rello/analytics#399]
Hello everyone,

How can I display stacked bar?
I have tested the following, unfortunately without success.

Diagram options:

```json
{
  "scales": {
    "xAxes": {
      "type": "time",
      "time": {
        "format": "YYYY-MM-DD HH:mm",
        "unit": "day",
        "displayFormats": { "day": "DD. MMM" },
        "tooltipFormat": "HH:mm"
      }
    },
    "yAxes": { "stacked": "true" }
  }
}
```

Data options:

```json
[
  { "yAxisID": "primary", "type": "bar", "stack": "0" },
  { "yAxisID": "secondary", "type": "bar" },
  { "yAxisID": "primary", "type": "line" },
  { "yAxisID": "primary", "type": "bar", "stack": "0" }
]

```

Can anyone help me here?

Thanks in advance.

Greetings Himra

**Comment by Rello** [comment]
Hi,
there is a default stacked option available. did you use this one?

![Bildschirmfoto 2024-07-24 um 23 13 08](https://github.com/user-attachments/assets/f176caba-8c30-4bbb-ae1f-6e767c7c90e1)

**Comment by Himra** [comment]
Oh, sorry. The diagram has been in use for a while and I didn't see this option.

I solved it with your help thanks
