### ISSUE TITLE
Feature to change data range showed in graph

### ISSUE THREAD

**Issue by christoschronopoulos** [Rello/analytics#40]
May I suggest a feature that might be handy? I have a graph report from local NC .csv file with hourly time-series, which gets quite dense day by day. It would be useful to have an option to select the range of the data showing on the graph (e.g. the last 1000 data points). I hope that it can be easily implemented.

**Comment by Rello** [comment]
Hello,

thank you for the request.
yes, I am thinking already about the way to introduce filters, but its rather complex depending on the requirement

- enable filtering in general
- store the filters as e.g. favourites or defaults for a report

This will be he next big upgrade of Analytics. I "only" have to figure out how to do this in an intuitive way
( absolute filters, absolute ranges, dynamic ranges like 2 weeks, ...)

**Comment by Rello** [comment]
Report filter and drilldown dialog #41

**Comment by Rello** [comment]
implemented via  #44
in the next release
