### ISSUE TITLE
dark mode problems

### ISSUE THREAD

**Issue by Himra** [Rello/analytics#400]
Hello everyone,

I found color errors in Nextcloud Dark Mode

![grafik](https://github.com/user-attachments/assets/21534701-83ef-4b46-8806-c5ca6ca6135b)

Greetings Himra

**Comment by Rello** [comment]
nice finding.
I will take care

**Comment by Rello** [comment]
fixed with the upcoming version...

**Comment by tatrapikao** [comment]
also:
![grafik](https://github.com/user-attachments/assets/74209520-e3c1-4d29-8935-478859103c77)
