### ISSUE TITLE
page selector hardly visible in darkmode

### ISSUE THREAD

**Issue by SystemKeeper** [Rello/analytics#404]
<img width="901" alt="image" src="https://github.com/user-attachments/assets/2341aa82-295b-46fb-a8bb-78f64401c4c0">

The "page selector" (not sure if this is the correct name) at the bottom is hardly visible, as it has a black outline (should probably be white)

**Comment by Rello** [comment]
Hallo,
ja, da sind noch ein paar mehr Themen die für NC30 korrigiert werden müssen. danke für den Hinweis

**Comment by Rello** [comment]
problem was solved - along with a lot of other NC30 issues (e.g. all bold texts)
