### ISSUE TITLE
Export of data (as CSV?)

### ISSUE THREAD

**Issue by lars-becker** [Rello/analytics#405]
For month I collected some data from an API with Analytics. Today I wanted to export the data, to process it with pandas. I found out that there is no simple way to export the data as excel sheet oder json file which pandas can read.  While that wasn't much of a hindrance because I could extract the data manually; users without technical background wouldn't be able to extract the data in analytics. A simple CSV export would remedy this situation.

**Comment by Rello** [comment]
Hi,
do you want to permanently move the date out of Analytics, or you want to use the panda frontend?
Analytics has a rest api 
https://github.com/Rello/analytics/wiki/API#data-get

would this help also?

**Comment by lars-becker** [comment]
> Hi, do you want to permanently move the date out of Analytics, or you want to use the panda frontend? Analytics has a rest api https://github.com/Rello/analytics/wiki/API#data-get
> 
> would this help also?

Oh sorry and thanks! I quickly looked into the wiki, but I have overlooked the get data method. That solves my problem. But I still I think a csv export could be nice for non-technical users. Shall I close the ticket or leave it open? :)

**Comment by Rello** [comment]
if you export the report (sidebar), this includes the data array plus the report meta data
