### ISSUE TITLE
Error when editing notes

### ISSUE THREAD

**Issue by Pshpdesu** [Rello/analytics#407]
Encounter errors when i edit notes in notes app.

Logs:
NOTICE: PHP message: [nextcloud][PHP][3] {"reqId":"someid","level":3,"time":"2024-08-30T09:43:35+00:00","remoteAddr":"**.**.**.**","user":"admin","app":"PHP","method":"POST","url":"/apps/text/session/11111/save","message":"Undefined array key 1 at /var/www/html/custom_apps/analytics/lib/Service/DataloadService.php#479","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0","version":"29.0.4.1","data":{"app":"PHP"}}
NOTICE: PHP message: [nextcloud][PHP][3] {"reqId":"someid","level":3,"time":"2024-08-30T09:43:35+00:00","remoteAddr":"**.**.**.**","user":"admin","app":"PHP","method":"POST","url":"/apps/text/session/11111/save","message":"Undefined array key 2 at /var/www/html/custom_apps/analytics/lib/Service/DataloadService.php#479","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0","version":"29.0.4.1","data":{"app":"PHP"}}

Repro:
Edit some note, then let it auto-sync after some time, and then hit save button (Ctrl+S or check mark with dot in right upper corner)

**Comment by Rello** [comment]
Hello,
what notes are you talking about? the notes app? this is not related to analytics at all.
the mentioned error is related to an import of a report within the analytics app. this can not be triggered from outside of Analytics
