### ISSUE TITLE
Database error when running migration 4015Date20240714200000 for app analytics

### ISSUE THREAD

**Issue by ldidry** [Rello/analytics#410]
When updating analytics to version 5.0.0, I got this message:

```
Error: Database error when running migration 4015Date20240714200000 for app analytics
An exception occurred while executing a query: SQLSTATE[23502]: Not null violation: 7 ERREUR:  la colonne « item_type » de la table « analytics_share » contient des valeurs NULL
analytics couldn't be updated
```

The problem appears because of [line 72 of `lib/Migration/Version4015Date20240714200000.php`](https://github.com/Rello/analytics/blob/master/lib/Migration/Version4015Date20240714200000.php#L72). The command adds a non-null column without default value.

I modified the code to make the column nullable and was able to update the app, then made the column non-nullable with an SQL command.

I use PostgreSQL, for information.

**Comment by Rello** [comment]
thank you for that!
this was not found in tests as it relates to a combination of an existing version + existing shares.
a new version will be published.

thank you again
