### ISSUE TITLE
Pull Calendar Data

### ISSUE THREAD

**Issue by vincentmaule** [Rello/analytics#412]
Hello Team,

I am confused with what I am doing wrong with trying to pull Calendar data, I believe I might be doing something wrong with the request itself.

What I found out through searching the [web](https://help.nextcloud.com/t/get-calendar-events-as-json/46539/2) is I could pull my calendar data in a `.json` format via this URL: `https://<NC URL>/remote.php/dav/calendars/<USERNAME>/<CALENDAR>?export&accept=jcal`.

![Untitled](https://github.com/user-attachments/assets/6c9d13b7-09a7-4bd3-9832-11dbd34403d0)

When I try to use the Analytics app to pull the data down, I am just getting a date with a few missing fields.

Could you help point me in the right direction with what I am doing wrong?

Kind Regards,
Vince

**Comment by Rello** [comment]
Hi,

interesting idea.
what are you trying to report here at the first place?

**Comment by vincentmaule** [comment]
> Hi,
> 
> interesting idea.
> what are you trying to report here at the first place?

Hi Rello!

Thank you! I thought so myself & excited to continue to explore this idea.

The goal is to start putting together newsletters based on what is in my calendar. 

Considering this, I know there are a few options. One of them is using the new AppAPI Functionality to manually create a data pull and use other methods.

My goal with this method (Analytics within Nextcloud) is to learn more about Analytics and pull more data.

Look forwward to hearing more thoughts,
Kind Regards,
Vince

**Comment by vincentmaule** [comment]
Hello,

It seems this issues has not had a response in some time. 
As such, we can close this issue.

Thanks for your time,
Vince

**Comment by Rello** [comment]
Hi,
yes, the usecase is a little limited. but the app can be enhanced with additional datasources. I am always open to contributions...
