### ISSUE TITLE
Failed to create document from template

### ISSUE THREAD

**Issue by anoegit** [Rello/analytics#421]
When creating new Office or text files in Nextcloud, the error message always appeared: "Failed to create document from template". In addition, you couldn't use the "save as" function in Collabora.
Since I couldn't narrow down the error even after 2 months, I searched my instance for changes compared to an instance from 3 months ago. Then I deactivated some apps that had been installed since then. When I deactivated the "Analytics" app, everything worked properly again.
The "Analytics"  is definitely the cause of the problem. 
Whenever I install or activate the app, the error comes back.

**Comment by Rello** [comment]
Hello,
during that point of time, something should be in the nextcloud.log file. can you check?

**Comment by anoegit** [comment]
Hallo Rello.

Here is are the 2 Errors in the nextcloud.log

{"reqId":"81b21XEExaT0v9aDmraj","level":3,"time":"2024-12-04T08:41:09+00:00","remoteAddr":"192.168.xxx.xxx","user":"x.xxx","app":"PHP","method":"POST","url":"/nextcloud/ocs/v2.php/apps/files/api/v1/templates/create","message":"Undefined array key \"operation\" at /var/www/html/apps/analytics/lib/Flow/FlowOperation.php#98","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36","version":"28.0.7.4","data":{"app":"PHP"},"id":"67506bec4e49e"}




{"reqId":"1VLd2UnYGHN5Fbcg73hk","level":3,"time":"2024-12-04T08:49:28+00:00","remoteAddr":"192.168.xxx.xxx","user":"x.xxxxxx","app":"no app in context","method":"POST","url":"/nextcloud/ocs/v2.php/apps/files/api/v1/templates/create","message":"Exception thrown: Exception","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36","version":"28.0.7.4","exception":{"Exception":"Exception","Message":"Undefined constant OCA\\Analytics\\Controller\\DatasourceController::DATASET_TYPE_FILE in file '/var/www/html/apps/analytics/lib/Service/DataloadService.php' line 488","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/ocs/v1.php","line":65,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/ocs/v2.php","line":23,"args":["/var/www/html/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":169,"Previous":{"Exception":"Error","Message":"Undefined constant OCA\\Analytics\\Controller\\DatasourceController::DATASET_TYPE_FILE","Code":0,"Trace":[{"file":"/var/www/html/apps/analytics/lib/Controller/DataloadController.php","line":229,"function":"importFile","class":"OCA\\Analytics\\Service\\DataloadService","type":"->"},{"file":"/var/www/html/apps/analytics/lib/Flow/FlowOperation.php","line":114,"function":"importFile","class":"OCA\\Analytics\\Controller\\DataloadController","type":"->"},{"file":"/var/www/html/apps/workflowengine/lib/AppInfo/Application.php","line":102,"function":"onEvent","class":"OCA\\Analytics\\Flow\\FlowOperation","type":"->"},{"file":"/var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":230,"function":"OCA\\WorkflowEngine\\AppInfo\\{closure}","class":"OCA\\WorkflowEngine\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":59,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/html/lib/private/EventDispatcher/EventDispatcher.php","line":94,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/html/lib/private/Files/Node/HookConnector.php","line":162,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/html/lib/private/legacy/OC_Hook.php","line":105,"function":"postTouch","class":"OC\\Files\\Node\\HookConnector","type":"->"},{"file":"/var/www/html/lib/private/Files/View.php","line":1283,"function":"emit","class":"OC_Hook","type":"::"},{"file":"/var/www/html/lib/private/Files/View.php","line":1210,"function":"runHooks","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/html/lib/private/Files/View.php","line":556,"function":"basicOperation","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/html/lib/private/Files/Node/Folder.php","line":190,"function":"touch","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/html/lib/private/Files/Template/TemplateManager.php","line":162,"function":"newFile","class":"OC\\Files\\Node\\Folder","type":"->"},{"file":"/var/www/html/apps/files/lib/Controller/TemplateController.php","line":80,"function":"createFromTemplate","class":"OC\\Files\\Template\\TemplateManager","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"create","class":"OCA\\Files\\Controller\\TemplateController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/ocs/v1.php","line":65,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/ocs/v2.php","line":23,"args":["/var/www/html/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/html/apps/analytics/lib/Service/DataloadService.php","Line":488},"CustomMessage":"Exception thrown: Exception"},"id":"67506bec4e37b"}

**Comment by Rello** [comment]
ok, that is unexpected.
can you please check the settings if you set up a flow action with analytics in some way?

![Bildschirmfoto 2024-12-04 um 16 03 33](https://github.com/user-attachments/assets/c5c0ebd8-e260-49db-b338-fd52713e196c)

**Comment by Rello** [comment]
its not an analytics thing. I would just like to know if you defined any flows. if you do not require support to fix your system, feel free to close the ticket

**Comment by anoegit** [comment]
I don't need support for this at the moment,
but I can't understand the connection between the Ananlytics app and the Collabora Office problems when creating Office files.
If I want to use Analytics again and the problem persists, I will get in touch.

**Comment by anoegit** [comment]
Thank you for the prompt response
