### ISSUE TITLE
Cannot install: Index name "oc_analytics_threshold"."analytics_threshold_dataset_idx" is too long

### ISSUE THREAD

**Issue by fgtham** [Rello/analytics#45]
Installing analytics 2.4.0 into nextcloud 18.0.6 fails with the following error:

```
InvalidArgumentException: Index name "oc_analytics_threshold"."analytics_threshold_dataset_idx" is too long.

/var/www/nc.qcft.de/nextcloud/lib/private/DB/MigrationService.php - line 484:
OC\DB\MigrationService->ensureOracleIdentifierLengthLimit(Doctrine\DBAL\Schema\Schema {}, Doctrine\DBAL\Schema\Schema {}, 3)

/var/www/nc.qcft.de/nextcloud/lib/private/DB/MigrationService.php - line 414:
OC\DB\MigrationService->executeStep("020400Date20200515185352", false)

/var/www/nc.qcft.de/nextcloud/lib/private/Installer.php - line 157:
OC\DB\MigrationService->migrate()

/var/www/nc.qcft.de/nextcloud/apps/settings/lib/Controller/AppSettingsController.php - line 443:
OC\Installer->installApp("analytics")

/var/www/nc.qcft.de/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 170:
OCA\Settings\Controller\AppSettingsController->enableApps([ "analytics"], [])

/var/www/nc.qcft.de/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99:
OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings ... {}, "enableApps")

/var/www/nc.qcft.de/nextcloud/lib/private/AppFramework/App.php - line 125:
OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings ... {}, "enableApps")

/var/www/nc.qcft.de/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:
OC\AppFramework\App::main("OCA\\Settin ... r", "enableApps", OC\AppFramew ... {}, { _route: "s ... "})

<<closure>>
OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "s ... "})

/var/www/nc.qcft.de/nextcloud/lib/private/Route/Router.php - line 299:
call_user_func(OC\AppFramew ... {}, { _route: "s ... "})

/var/www/nc.qcft.de/nextcloud/lib/base.php - line 1008:
OC\Route\Router->match("/settings/apps/enable")

/var/www/nc.qcft.de/nextcloud/index.php - line 38:
OC::handleRequest()
```

Apparently `nextcloud/lib/private/DB/MigrationService.php` [enforces a maximum string length of 30 chars](https://github.com/nextcloud/server/blob/dbb46a72b1cafa15c330515ee2bd0caf8d5151eb/lib/private/DB/MigrationService.php#L519) for index names, which `analytics_threshold_dataset_idx` violates with a count of 31.

**Comment by Rello** [comment]
Hello,
ist an Oracle specific thing. did not know this!?
I will have a look

**Comment by fgtham** [comment]
Hi,

it doesn't seem to be Oracle-specific as I am running MariaDB 10.3. I have no idea about the function naming though, as `ensureOracleIdentifierLengthLimit` does imply vendor-specific handling.

**Comment by Rello** [comment]
thats really strange, because I am locally testing against MariaDB and Postgress
I will shorten it anyway

this setting has been in since a long time without any report yet

**Comment by Rello** [comment]
Hello,
2.4.1 was published
please try again and let me know

**Comment by fgtham** [comment]
Installation of 2.4.1 was successful, the app works like a charm. Thank you very much!

**Comment by Rello** [comment]
thank you for the feedback.

if you find some time, I would like to get some feedback on the use cases of the app.
perhaps you can tell what you are using the app for?
thank you
