### ISSUE TITLE
documentation and SQL db

### ISSUE THREAD

**Issue by ifuchs** [Rello/analytics#46]
Are there any tutorials or documentation on Analytics app? 
Specific question regarding datasources: Is there any way for Analytics to pull data from an SQL (MYSQL or MS SQL or SQlite) db?

**Comment by ifuchs** [comment]
Anyone?

**Comment by Rello** [comment]
Hello,
sorry for the delay. I am just finishing an other app.

currently there is no datasource for an external DB. it would require quite some input parameters for authentication and so so on. but there have been several requests.

can you please write some details on your use case?
what kind of data would you like to report "how"?
what is the structure of the SQL-Table you want to access?

**Comment by Rello** [comment]
Hello,
let me know when you have time to discuss this. then we can reopen the issue

**Comment by potagerGit** [comment]
hello, I would like to do some dashboard on my large music collection, stored in NextcloudMusic App.  
I was hoping to connect directly via SQL to the MusicApp tables (oc_music_* in the MariaDB of Nextcloud) from the Analytics App.

I understand that this is not possible (yet) ?  Maybe a workaround is to dump the tables as Nextcloud Files, on work on the files.

**Comment by paulijar** [comment]
I believe that the "right" way to do such thing would be to create a register a data source in the Music app as described in https://github.com/Rello/analytics/wiki/Register-own-datasource.
