### ISSUE TITLE
Dataload: Purge Dataset

### ISSUE THREAD

**Issue by MarkPartlett** [Rello/analytics#47]
Great product! :)

Could I please request the ability to purge the existing record-set and re-load, for scheduled data loads.

**Comment by Rello** [comment]
Hello,
on the sidebar where you add data manually, you can also delete date.
the input fields accept wildcards *
so deleting ALL should work via * * *
a scheduled deletion/cleanup is not (yet) there

...does this help?
let me know!

**Comment by MarkPartlett** [comment]
Hi @Rello ,
The ability to manually delete is good. :) But I would the delete functionality to be part of the schedule job....That would be great!
Thanks again!

**Comment by Rello** [comment]
hello,
yes, thats a todo. the tricky part will be dynamic variables here like "<2weeks" or so

**Comment by Rello** [comment]
#56

**Comment by Rello** [comment]
Hello @MarkPartlett 

in the first version, there will be the "delete all" option.
this was the simplest to implement for the moment. 
A better integration with parameters/filters will follow later

![Bildschirmfoto 2020-08-29 um 23 59 15](https://user-images.githubusercontent.com/13385119/91646832-d67e2d80-ea53-11ea-9697-5b1aa15165a4.png)

**Comment by MarkPartlett** [comment]
I've tested v3.0 on Nextcloud 20. Thank you!
