### ISSUE TITLE
No available report options for HTML grabber

### ISSUE THREAD

**Issue by AleksovAnry** [Rello/analytics#48]
Can't create report chart from HTML grabber. In Report->Datasource select "HTML grabber" not present. Any idea?

Analytics 2.4.1

![Report->Datasource](https://user-images.githubusercontent.com/21116220/88429619-9d70ee80-cdff-11ea-8c33-9a68c038e5d7.png)

**Comment by Rello** [comment]
Hello,
please to to advanced config
the HTML grabber requires some complex regex - and this is not possible in the basic config.
let me know if you have questions

**Comment by AleksovAnry** [comment]
Thank you for your reply!
Yes, i have some question:

https://weather.com/en-GB/weather/today/l/aad6cfff41f8ff8ba6f7f704388aca9ef8ec099f20666c32d00f240a6f1b9d9f

`/(location--1YWj_">)(?<dimension>.*)(<\/h1><d)(.*)(tempValue--MHmYY">)(?<value>.*)(°<\/span><d)/`

What i did wrong in this regex?

**Comment by AleksovAnry** [comment]
Ok, i understand what's wrong. If i use file_get_contents without headers, in many web sites i got 403 reply. All what we need is add headers.
