### ISSUE TITLE
Thresholds: NC Notification and color coding

### ISSUE THREAD

**Issue by Rello** [Rello/analytics#5]

**Comment by Rello** [comment]
![Screenshot 2019-11-27 at 21 25 29](https://user-images.githubusercontent.com/13385119/69757145-7f61ca00-115c-11ea-8f30-1dca219c0619.png)

**Comment by Rello** [comment]
Hello @nickvergessen

I implemented notifications but I am receiving an error in NC16 - I assume its due to NC17.
Is there a complatibility to work with both or do I need to limit to NC17 now?

`Call to undefined method OC\\Notification\\Manager::registerNotifierService()`

its in Application.php
`\OC::$server->getNotificationManager()->registerNotifierService(Notifier::class);`

**Comment by nickvergessen** [comment]
No, it's not possible to be compatible with 16 and 17 at the same time

**Comment by nickvergessen** [comment]
You would need to have a second Notifier (call it `Notifier16`) and register with `registerNotifier` on the notification manager when that method is available. Or you tell your users that there is cool notifications when they update to 17 and you simply dont register on 16.

**Comment by Rello** [comment]
ok, but how do "not register" with NC16? I would go that route. currently NC17 dependency brakes in total.


and: could you do me a favour and check my implementation to avoid any obvious mistakes? would really be a help
https://github.com/Rello/analytics/blob/c5a2d1db4487d3f9e589e8ddef0632bcf90e5b42/lib/Notification/NotificationManager.php

https://github.com/Rello/analytics/blob/c5a2d1db4487d3f9e589e8ddef0632bcf90e5b42/lib/Notification/Notifier.php

**Comment by nickvergessen** [comment]
https://github.com/Rello/analytics/blob/c5a2d1db4487d3f9e589e8ddef0632bcf90e5b42/lib/AppInfo/Application.php#L34

Replace with:
```php
$notificationManager = \OC::$server->getNotificationManager();
if (method_exists($notificationManager, 'registerNotifierService')) {
    \OC::$server->getNotificationManager()->registerNotifierService(Notifier::class);
}
```

And do the same where you "create" the notification

**Comment by Rello** [comment]
![Screenshot 2019-12-14 at 21 41 23](https://user-images.githubusercontent.com/13385119/70854333-8443af00-1eba-11ea-98e9-abdf284e3905.png)

https://www.youtube.com/watch?v=qnNZafE7ECM

@nickvergessen thank you for your help. next milestone reached!

**Comment by Rello** [comment]
Information: Notifications only working as of NC17
