### ISSUE TITLE
Displayed date & time in UTC

### ISSUE THREAD

**Issue by AleksovAnry** [Rello/analytics#54]
Report displays time in UTC, it not use local/server timezone.

**Comment by Rello** [comment]
Hello,
can you please give me some detail on your data?
did you use the API? which format did you push there?

**Comment by AleksovAnry** [comment]
Hi!
Yes. I HTML Grabber. 
`
URL https://weather.com/ru-RU/weather/today/l/RSXX0063:1:RS
`
`
Regex /(location--1YWj_">)(?<dimension>.*)(<\/h1><d)(.*)(tempValue--MHmYY">)(?<value>.*)(°<\/span><d)/
`
Diagram+table
Type: line
`{"scales":{"xAxes":[{"time":{"displayFormats":{"quarter":"MMM D"}}}],"yAxes":[{},{"display":true}]}}`

**Comment by Rello** [comment]
Hello,
sorry for the late reply.
did you continue here?

I was playing with your regex but its a little difficult. for me I could not get the separation at the "°". this seems to be a tricky one.
https://stackoverflow.com/questions/3140734/unicode-preg-replace-problem-in-php

But this is not your issue, correct?
you are loading the data with the option to add the timestamps, correct?
![Bildschirmfoto 2020-12-02 um 19 33 39](https://user-images.githubusercontent.com/13385119/100915892-48dc2f00-34d5-11eb-857c-93907e00babf.png)

I am still searching on how to handle this issue

**Comment by Rello** [comment]
Finally ;-)
Timestamps are stored in UTC an then calculated to local time for the reporting
