### ISSUE TITLE
API: use display names for upload

### ISSUE THREAD

**Issue by ln-komandur** [Rello/analytics#58]
This is not a functional issue. 
I understand the intent behind naming parameters as  `{'dimension1': xxx, 'dimension2': yyyy, 'dimension3': zzzz}`. I relate to them as below

`dimension1` as `dataName`
`dimension2` as `dataValueAt`
`dimension3` as `dataValue`

Would it help improve code readability, if they could be named such, or are mapped as equivalent? Thank you for your consideration

**Comment by Rello** [comment]
Hello,
this is correct. this is not perfect yet.
I will extend the datamodel in the near future to allow more dimensions and e.g. also  units for the keyfigure. 
when I touch this, the old naming will be also be made more flexible.

Did I understand your request correctly, that you want to use the displayname of the columns, which you defined in the report?

**Comment by ln-komandur** [comment]
Thank you for your kind reply and consideration

I mean, naming the parameters `dimension1, dimension2, dimension3` to what they really are in the output as `dataName, dataValueAt, dataValue`, rather than what they could be referring to. As I said before there is no difference in the functional behaviour, and it only improves readability.

When using `dimension1`, `dimension2` or `dimension3`, I cannot help being reminded of Fortran where `i`, `j`, `k` were commonly used for any integers in the code and also as iterators in `for` loops because the mathematicians liked it from vector analysis. :-) It was very hard for anyone who learned that to break free of that habit even after moving on to other high level programming languages that were designed to promote better code readability. :-)

By saying, 
> or are mapped as equivalent

I meant, keeping both notations as some one might be like `dimension1, dimension2, dimension3` and want to continue using it to pass objects / values

**Comment by Rello** [comment]
Hello,
the best technical way will be to add a /api/v2/ for this. I will provide this as part of the next version. then the user can choose

**Comment by Rello** [comment]
https://github.com/Rello/analytics/wiki/API

**Comment by Rello** [comment]
please see the wiki
the api v2 was extended to work either way
