### ISSUE TITLE
Sharing: user + groups

### ISSUE THREAD

**Issue by Rello** [Rello/analytics#60]
- [x] enabling report sharing for user
- [x] enabling report sharing for group
- [x] <del>enabling report sharing for room</del>
- [x] UI in sidebar
- [x] Integrate stock icons for groups/conversations
- [x] backend to show shared datasets

**Comment by Rello** [comment]
![Bildschirmfoto 2020-08-10 um 21 28 56](https://user-images.githubusercontent.com/13385119/89823100-2d799c80-db51-11ea-94ee-d3e1da7b55da.png)

suggestions as you type
![Bildschirmfoto 2020-08-10 um 21 29 41](https://user-images.githubusercontent.com/13385119/89823108-323e5080-db51-11ea-8b18-565aa116295a.png)

results for all types
![Bildschirmfoto 2020-08-10 um 21 30 03](https://user-images.githubusercontent.com/13385119/89823125-3c604f00-db51-11ea-824e-e563e59c2d5e.png)

**Comment by Rello** [comment]
changing filters/drilldowns in shared report not yet possible

**Comment by thenamelessthing** [comment]
Where I can share a report??I'm not able to find where!

**Comment by Rello** [comment]
hi,
click the "..." next to the report name => basic

![Bildschirmfoto 2021-12-05 um 19 27 51](https://user-images.githubusercontent.com/13385119/144758840-161f0bcd-5ab5-4c59-aa1c-f2bf927c2f50.png)

then on the sidebar you should find it
