### ISSUE TITLE
Different order of months displayed in the diagram and the table view

### ISSUE THREAD

**Issue by Alexander-Thomas** [Rello/analytics#65]
First of all, thank you for this fantastic app!

I must admit, I am a non-techie and true newbie in using this application. 

(1) When I click on „In Analytics anzeigen“ of this csv file below, I get the following result:

<img width="228" alt="Screenshot_1" src="https://user-images.githubusercontent.com/70642963/91987853-db323280-ed2e-11ea-96eb-045ac71a5ecb.png">
<img width="1428" alt="Screenshot_2" src="https://user-images.githubusercontent.com/70642963/91987882-e4230400-ed2e-11ea-9f13-1213e44b65f6.png">

Result: —> Right order of months in the diagram, but wrong order of the months in the table. Is there any way to solve this problem?

(2) If the original csv file contains more than two columns (in this case „Kommentare“), it will crush the diagram completely. Any idea to solve this issue as well?

<img width="261" alt="Screenshot_3" src="https://user-images.githubusercontent.com/70642963/91987914-ef762f80-ed2e-11ea-81ac-4a23cdb919bf.png">
<img width="1432" alt="Screenshot_4" src="https://user-images.githubusercontent.com/70642963/91987962-ff8e0f00-ed2e-11ea-9a6c-d0759e246d91.png">

Many thanks for your support!

Regards from Düsseldorf,
Alexander Thomas

**Comment by Rello** [comment]
Hi,
sorry for the late reply.

Table:
yes, per default it is sorting via alphabet. I am still searching on how to change this. current solutions are quite code intensive. I will keep on searching

Chart:
yes, for technical reasons, the data is expected to have the value/kpi in the last column. if you add the comment before, it will work. you can hide it in the report later if you don´t require it

**Comment by Rello** [comment]
Hello,
die you fine a way to work for your usecase?

regarding the months, it would require coding to convert months to real dates to make them sortable. but thats a lot of find/replace for all languages

**Comment by Rello** [comment]
Hello,
there is no usable way to make the table sort any string in a usable manner.
only chance is to make it e.g. by adding 1_ 2_ or so...
