### ISSUE TITLE
Line not up to date

### ISSUE THREAD

**Issue by tobiasKaminsky** [Rello/analytics#68]
I have a csv file that I update every day and upload to server.
Blue is 2019 and orange is 2020.

![image](https://user-images.githubusercontent.com/5836855/96602623-7f7a3380-12f3-11eb-8520-992932131739.png)

Currently it looks like:
2019,01.01,0
…
2019,31.12,90
2020,01.01,0
…
2019,20.10,84.9

I can see two values for "20.10.":
![image](https://user-images.githubusercontent.com/5836855/96602879-c7995600-12f3-11eb-929d-7f1e1b6e51ee.png)

Now I do not understand why orange line is not shown until 20.10., but only until 17.10.
Interestingly, when I opened it yesterday, it was only shown until 16.10.

Here is the file in question: https://nextcloud.kaminsky.me/s/JSj53rBqok2gBmd

**Comment by tobiasKaminsky** [comment]
I hate to bump…But I tried to find a solution on my own again, today, but did not succeed.
It is now an offset of 5 days…

I really do not understand what is happening…

**Comment by Rello** [comment]
Hey,
sorry. totally forgot about it - was working on the app itself.
can you share the file again, please?

please let me know what graph type you selected. timeline?

**Comment by tobiasKaminsky** [comment]
https://nextcloud.kaminsky.me/s/CWHnpDD3fZk8w5R

![image](https://user-images.githubusercontent.com/5836855/100194175-81887100-2ef5-11eb-8f27-12d968d28b4a.png)

It is the "old?" report.
But if I create new one, it is the same.

**Comment by Rello** [comment]
Hi,
got your dataset - pretty good amount of data to test this.
for me it looks more funny.

I am checking. problem with any normal chart (not timeline) is, that the x-axis values need to be available on both lines. if not - some data missing like in your case - they get shifted.
Like in excel. if one line as 1,2,3,4,5 and the second has 1,4,5, it will align them by sequence and match the 2/4. hope you see what I mean.

let me look at the details.
Better way is the timeline chart (a true x/y coordinate charttype), but its a little picky regarding the format. But there it might be possible to customize it.

I will get back to you
![Bildschirmfoto 2020-11-29 um 20 43 39](https://user-images.githubusercontent.com/13385119/100551829-91041300-3283-11eb-857b-6f2d76afc43a.png)

**Comment by tobiasKaminsky** [comment]
> I am checking. problem with any normal chart (not timeline) is, that the x-axis values need to be available on both lines. if not - some data missing like in your case - they get shifted.
> Like in excel. if one line as 1,2,3,4,5 and the second has 1,4,5, it will align them by sequence and match the 2/4. hope you see what I mean.

I thought that I had filled every gap. In case that my sensor did not reported I added 0 as value.
--> I found 5 missing dates.

So this indeed was the problem!

**Comment by tobiasKaminsky** [comment]
If you have any idea how to make this a bit more robust would be great.
Otherwise I now at least know the cause :)

**Comment by Rello** [comment]
Hello,
yes, either you fix the data - or you tweak the report.
in your case, the timeseries would be very helpfull, because its a true x/y coordinate chart.
But your time value needs some help.

for this, there is the chart options available for advanced tweaking
if you enter this string, there, it will understand your unusual date format

`{"scales": {"xAxes": [{"time": {"format" : "DD.MM"}}]}}`

![Bildschirmfoto 2020-11-30 um 16 37 44](https://user-images.githubusercontent.com/13385119/100630282-a3855780-332a-11eb-893a-824f66a2f064.png)

Advantage of going this way is, that you don´t need "0" records for missing days. I removed them - see in August. then the chart is creating a real timeline

![Bildschirmfoto 2020-11-30 um 16 41 27](https://user-images.githubusercontent.com/13385119/100630488-e6dfc600-332a-11eb-80c6-50afee896e48.png)

helpfull?

**Comment by Rello** [comment]
wiki updated with this usecase
https://github.com/Rello/analytics/wiki/Advanced-chart-options

**Comment by tobiasKaminsky** [comment]
![image](https://user-images.githubusercontent.com/5836855/100758754-27edde00-33f0-11eb-89f8-791c420b14f5.png)


Now it looks like that. Great!

**Comment by Rello** [comment]
You can check the wiki
In your case it might look good to set the x-scaling unit to month 👍🏼

**Comment by tobiasKaminsky** [comment]
![image](https://user-images.githubusercontent.com/5836855/100835518-11866780-346e-11eb-86c0-d755492ea1e0.png)

Awesome :+1:
