### ISSUE TITLE
Database issue for shared reports

### ISSUE THREAD

**Issue by raceface2nd** [Rello/analytics#69]
Hi,

I have installed Analytics 2.5.0 on NC 19.4.

When I open the App the left part, where the "new report" button should appear, nothing appears but the settings button at the bottom.

In the error log of NC I found the following entry.

`{"reqId":"TCCSi7kY4i2JZj2ORhqy","level":3,"time":"2020-11-02T13:39:56+00:00","remoteAddr":"ip overwritten du to security","user":"Administrator","app":"index","method":"GET","url":"/apps/analytics/dataset","message":{"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception occurred while executing 'SELECT \"DS\".\"id\", \"DS\".\"name\", ? AS \"type\", ? AS \"parrent\" FROM \"oc_analytics_dataset\" \"DS\" LEFT JOIN \"oc_analytics_share\" \"SH\" ON \"DS\".\"id\" = \"SH\".\"dataset\" WHERE (\"SH\".\"uid_owner\" = ?) AND (\"SH\".\"type\" = ?)' with params [99, 0, \"admin\", 1]:\n\nSQLSTATE[42P18]: Indeterminate datatype: 7 FEHLER:  konnte Datentyp von Parameter $1 nicht ermitteln","Code":0,"Trace":[{"file":"/var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line":169,"function":"convertException","class":"Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver","type":"->"},{"file":"/var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line":145,"function":"wrapException","class":"Doctrine\\DBAL\\DBALException","type":"::"},{"file":"/var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":911,"function":"driverExceptionDuringQuery","class":"Doctrine\\DBAL\\DBALException","type":"::"},{"file":"/var/www/html/lib/private/DB/Connection.php","line":194,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php","line":200,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":216,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/var/www/html/apps/analytics/lib/Db/ShareMapper.php","line":77,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/html/apps/analytics/lib/Controller/ShareController.php","line":105,"function":"getDatasetsByGroup","class":"OCA\\Analytics\\Db\\ShareMapper","type":"->"},{"file":"/var/www/html/apps/analytics/lib/Controller/DatasetController.php","line":68,"function":"getSharedDatasets","class":"OCA\\Analytics\\Controller\\ShareController","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"index","class":"OCA\\Analytics\\Controller\\DatasetController","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->"},{"file":"/var/www/html/lib/private/Route/Router.php","line":297,"function":"call_user_func"},{"file":"/var/www/html/lib/base.php","line":1011,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php","Line":79,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDOException","Message":"SQLSTATE[42P18]: Indeterminate datatype: 7 FEHLER:  konnte Datentyp von Parameter $1 nicht ermitteln","Code":"42P18","Trace":[{"file":"/var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":903,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDOStatement","type":"->"},{"file":"/var/www/html/lib/private/DB/Connection.php","line":194,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php","line":200,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":216,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/var/www/html/apps/analytics/lib/Db/ShareMapper.php","line":77,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/html/apps/analytics/lib/Controller/ShareController.php","line":105,"function":"getDatasetsByGroup","class":"OCA\\Analytics\\Db\\ShareMapper","type":"->"},{"file":"/var/www/html/apps/analytics/lib/Controller/DatasetController.php","line":68,"function":"getSharedDatasets","class":"OCA\\Analytics\\Controller\\ShareController","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"index","class":"OCA\\Analytics\\Controller\\DatasetController","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->"},{"file":"/var/www/html/lib/private/Route/Router.php","line":297,"function":"call_user_func"},{"file":"/var/www/html/lib/base.php","line":1011,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php","Line":119,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[42P18]: Indeterminate datatype: 7 FEHLER:  konnte Datentyp von Parameter $1 nicht ermitteln","Code":"42P18","Trace":[{"file":"/var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php","line":117,"function":"execute","class":"PDOStatement","type":"->"},{"file":"/var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":903,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDOStatement","type":"->"},{"file":"/var/www/html/lib/private/DB/Connection.php","line":194,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php","line":200,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":216,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/var/www/html/apps/analytics/lib/Db/ShareMapper.php","line":77,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/html/apps/analytics/lib/Controller/ShareController.php","line":105,"function":"getDatasetsByGroup","class":"OCA\\Analytics\\Db\\ShareMapper","type":"->"},{"file":"/var/www/html/apps/analytics/lib/Controller/DatasetController.php","line":68,"function":"getSharedDatasets","class":"OCA\\Analytics\\Controller\\ShareController","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"index","class":"OCA\\Analytics\\Controller\\DatasetController","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->"},{"file":"/var/www/html/lib/private/Route/Router.php","line":297,"function":"call_user_func"},{"file":"/var/www/html/lib/base.php","line":1011,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php","Line":117}},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36 Edg/86.0.622.58","version":"19.0.4.2","id":"5fa00cd1c9cda"}`

Warm regards!

Andy

**Comment by Rello** [comment]
Hi,
thanks for the report.
which DB are you using? you used the app for the first time - so no reports existing, correct?

**Comment by Rello** [comment]
Hello,
any feedback?

**Comment by Rello** [comment]
Hi,
I am working on the fix. are you planning to update to NC20 soon?
this version is continuously supported by Analytics

**Comment by Rello** [comment]
hello @raceface2nd 
did the new version fix the issue for you?

**Comment by Rello** [comment]
hello @raceface2nd 
can you help here?

**Comment by raceface2nd** [comment]
Sorry for the radio silence. I simply oversaw your replies and had no time to examine the issue.
