### ISSUE TITLE
CSV import format validation

### ISSUE THREAD

**Issue by AMDG2** [Rello/analytics#7]
When trying to import CSV from clipboard I have error message. When I check the log I see this:

```
{
	"reqId":"xxxxx",
	"level":3,
	"time":"2019-12-03T15:33:05+00:00",
	"remoteAddr":"xxxxx",
	"user":"xxxxx",
	"app":"PHP",
	"method":"POST",
	"url":"\/index.php\/apps\/analytics\/data\/importCSV",
	"message":"sizeof(): Parameter must be an array or an object that implements Countable at \/path\/to\/nextcloud\/apps\/analytics\/lib\/Controller\/DataLoadController.php#150",
	"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko\/20100101 Firefox\/70.0",
	"version":"17.0.1.1"
}
```

I tried with these CSVs:

```
A;B;B
1;2;3
3;4;5
6;7;8
```

```
A,B,B
1,2,3
3,4,5
6,7,8
```

May be this is not what is expected?

PHP Version Info:
```
php -v
PHP 7.3.12 (cli) (built: Nov 20 2019 19:02:54) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.12, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.12, Copyright (c) 1999-2018, by Zend Technologies
```

If you need more info let me know.

**Comment by Rello** [comment]
Hello,
welcome do Data Analytics.

Please try it without the header. just
```
1,2,3
3,4,5
6,7,8
```
I am still working on hardening/errorhandling here (including better messages).
does it work?

**Comment by AMDG2** [comment]
It works with the suggested CSV.

However I have to double check because it may be related to the fact that I disabled the uBlock origin (most of the assets are getting blocked due to analytics in the name).

**Comment by AMDG2** [comment]
Ok, I can confirm that the suggested CSV works. I will open another issue for the uBlock problem.
