### ISSUE TITLE
An error occurred while searching for Analytics

### ISSUE THREAD

**Issue by frankbootmaker** [Rello/analytics#70]
Using the unified search in NC 20.0.1 I receive the message next to the search icon: "An error occurred while searching for Analytics"

![kép](https://user-images.githubusercontent.com/32898636/98211331-2d1b5280-1f42-11eb-9e52-133899db2dbd.png)

The log in NC 20.0.1 shows:

Error | no app in context | Exception: Argument  2 passed to OCP\Search\SearchResult::complete() must be of the type  array, null given, called in  /var/www/html/custom_apps/analytics/lib/Search/Provider.php on line 65/var/www/html/lib/private/AppFramework/App.php - line 152: OC\AppFramework\Http\Dispatcher->dispatch(OC\Core\Cont ... {}, "search")/var/www/html/lib/private/Route/Router.php - line 308: OC\AppFramework\App::main("OC\\Core\\C ... r", "search", OC\AppFramew ... {}, { action: nu ... "})/var/www/html/ocs/v1.php - line 88: OC\Route\Router->match("/ocsapp/sea ... h")/var/www/html/ocs/v2.php - line 24: require_once("/var/www/html/ocs/v1.php")
-- | -- | --

Error | PHP | Error: Undefined variable: result at /var/www/html/custom_apps/analytics/lib/Search/Provider.php#65/var/www/html/custom_apps/analytics/lib/Search/Provider.php - line 65: OC\Log\ErrorHandler::onError(8, "Undefined variable: result", "/var/www/ht ... p", 65, { user: OC\U ... ]})/var/www/html/lib/private/Search/SearchComposer.php - line 162: OCA\Analytics\Search\Provider->search(OC\User\User {}, OC\Search\SearchQuery {})/var/www/html/core/Controller/UnifiedSearchController.php - line 110: OC\Search\SearchComposer->search(OC\User\User {}, "analytics", OC\Search\SearchQuery {})/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 169: OC\Core\Controller\UnifiedSearchController->search("analytics", "analyt", null, null, null, "/settings/a ... s")/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 100: OC\AppFramework\Http\Dispatcher->executeController(OC\Core\Cont ... {}, "search")/var/www/html/lib/private/AppFramework/App.php - line 152: OC\AppFramework\Http\Dispatcher->dispatch(OC\Core\Cont ... {}, "search")/var/www/html/lib/private/Route/Router.php - line 308: OC\AppFramework\App::main("OC\\Core\\C ... r", "search", OC\AppFramew ... {}, { action: nu ... "})/var/www/html/ocs/v1.php - line 88: OC\Route\Router->match("/ocsapp/sea ... h")/var/www/html/ocs/v2.php - line 24: require_once("/var/www/html/ocs/v1.php")
-- | -- | --

**Comment by Rello** [comment]
Hello,

thank you for the report.
actually it was fixed already, but I did not roll out the fix due to some dependencies.
I will prioritize.

https://github.com/Rello/analytics/commit/04bd867fb6bcf20d7004f6209e1218950aa91e31

**Comment by frankbootmaker** [comment]
Hi,

perfect, I applied it and works. 😊

Many thanks for your quick feedback!

Cheers,
Feri
