### ISSUE TITLE
Unable to load data from JSON into database (SQLSTATE[22007]: Invalid datetime format)

### ISSUE THREAD

**Issue by cole8888** [Rello/analytics#72]
I have a python program which hosts some JSON data at 192.168.2.100:8008. I can access this data with my browser and the Nextcloud server is able to access it as-well, but for some reason it is not able to store any of the data it collects into the database. Upon further investigation I'm getting these errors:
![image](https://user-images.githubusercontent.com/32819560/99632467-a1aac280-2a13-11eb-8dc7-a0b86a0ac155.png)

I tried changing a bunch of settings and following the example for collecting the Nextcloud serverinfo, but it gives the same results.

Any input would be appreciated.

**Comment by Rello** [comment]
Hello,
I will need to check why the normal proper-texted error handling does not work here.
your problem is, that you are reporting "false" for the value column. the value needs to be a decimal number

can you check what you want to do here?
