### ISSUE TITLE
"Limit to groups" not working

### ISSUE THREAD

**Issue by remihb** [Rello/analytics#73]
Top bar icon still appears for users in groups that are not allowed to use Analytics app.
When clicking on icon, it redirects to standard file explorer.

**Comment by Rello** [comment]
hey,
let me check on my instance if I can reproduce.
in general apps being shown there is a Nextcloud thing and not related to the app itself.
did you try again? perhaps old cached data?

**Comment by Rello** [comment]
Hello,
let me know if the issue is still existing. thats an NC standard feature

**Comment by remihb** [comment]
Hi,
nop the icon is still here for me.
Re-tested after fresh install.
