### ISSUE TITLE
Advanced Configuration - Dataload tab does not load

### ISSUE THREAD

**Issue by befel** [Rello/analytics#79]
Hello,

the dataload tab does not load anymore completely since v3.1 (NC20).
Firefox console shows Uncaught TypeError: dataload is undefined see screenshot.
Can anyone confirm this?
![screen](https://user-images.githubusercontent.com/62852717/102812429-46c80a80-43c7-11eb-940b-966f02d54f7b.png)

**Comment by Rello** [comment]
Let me check. All looks good in my testing. Will check with firefox. 
any log in the nextcloud.log?

**Comment by Rello** [comment]
something got lost in your internal variable, which is required.

can you check the following object in the console:
OCA.Analytics.Advanced.Dataload.dataloadArray

![Bildschirmfoto 2020-12-21 um 21 08 56](https://user-images.githubusercontent.com/13385119/102817821-bee6fe00-43d0-11eb-8aa2-cefd911f85c3.png)

I don´t see a FF related issue

**Comment by befel** [comment]
Thanks for your fast reply.
OK maybe something goes wrong during update.
I tried to reinstall the app - without success.
Could you give me some hints how to check.

**Comment by miketkf** [comment]
I have a similar problem to the original poster: I see the same as on the first screenshot, but I do not see the undefined error in the console.

OCA.Analytics.Advanced.Dataload.dataloadArray exists, but looks empty:
 length:0

The browser is Chromium Version 85.0.4183.162 (Official Build) (64-bit)

**Comment by Rello** [comment]
Hello
Any hint in the nextcloud log?

**Comment by Rello** [comment]
Does this happen for every datasource type?
Or just for GitHub?

**Comment by Rello** [comment]
And one more idea: which database are you using?

**Comment by miketkf** [comment]
It is a docker based install, which is using Mariadb. Yes, it happens with all datasource types. I could not find anything obvious in the logs, will check again.

**Comment by Rello** [comment]
ok, also MariadDb & Postgres tested here.

can you please get me the following information:
- open Console -> Network -> Filter for XHR requests
- click on the dataload tap
- there will be one request with the dataset id
- can you post the return/preview?

![Bildschirmfoto 2020-12-24 um 11 06 03](https://user-images.githubusercontent.com/13385119/103081449-3f2b8000-45d8-11eb-8827-2cfe21258dc1.png)

**Comment by miketkf** [comment]
![image](https://user-images.githubusercontent.com/44547215/103105260-f0f49c00-462c-11eb-84e6-26b343536674.png)

**Comment by Rello** [comment]
@miketkf Hi, I think there is a misunderstanding with your part of the issue.
you do not have any dataload created - thats why yours is correct.

- You selected a report
- now you need to create a dataload (choose type in the dropdown and then "+")
- then the dataload will show up above the dropdown (see "new" in the first screenshot)
- then you can select it

I will see how I can make it more obvious in the UI. Also that the "delete data before" is shown is wrong here. it should only be shown once a dataload is selected. will improve this for the next version

**Comment by miketkf** [comment]
Agreed, it is not very intuitive and the documentation is somewhat lacking too. So, I have selected a report, created a JSON dataload with the + and I have selected it:
![image](https://user-images.githubusercontent.com/44547215/103131346-b4fb1e80-46a0-11eb-8741-e238332fbfa0.png)

Still, I can not get the same view as it is on your screenshot.

**Comment by Rello** [comment]
ok, thank you.
I think I have an idea. on your side, all values are returned as strings - even so they are integers like on my screenshot.
let me check the details...

![Bildschirmfoto 2020-12-25 um 11 10 48](https://user-images.githubusercontent.com/13385119/103131637-da3c5c80-46a1-11eb-8da4-e16c9ad78f9b.png)

**Comment by miketkf** [comment]
On the database side it looks good:

![image](https://user-images.githubusercontent.com/44547215/103141497-472d1200-46f5-11eb-99ab-ece4ef74f480.png)

**Comment by Rello** [comment]
thank you. I could not find out why, but I think the backend is transforming the types in some way. I am waiting for ideas from the NC-Team.
Meanwhile I went the safe way to handle them in the frontend.
do you have any chance to apply this commit to your instance?

**Comment by miketkf** [comment]
ok, I applied the patch:

> marcell@atom:~/docker-nextcloud$ docker exec --interactive nextcloud-app cat /var/www/html/custom_apps/analytics/js/advanced.js | grep parseInt
>                     dataload['dataset'] = parseInt(dataload['dataset']);
>                     dataload['datasource'] = parseInt(dataload['datasource']);
>                     dataload['id'] = parseInt(dataload['id']);
>         let typeINT = parseInt(dataload['datasource']);
>         a.dataset.id = parseInt(dataload['id']);
>         a.dataset.datasourceId = parseInt(dataload['datasource']);
>         let dataload = OCA.Analytics.Advanced.Dataload.dataloadArray.find(x => x.id === parseInt(evt.target.dataset.id));
>                 'datasetId': parseInt(document.getElementById('app-sidebar').dataset.id),
>                 OCA.Analytics.Advanced.Dataload.dataloadArray.find(x => x.id === parseInt(dataloadId))['schedule'] = document.getElementById('dataloadSchedule').value;
>                 OCA.Analytics.Advanced.Dataload.dataloadArray.find(x => x.id === parseInt(dataloadId))['name'] = document.getElementById('dataloadName').value;
>                 OCA.Analytics.Advanced.Dataload.dataloadArray.find(x => x.id === parseInt(dataloadId))['option'] = option;
>                 if (parseInt(data.type) !== OCA.Analytics.TYPE_INTERNAL_DB) {
>         data.severity = parseInt(data.severity);
>         const datasetId = parseInt(document.getElementById('app-sidebar').dataset.id);

I restarted everything (docker-compose down & docker-compose up), but I see no change:

![image](https://user-images.githubusercontent.com/44547215/103149336-c7408f80-4768-11eb-9b86-39765d309c64.png)

**Comment by Rello** [comment]
Hi,
Is your instance externally available?
Would it br possible to get a user to test it?

send me a mail to analytics-at-scherello-dot-de

**Comment by miketkf** [comment]
I have sent a mail with the credentials.
