### ISSUE TITLE
Assets blocked by uBlock origin

### ISSUE THREAD

**Issue by AMDG2** [Rello/analytics#8]
uBlock origin is blocking asset loading because of the 'analytics/js' inside the path.

Firefox Console:
![image](https://user-images.githubusercontent.com/1136402/70137774-0a781e00-168f-11ea-9b84-5775cb46c7ad.png)

uBlock Origin Logger:
![image](https://user-images.githubusercontent.com/1136402/70137858-41e6ca80-168f-11ea-8b52-2ca80a8d344c.png)

I will try to find which list contains this filter.

**Comment by Rello** [comment]
hello,
Thats really an interesting finding. but this will be the reason for #6 also
not good

**Comment by AMDG2** [comment]
EasyPrivacy from https://easylist.to/ contains this filter. I think it is a very common list so it is very probably included in other adblockers or privacy tools.

Maybe you could change the app name ?

**Comment by Rello** [comment]
@nickvergessen
a widely used block-list includes a filter for `/analytics/js$script`
this is where my App is being blogged.

I think it can be avoided by using a different subfolder than `/js` for the scripts.
Do you have an idea if this would be possible? because all the `Util::addScript('analytics', 'app');` depend on this folder. can a different subfolder be used via parameter?

thank you

**Comment by nickvergessen** [comment]
You can have subfolders inside js/
But you can not replace js/ I think.
Maybe you can detect it and recomment to disable ublock for your own nextcloud, or you rename your app again to e.g. data_visualization

**Comment by Rello** [comment]
@nickvergessen a rename would mean a new app release because there is no rename process available, correct?
for the remain, the `<id>analytics</id>` would be the one, not the `<namespace>Analytics</namespace>`, correct?

**Comment by nickvergessen** [comment]
yes, `<id>` needs changing, but that value must match the folder name and the entry in the appstore, and .... (exactly the reason why Talk is still running with the appid `spreed` :crying_cat_face: )

**Comment by Rello** [comment]
@nickvergessen 
Yes, I could include a start screen message in my App to disable AdBlock (and hide this message via js, if its working)

But it seems a workaround if we are planning for a wider use of DA. 
DA has 200users already. They need to be informed to install the new app. 

I think about ‚data_analytics‘. 
Later enhancing with modules like ‚data_extraction‘ or ‚data_reporting‘

**Comment by Rello** [comment]
@AMDG2 the implication of changing the app is quite some issue. can you confirm that uBlock can be disabled for your NC-Domain only to make Data Analytics work?

**Comment by AMDG2** [comment]
Yes, for sure. My guess is that it would be the same for adblocker users with any nextcloud instance. Usually they don't have any tracking or advertisement on Nextcloud :sweat_smile: so it should not be an issue.

**Comment by Rello** [comment]
thank you for your feedback.
I am in contact with the creators of Easylist already. In parallel I am implementing a proper warning page

After deactivating uBlock, I hope you enjoy Data Analytics

**Comment by Rello** [comment]
User warning implemented;
![Screenshot 2019-12-05 at 23 28 40](https://user-images.githubusercontent.com/13385119/70279591-15c66900-17b7-11ea-8b19-86a5b033ba31.png)

wiki provided https://github.com/Rello/analytics/wiki/EasyPrivacy-Blocklist;
