### ISSUE TITLE
Showing YYYY-MM-DD HH:MM along x-axis instead of epoch milliseconds

### ISSUE THREAD

**Issue by elapse2039** [Rello/analytics#80]
I have seen you can adjust the x-axis time scale based on examples here: https://github.com/Rello/analytics/wiki/Advanced-chart-options

I have tried setting the time unit to millisecond which is recognised by moment.js library.  
eg: {"scales": {"xAxes": [{"time": {"unit" : "millisecond"}}]}}

However, I still see the original millisecond value on the x-axis of a chart that has this kind of tab-delimited data set...

1608766202000   13.50
1608767103000   13.44
1608768002000   13.31
1608768902000   13.25
1608769802000   13.25
1608770704000   13.19
1608771603000   13.12
1608772503000   13.06
1608773402000   13.06
1608774302000   13.00
1608774864000   12.94
1608774876000   12.94
1608776103000   12.88
1608776642000   12.81

How can I get the Analytics chart to display a more readable timestamp?  For example, YYYY-MM-DD HH:MM along the x-axis using the epoch millisecond values from the local file.

**Comment by Rello** [comment]
Hi,
you were almost correct with the advanced settings. but in your case you wanted to change the output format.
Per default chartjs expects a proper date input - which is not the case in your example.

So what you need to tell chartjs is the input format:
{"scales": {"xAxes": [{"time": {"format" : "X"}}]}}

This works for me.
As you only have a 2-dimensional dataset, don´t forget to hide the second column then.

![Bildschirmfoto 2020-12-25 um 22 52 44](https://user-images.githubusercontent.com/13385119/103142480-e78a3300-4703-11eb-81c6-bb5c9d9fe498.png)

Let me know if it helps...

**Comment by elapse2039** [comment]
Thanks for getting back so quickly!  What value did you substitute for "X" in the format to get that graph?  I have taken a quick look at chartjs and it referes to moment.js for time units.  None of these seem to change the x-axis for me.  WRT your comment about second-column, I only have two columns, the epoch milliseconds and the float.

**Comment by Rello** [comment]
Hey,
per default every dataset has 3 columns. how did you import? file? or clipboard?
the mentioned value above needs to be in the advanced options
![Bildschirmfoto 2020-12-26 um 09 05 40](https://user-images.githubusercontent.com/13385119/103147882-88570d80-4759-11eb-80f7-9ea97effae7a.png)

when you also show the table I expect something like that:
![Bildschirmfoto 2020-12-26 um 09 06 02](https://user-images.githubusercontent.com/13385119/103147893-a45aaf00-4759-11eb-8376-aca2b3bb63a7.png)

the empty column needs to be hidden (drilldown icon on top of the chart) for the chart to work correctly

**Comment by elapse2039** [comment]
I added a csv header to the tab-delimited-file and can see two columns.  The date-field on the graph does attempt to display a date when using Timeline option in Chart Type, but it's not correct.  I can't see a drill-down icon.  I have turned off all my browser ad-blockers. 

epoch   temperature
1608759902000   13.94
1608759970000   13.94
1608760018000   13.94
1608760067000   13.94
1608760083000   13.94
1608760109000   13.94
1608760127000   13.94
1608760219000   13.94
1608760230000   13.94
1608760803000   13.88
...

![screenshot845](https://user-images.githubusercontent.com/5325698/103152705-99ebe580-4758-11eb-9544-6ca9b87a016d.png)

![screenshot846](https://user-images.githubusercontent.com/5325698/103152709-a1ab8a00-4758-11eb-8094-44c8dbf3fd54.png)

So close, but not quite there.  This is running on Nextcloud  20.0.4.0.

**Comment by elapse2039** [comment]
I added a new column, date, and the timeline axis, to match the table you had in yoru screenshot.  Now the timeline looks broken.
![screenshot847](https://user-images.githubusercontent.com/5325698/103152846-e8e64a80-4759-11eb-8f6e-dffe3fb1a6cf.png)

**Comment by elapse2039** [comment]
I've played around with the epoch timestamp and if I shorten the epoch to within a few hours or within a day the graph "looks" right although the x-axis is still not correct.  Looking at your example too, the dates span a much wider date range (several months) than the readings (~1wk).  If I include more than a day's worth of samples, the graph starts plotting like the previous screenshots I've posted on this thread.  So I think the {"scales": {"xAxes": [{"time": {"format" : "X"}}]}} isn't being interpreted by chartjs as expected.

**Comment by Rello** [comment]
ah, wait. you have much closer readings? 
I don´t know the background. but then try with a small "x" - this would correspond to the milisecond format of the timestamp

**Comment by elapse2039** [comment]
That seems to help! Using this option: {"scales": {"xAxes": [{"time": {"format" : "x", "unit":"hours"}}]}} I now get a per-hour timeline that looks aligned with expected reading dates.   Thanks for your help!

(FWIW I did also try using human readable dates (eg: Sat Dec 26 15:52:54 UTC 2020), csv delimited data and got a correct graph with just hours displayed on it.)

![screenshot850](https://user-images.githubusercontent.com/5325698/103154814-3cf82b80-4768-11eb-8508-a50836ce69a3.png)

![screenshot851](https://user-images.githubusercontent.com/5325698/103154830-54cfaf80-4768-11eb-911f-77ae1cbbc136.png)

**Comment by Rello** [comment]
Hey,
but now as you have the input correct, you can try to combine with the output unit format

`{"scales": {"xAxes": [{"time": {"format" : "x","unit" : "hour"}}]}}`

have fun...

**Comment by Rello** [comment]
let me know when you need more - closing it for now...
