### ISSUE TITLE
Missing language keys

### ISSUE THREAD

**Issue by AleksovAnry** [Rello/analytics#86]
That's what i see we missing in the language pack.

`  'Load via occ command:':'Загрузить с помощью команды occ',
    'Timestamp of dataload':'Временной штамп загрузки',
    'valid regex':'Регулярное выражение',
    'Limit':'Лимит',
    'Delete data before load':'Удалить данные перед загрузкой',
    'Favorites':'Избранное',
    'New Report': 'Новый Отчёт',
    'Overview': 'Обзор',
    'Analytics - Advanced Configuration':'Аналитика - Расширенные настройки'
`

+ Not completely understand what mean this key: 'Grant navigation'

**Comment by Rello** [comment]
Hello,
thank you for your quick input!
I will add them and also check the other languages

"Grant navigation". perhaps I should rename it to "allow navigation"?
its when sharing a report, you allow the receiver to also filter/navigate in the report

what do you think?

**Comment by Rello** [comment]
Hi,
will change it to "can navigate" as its is consistent with the rest of NC

**Comment by AleksovAnry** [comment]
Hi! Updated.

**Comment by Rello** [comment]
You are really busy today!
...i still need to add the keys you mentioned above kn all languages. 

Thank you a lot for supporting the App!

**Comment by AleksovAnry** [comment]
+ new missing key
`'Datasource simulation':'Симуляция источника данных'`

**Comment by Rello** [comment]
@AleksovAnry 

can you please translate this string also:
`Report was changed - Press here to save the current state`

post it here, I will put it in.
thank you!

**Comment by AleksovAnry** [comment]
Отчет был изменен - ​​чтобы сохранить текущее состояние, нажмите здесь

**Comment by AleksovAnry** [comment]
Hello there! I'm found something new )
Inside user properties -> Events

`"Analytics: New reports":"Аналитика: Новые отчёты"`
`"Analytics: New data was added to a report":"Аналитика: В отчёт добавлены новые данные"`
