### ISSUE TITLE
Thresholds not read for external report types

### ISSUE THREAD

**Issue by tasagore** [Rello/analytics#9]
I've upgraded from 1.1.0 to 1.2.0, all the graphs works ok but the tables are empty, no matters if I choose table+chart or table, if only shows the headers.

**Comment by Rello** [comment]
Hello,
Do you see an error in the browser log?
Die you enter any threshold already?

**Comment by Rello** [comment]
I think I found the issue. 
Can you confirm that the issue is related to a report from a non-database source like CSV?

**Comment by Rello** [comment]
fixex with 1.2.1
