### ISSUE TITLE
TypeError: Return value of "OCA\Analytics\Command\Load::execute()" must be of the type int, "null" returned

### ISSUE THREAD

**Issue by AleksovAnry** [Rello/analytics#91]
Trying to grap data from web source. Previously it works fine, but now, something went wrong. When i'm ran occ command to load data, i get this error:

root@cloud:/var/www/html/nextcloud# sudo -u www-data php occ analytics:load 12 
An unhandled exception has been thrown:
TypeError: Return value of "OCA\Analytics\Command\Load::execute()" must be of the type int, "null" returned. in /var/www/html/nextcloud/apps/mail/vendor/symfony/console/Command/Command.php:261
Stack trace:
#0 /var/www/html/nextcloud/apps/mail/vendor/symfony/console/Application.php(920): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /var/www/html/nextcloud/apps/mail/vendor/symfony/console/Application.php(266): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Analytics\Command\Load), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/nextcloud/apps/mail/vendor/symfony/console/Application.php(142): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/nextcloud/console.php(100): OC\Console\Application->run()
#5 /var/www/html/nextcloud/occ(11): require_once('/var/www/html/n...')
#6 {main}

Datasource & RegEx:
https://weather.com/ru-RU/weather/today/l/RSXX0063:1:RS
/(location--[\w]+">)(?<dimension>.*)(<\/h1><d)(.*)(tempValue--[\w]+">)(?<value>.*)(°<\/span><d)/

**Comment by Rello** [comment]
die you try to deactivate the mail app - because it looks like this is causing the issue?

**Comment by AleksovAnry** [comment]
Yes, thats is it. Disabling mail helps
