### ISSUE TITLE
JSON Getting Data embbed in Objects

### ISSUE THREAD

**Issue by cecada** [Rello/analytics#93]
Hello,

Forgive me if I am overlooking something... however, is it possible to create a table based on a remote JSON  where the path has an embedded object? See this example for the JSON: https://0bin.net/paste/XxETdJsH#et7aoYdDKf9cRxgMoRpOisWtS5nsuIdvK4TblHgGK00

Lets' say I want a table of all the embedded process_lists? The path would be data/*/process_list (where * would be wildcard card as the index would be 0 - n.  How can this be done? If it is not currently possible can someone get in touch and point me in the direction as to what files may need to be edited to incorporate this feature? I would be more than happy to contribute back.

**Comment by Rello** [comment]
Hi,
is this data available per direct URL? this one does not help obviously...

but see here
https://github.com/Rello/analytics/wiki/Datasource:-JSON

you are accessing a JSON via its object tags.
something like 
`data/process_list`
its difficult to answer this remotely. check your severlogs (see the wiki). perhaps this helps to understand how it works?
let me know

**Comment by cecada** [comment]
```
{
 "status": "ok",
  "data": [
    {
      "md5": "304437e87d37258a54e22c63ee484466",
      "tags": [
        "evasive",
        "odd"
      ]
   },{
      "md5": "304437e87d37258a54e22c63ee484466",
      "tags": [
        "evasive"
      ]
   }, {
      "md5": "304437e87d37258a54e22c63ee484466",
      "tags": [
        "evasive"
      ]
   }
 ]
}
```

Not exactly, I have simplified an example (above). Now if I want just a column of md5 hashes... easy the path is data/md5. But... what if I want:
  
- a list of just the tags in the first object?
- a list of all the tags (depending on the complexity of the JSON data/tags doesn't seem to work, especially if "tags" is embedded in another object of variable length.  

Again, sorry if this is the wrong forum for this "issue." After a lot of poking around, I do not think this a bug, but likely more a request to allow paths to account for embedded variable-sized objects.... or it's very possible I am overlooking some syntax implementation with the app. 

Either way, thank you very much for your help.

**Comment by Rello** [comment]
Hello,
I am sorry, but your idea is currently not working.
because if you go for `data/`, it will get the next level from there. but you need multi-dimensions.
I don´t have an idea at the moment how to do it in a user-friendly way.

Regards...
