### ISSUE TITLE
Parameter to skip header rows in csv and file datasource

### ISSUE THREAD

**Issue by dgedgedge** [Rello/analytics#97]
Hi,
First thanks for the tool.

I was trying to get some gouv info for the corona.
I get this one : 
- [CSV](https://www.data.gouv.fr/fr/datasets/r/f4935ed4-7a88-44e4-8f8a-33910a151d42)
- [Json](https://www.data.gouv.fr/fr/datasets/r/a7596877-d7c3-4da6-99c1-2f52d418e881)

but I was not able to directly use it, because of initial dala rows.
It would be great to be able to specify the start row of the file as well as the colum titles / Date format...

Thanks in advance.

**Comment by Rello** [comment]
Hello,
thank you for the request.
This is about skipping header rows. I will look into this

**Comment by Rello** [comment]
Hello @dgedgedge 
I tested an implementation of a skip-header functionality.
this would be the result of your data. is this what you would expect?

![Bildschirmfoto 2021-01-28 um 16 07 37](https://user-images.githubusercontent.com/13385119/106157505-0eb0a600-6183-11eb-96e4-800dd49d510f.png)

**Comment by dgedgedge** [comment]
Yes, this seems great.
I am not yet an expert in using analytics, but this seems appropriate, and lead to usage of those data.
This answers to the request.

One question we raise for more features are : 
- Will we be able to select the colums to be printed afterward ?
- What about the date format ?
- Could the date be the 2nd column ?
But I think this should be another subject.
Thanks again for your concern.

**Comment by Rello** [comment]
Hello,
what you are asking for is real so called ETL processing.
selecting dedicated columns and so on. 
Its planned but I have to see how I can get this implemented in a usable way

**Comment by dgedgedge** [comment]
OK.
Thanks for all.

**Comment by Rello** [comment]
Approach to make the row selection flexible
![Bildschirmfoto 2021-01-28 um 19 33 15](https://user-images.githubusercontent.com/13385119/106182814-acb26980-619f-11eb-8bbc-4d6e0b183ac3.png)

**Comment by Rello** [comment]
Testing with a selector for the columns.
Would this work for you?

![Bildschirmfoto 2021-01-28 um 23 05 34](https://user-images.githubusercontent.com/13385119/106204478-548a6000-61bd-11eb-9404-a5ff57ed5532.png)

**Comment by dgedgedge** [comment]
That's perfect
