### ISSUE TITLE
SQL error for shared reports

### ISSUE THREAD

**Issue by vacy** [Rello/analytics#98]
Hi Rello,

very very interesting app and I am really curious to try stuff.
But for me nothing works, i am using postgreSQL, nextcloud 20.0.5 and most recent app.

I get this output on the nextcloud.log

> `          "An exception occurred while executing 'SELECT \"DS\".\"id\", \"DS\".\"name\", ? AS \"type\", ? AS \"parrent\" FROM \"oc_analytics_dataset\" \"DS\" LEFT JOIN \"oc_analytics_share\" \"SH\" ON \"DS\".\"id\" = \"SH\".\"dataset\" WHERE (\"SH\".\"uid_ownD (\"SH\".\"type\" = ?)' with params [99, 0, \"apps\", 1]:\n\nSQLSTATE[42P18]: Indeterminate datatype: 7 ERROR:  could not determine data type of parameter $1"`

Full output: https://pastebin.com/wbAPaQ2M

This is what the website looks like for me, i wont know how it should look like having all set up fine, no idea how to use it, its my first install:
![image](https://user-images.githubusercontent.com/9817869/105612981-d5151f00-5dbf-11eb-98c1-10c96969855d.png)

**Comment by Rello** [comment]
that is strange.
the very same error was fixed for 3.1.0
https://github.com/Rello/analytics/issues/69

which Analytics version do you have? can you verify?

**Comment by vacy** [comment]
Its 3.2.0 -> thx for quick reply :)

**Comment by Rello** [comment]
hm. will think about it.
it is typed. I also have a postgres instance her.
lets see....

**Comment by Rello** [comment]
Hello @vacy if you habe the possibility, you could apply the attached patch.
Will be released with the next 3.3 version

**Comment by vacy** [comment]
It works, thanks!
But for me currently looks like your app is not listed on the appstore (not available in my nextcloud instance for install, but listed on public appstore. dunno.... i restored your app from backup and patched successfull)

closing issue.

**Comment by Rello** [comment]
Hi,
I need to keep it open because the fix will be part of the release...
Thank you for confirming!

the appstore is offline at the moment. they have issues there.
additionally, NC has a bug in 20.0.5 with comparing php versions. one of these 2 is the reason for the app not showing up right now
