### ISSUE TITLE
Format of JSON dataload

### ISSUE THREAD

**Issue by puschmie** [Rello/analytics#99]
Hi there,
I was wondering if someone could give me some additional info on how to integrate a JSON datasource.
What format does the JSON data have to be? 
I'm currently sending an array of objects through a REST API and it doesn't display. 
Is it okay to send an array of objects, or does it have to be one single object? For the kind of data I want to display it is very inconvenient to send it is an object and makes much more sense to have an array of objects. 
Also, is there any way to access and monitor command line output of the app? 
In general i think the app is great, but the documentation is a bit sparse for unexperienced people like me.
Thanks for your help!

**Comment by Rello** [comment]
Hello,
happy to enhance the wiki with every usecase.

the REST can handle arrays
```
{
    "data":[
        {
            "dimension1": "x", 
            "dimension2": "y",
            "value": "1,1"
        },
        {
            "Column 1": "x", 
            "Free Text": "y",
            "Percentage": "12"
        }
    ]
}
```
as shown here https://github.com/Rello/analytics/wiki/API#adddata

what are you sending - and how? perhaps you can post the script here?

**Comment by puschmie** [comment]
I'm loading the contents of a mongodb in a nodeserver and sending it through express as so:
`app.get('/get-data',(req,res)=>{
    console.log("incoming get request")
    eventSignUp.find((err,signups)=>{
        if(err) return console.log(err);
        res.send(signups);
    })
})`

The database contains names and email adresses of people who signed up for an event through a form on our website:
[
{name: "John",
email: "email@email.com",
id: "someid",
timestamp: "sometimetamp"},
{name: "Jane",
email....},
...]

**Comment by puschmie** [comment]
Sorry to avoid confusion: I'm using the JSON dataload option, as it seemed to fit my usecase better, not the API dataload for internal databases. 
Is my understanding correct, that the JSON option loads and just displays data from an external API, whereas the API dataload option is an API endpoint to add data to a local database?
I'd like to keep the database in the backend of the website, for dataprotection reasons and not have it in nextcloud, since more people have access there. But I want the analytics app to be able to display the data for certain users. That's why I thought the JSON dataload would be the way to go. Please correct me if I'm wrong

**Comment by Rello** [comment]
naja, here is the thing.
Analytics is no fully flexible database (yet).
due to its current database setup, it can only have 2 dimentions and one value.
they need to be delivered in this way

```
{
            "dimension1": "x", 
            "dimension2": "y",
            "value": "1,1"
        }
```

what do you want to achieve with your data? what is your expected display in the report?

**Comment by puschmie** [comment]
I just want it to be a kind of dashboard to monitor signups for events through our website.

**Comment by puschmie** [comment]
Just another question: What can be in place of x and y? just a single value or an array or object?

**Comment by Rello** [comment]
ok, got it. 
yes, you are correct: API to Push data into the internal DB.
JSON to pull the data into Analytics - either realtime or also persisted in the internal DB.
but you need relatime.

For it to work you need an url to be accessible by Analytics. this is available if I understood correctly.
You could use a json or even a csv if available.

I understand that you need to work with more dimensions. Let me think about it. its a valid request on the todo anyway. But cant promise a timing yet.

But what you will definitely need is a value - at least a 1 to have something countable. Because at the end of the day its about reporting. is this what you were planning?

**Comment by Rello** [comment]
Hello,
did you get your request to work?

**Comment by puschmie** [comment]
Hey Rello, sorry for the slow response. I ended up using forest admin, because it seemed like a better fit for my usecase. I will use Analytics at some point in the future for sure though. Thanks for being so engaged!
Cheers
Jonas
